### ISSUE TITLE
✨ Respect Stage Manager

### ISSUE THREAD

**Issue by UsamaKarim** [MrKai77/Loop#101]
### Feature Request Description

Loop should respect Stage Manager and leave space for it.

### Screenshots

Rectangle example... 
<img width="1440" alt="image" src="https://github.com/MrKai77/Loop/assets/64292174/2c6a4884-00af-4bda-a25c-ce159a549c35">

Loop Example
<img width="1440" alt="image" src="https://github.com/MrKai77/Loop/assets/64292174/7700fb57-f01e-451c-af01-55816af1a023">

### Additional Context

Loop does not respect Stage Manager, in Rectangle, it leaves space for Stage Manager and even if maximizing to full screen the stage manager hides and can be visible while hovering the mouse on the left side of screen, but that's not the case with Loop.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Great idea! I personally don't really use Stage Manager, but now that I think about it, this seems like an essential feature! I'll look into this!

**Comment by MrKai77** [comment]
Here's a build with it working!
It's enabled by default, and can be configured in the "More" section of the settings window.

[Loop.zip](https://github.com/MrKai77/Loop/files/13762785/Loop.zip)
