### ISSUE TITLE
✨ Copy Button for Version Number

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#105]
### Feature Request Description

It would be helpful to have the version number automatically copied to the clipboard when clicked or to have a button for copying it. Using a hyperlink would make it look cleaner, but a button would make the feature more obvious.

This is obviously only used for making bug reports easier.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Great idea! Just added it here:
<img width="319" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/68b6cb7a-c12a-4810-9901-56883c69b960">

Making it a button made it look too chunky, so I just added a little pasteboard icon to indicate that the user can copy it! What do you think?

**Comment by JaceThings** [comment]
I was actually thinking here 😅, I never even thought or have used the about page yet 😭
![000778@2x](https://github.com/MrKai77/Loop/assets/60551230/8d83b12a-d636-4782-8b6c-8f7a24d92224)

**Comment by MrKai77** [comment]
OH I guess I should add it there too 😂

**Comment by MrKai77** [comment]
ok here's the latest build, with the functionality to copy the version from the settings window:
[Loop.zip](https://github.com/MrKai77/Loop/files/13519771/Loop.zip)
