### ISSUE TITLE
✨ Resize window under cursor

### ISSUE THREAD

**Issue by MrKai77** [MrKai77/Loop#106]
### Feature Request Description

This was a feature that was requested on Reddit.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by Dhairy2003** [comment]
@MrKai77 How does the pointer focus works ?? i tried using it with inactive windows but cant bring it to work

**Comment by MrKai77** [comment]
Hmm... It works correctly on my computer 🤔
Does Loop not resize anything or does it still resize the frontmost window on your side?

**Comment by Dhairy2003** [comment]
@MrKai77  its working , I didnt enable the setting  🥲. Thanks a lot 🫡

**Comment by MrKai77** [comment]
That's definitely a bug :(

Can you try out this build and see if it works?
[Loop.zip](https://github.com/MrKai77/Loop/files/13800211/Loop.zip)

If not, does window snapping still work? They both use the same method to get the window under the mouse. If not, then I'd suggest making a new issue.
