### ISSUE TITLE
✨ More preview window customization options

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#114]
### Feature Request Description

Make the preview more customizable, as in option to change color, blur etc.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup! 
Adjustable blur is planned in #103.

**Comment by MrKai77** [comment]
Since this is essentially a duplicate of #103, I'll be closing this to prevent any duplication :)
