### ISSUE TITLE
✨ Smoother animations

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#115]
### Feature Request Description

Hopefully make the animations(in preview as well as windows size changing) a bit smoother so that it has near native experience like windows

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Alright, I managed to remove the initial flicker, but otherwise, I think it's impossible to make the window resize even smoother without injecting code into Dock.app like how Yabai does it.

**Comment by MrKai77** [comment]
As for making the preview window animation feel smoother, you can configure the Animation Speed in the settings window. (The "Fast" option might be what you're looking for)
