### ISSUE TITLE
✨ A option to use it with a mouse button 

### ISSUE THREAD

**Issue by Dhairy2003** [MrKai77/Loop#118]
### Feature Request Description

Currently this works only by having a keyboard key setup, if possible pls try setting up a mouse button to use this, this will enhance the experience for those who dont use keyboard much (people who trading and stuff). Loved the app , one of the best i have used 😁

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
You can map middle click to open Loop in its settings :)
