### ISSUE TITLE
✨ Pointer Focus 

### ISSUE THREAD

**Issue by Dhairy2003** [MrKai77/Loop#119]
### Feature Request Description

Can u try adding pointer focus like amethyst , though amethyst is a lot buggy lately and isnt that smooth as loop . But pointer focus is one of the feature which really saves clicks . If possible a shortcut to enable/disable it using the loop set key. Great application , One of the best i have tried 😁

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by Dhairy2003** [comment]
https://github.com/MrKai77/Loop/assets/101127874/5debd787-34ee-4299-b364-592dd50d32a2

**Comment by MrKai77** [comment]
Thanks!
Would this be a duplicate of #106?

**Comment by Dhairy2003** [comment]
yes 😅, also are there any window tiling features on agenda ?

**Comment by MrKai77** [comment]
if tiling features mean similar functionality to Amethyst, unfortunately not :(
