### ISSUE TITLE
🐛 “Loop.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by matty2k** [MrKai77/Loop#120]
### Bug Description

“Loop.app” can’t be opened because Apple cannot check it for malicious software.

### Steps To Reproduce

“Loop.app” can’t be opened because Apple cannot check it for malicious software.

### Expected Behavior

“Loop.app” can’t be opened because Apple cannot check it for malicious software.

### Actual Behavior

“Loop.app” can’t be opened because Apple cannot check it for malicious software.

### MacOS Version

Sonoma Version 14.2.1

### Loop Version

latest

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
You can open Loop by right clicking `Loop.app`, then pressing "Open". I will make sure to add this to the README.
