### ISSUE TITLE
🐛 Eudic cannot resize

### ISSUE THREAD

**Issue by zhanglolo** [MrKai77/Loop#121]
### Bug Description

Eudic can not resize

### Steps To Reproduce

all shortcut

### Expected Behavior

normal

### Actual Behavior

resize error

### Screenshots

https://github.com/MrKai77/Loop/assets/27875371/04b76caf-eec1-4b37-b126-ab300010e189

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.12 (515)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Got it! Are other window management apps (such as Rectangle) able to move the window, or is it just Loop?

**Comment by zhanglolo** [comment]
currently I use raycast window management, i use magnet earlier, both works fine.

**Comment by zhanglolo** [comment]
Also some app (qq、wechat) resize behaviour look like the same as eudic. 
If you need, i'd  be happy to provide more help.

**Comment by MrKai77** [comment]
Alright, try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/13799549/Loop.zip)
I just removed a bit of logic to detect if the selected UI element's subrole is a standard window :)

**Comment by zhanglolo** [comment]
> Alright, try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/13799549/Loop.zip) I just removed a bit of logic to detect if the selected UI element's subrole is a standard window :)

The window still behaves incorrectly

**Comment by MrKai77** [comment]
I apologize for the late answer (again) 😅
Please try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14765457/Loop.zip)
it has support for `AXEnhancedUserInterface`, which is what I believe is the cause of this issue.

**Comment by zhanglolo** [comment]
> I apologize for the late answer (again) 😅 Please try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14765457/Loop.zip) it has support for `AXEnhancedUserInterface`, which is what I believe is the cause(原因) of this issue.

it works! thanks!
