### ISSUE TITLE
✨ Update soon? 👉👈

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#122]
### Feature Request Description

Can we get a status update on Loop? 😅 
It's been 3 weeks since the last commit, just wondering how this app will progress 👉👈

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Sorry about that!
I've been quite busy lately, but my winter break starts this Friday so I should be able to work more on Loop more after that!

**Comment by JaceThings** [comment]
No problem, I'm just very, very happy with this app. I check this repository about once every three days to see updates <3. Take your time! I just wanted to see if everything was okay.
