### ISSUE TITLE
✨ Move Windows when "Show Preview when looping" is disabled.

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#128]
### Feature Request Description

When the "Show Preview when looping" option is disabled, the radial menu loses its usefulness because there is no way to determine the current "level" when switching between different levels of the same keybind.

 For example, pressing [Keybind] + D moves the window to the right and cycles through three different sizes, but this cannot be visualized without a preview. 

To improve clarity and mental understanding, I suggest using the window itself as the size identifier, similar to how a rectangle does. Although this renders the radial menu useless in this scenario, I believe it is worth it for the sake of speed.

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/deaa1048-8f86-4c10-89a1-5e22b9845e6c

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Ohh actually I think this is a great idea! As of right now, disabling the preview window doesn't make any sense, so this would help make that setting actually useful!

**Comment by MrKai77** [comment]
Let me know how this is! 
(This also includes other changes on the `develop` branch so you will notice other new features too!)

[Loop.zip](https://github.com/MrKai77/Loop/files/13762705/Loop.zip)

**Comment by JaceThings** [comment]
This is amazing. Even better with the "Hide until direction is chosen" option. Love it!!!!
