### ISSUE TITLE
🐛 window snapping not working

### ISSUE THREAD

**Issue by KoukeNeko** [MrKai77/Loop#134]
### Bug Description

The window snapping feature in the Loop application on macOS stops working after extended use. Initially functional, the feature fails over time, preventing windows from snapping as set in the user preferences. This issue arises without specific triggers or error messages.

### Steps To Reproduce

1. make sure the window snapping is on
2. use macOS for a while
3. you will notice that the window snapping is not working

### Expected Behavior

window snapping keep working

### Actual Behavior

window snapping is not working

### Screenshots
screen record
[_No response_](https://youtu.be/BRP7ya5_dzk)

### MacOS Version

Sonoma 14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.12 (515)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Interesting!
Would you be able to try this build? [Loop.zip](https://github.com/MrKai77/Loop/files/13763067/Loop.zip)
It contains all the latest changes. But I have noticed that it has issues with external displays 😉

**Comment by KoukeNeko** [comment]
After downloading the version you provided, it now works properly. I will continue to monitor the app's working! 🥳
Although it destroys my previous keybindings. : (

**Comment by MrKai77** [comment]
Oh sorry, I completely forgot to mention that! 🙇
Loop's keybind system is in the process of being remade, and unfortunately you will lose all your previous keybinds in the process :(

**Comment by KoukeNeko** [comment]
Now, there is no keybindings function lol

**Comment by KoukeNeko** [comment]
After using it for several hours, I've found that the window snapping feature works flawlessly, even though this is a very early build. However, I've encountered two bugs that need attention:

The keybindings issue was mentioned earlier.
The 'Resize window under cursor' function seems inoperative. In my experience, there's no noticeable difference when it's toggled on or off. Specifically, when I switch from maximum to normal mode, the window just shifts abruptly to the left side of my 3440x1440 monitor.

**Comment by KoukeNeko** [comment]
Update: The keybindings are now functioning correctly on the built-in monitor.

https://github.com/MrKai77/Loop/assets/111033412/c22afcd8-8e70-4af8-aeae-c37232990b81

**Comment by MrKai77** [comment]
> The 'Resize window under cursor' function seems inoperative. In my experience, there's no noticeable difference when it's toggled on or off. Specifically, when I switch from maximum to normal mode, the window just shifts abruptly to the left side of my 3440x1440 monitor.

Would you be able to explain this further? I can't seem to reproduce it on my side :(

**Comment by MrKai77** [comment]
> Update: The keybindings are now functioning correctly on the built-in monitor.

Oh perfect! I'll close this issue then!
