### ISSUE TITLE
✨ Display a secondary radial menu when cursor exits first one

### ISSUE THREAD

**Issue by ankidoc** [MrKai77/Loop#137]
### Feature Request Description

Hello. I use 2 monitors, and it would be great if I could use the app to snap windows from the first monitor within the first monitor, but at the same time also target the second monitor with the same possible window locations.

Maybe you now the app charmstone? It's actually a launcher, but it has a nice feature: When you trigger it, you can choose app from a circle to launch, exactly like loop does with window position directions. But in charmstone, when you leave the inner circle, the displayed apps change so you can have more variety. My ideas was, if leaving the inner circle would trigger another ring or at least the other monitor, so I don't have to first switch the monitor with the window and then triggered loop, so I could skip this step. I hope it's clear what I mean.

### Screenshots

here from charmstone feature:

![_h4p3mDW2](https://github.com/MrKai77/Loop/assets/81517565/f648faf0-fd34-48f8-bc69-d6fb651ab8ef)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
I think I understand!
Would this be building on the functionality of having a secondary function on the radial menu (#108)?

**Comment by ankidoc** [comment]
feeling so dumb, I just saw it a minute ago, then saw how quickly you connected my issue to this. Sorry! But yes! That's excatly the point

**Comment by MrKai77** [comment]
No problem!
I might not be able to get this done by the next beta, but once I get to implementing it, I'm most likely going to do this, #108, and #107 all in one :)

**Comment by ankidoc** [comment]
nice! Since I'm not coder or anything but next β always sounds so big. Do you think it's more like a year or more like a month from a time perspective?

**Comment by MrKai77** [comment]
Haha I do one beta release around once or twice a month so I'd say a month at most!

EDIT:
> Since I'm not coder or anything...

Out of curiosity, how did you find Loop?

**Comment by ankidoc** [comment]
> Haha I do one beta release around once or twice a month so I'd say a month at most!
> 
> EDIT:
> 
> > Since I'm not coder or anything...
> 
> Out of curiosity, how did you find Loop?

I love apps. I do quite intense searching for new apps every 1-2 months. And I absolutely love those on point launcher apps like commander and charmstone. Your app is beautiful, quick and simple. Good recipe for an amazing app. I do use better touch tools for window alignment too, but it sometimes is not as reliable due to lags or bugs. Yours is way more stable'

and awesome, 1 month sounds super nice!

**Comment by MrKai77** [comment]
Hey sorry I've been really busy lately, but this is something I want to finish soon :(

Since this is also really similar to #108's functionality, I'll be closing this so that important information doesn't get split across multiple issues with a lot of overlap.
