### ISSUE TITLE
✨ No Grid?

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#139]
### Feature Request Description

I can't lie, I kinda don't like the grid on these menus. I much prefer the flat background. Just a thought.

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/60551230/f85ad535-5ed8-4f48-ad41-160eb4263345)
![002192@2x](https://github.com/MrKai77/Loop/assets/60551230/99a97ac2-99f6-4a4d-91fb-0fa50a4eb8ab)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Interesting! If the grids were removed, would you prefer that the background was still translucent? Or should it be returned completely back to how it was before?

**Comment by JaceThings** [comment]
I liked the translucency! It was a very clever idea to almost mimic what it would look like when you actually use it. Adding the grid made it feel like, "Oh, this is a testing chamber," when without it, it was almost like you're peeking into the app without needing to run your own tests.

**Comment by MrKai77** [comment]
Ohh haha, I was thinking of the background of a blueprint when I added the it 😅
(Although I originally created the grid shader for #103 😋)

**Comment by JaceThings** [comment]
Ah, makes sense. Since it wasn't cascaded to the actual preview, I thought it was just a design choice. In that case, if it were to be displayed, you have my full support (just make it an option and not forced <3)

**Comment by MrKai77** [comment]
Got it! I'll maybe also try and make the grid look more like a blueprint!

**Comment by MrKai77** [comment]
Ok now that I look at it, all I can see is a testing chamber 😓
I experimented without other blueprint designs, but none of them ended up looking like a blueprint, so now I think that removing the grid altogether in the settings window would be the best way to proceed :)

**Comment by MrKai77** [comment]
Here's a version without the grid!
[Loop.zip](https://github.com/MrKai77/Loop/files/13796435/Loop.zip)
