### ISSUE TITLE
🐛 Arrow keys on Apple Magic Keyboard doesn't work

### ISSUE THREAD

**Issue by caocanx** [MrKai77/Loop#14]
### Bug Description

Keyboard: [Magic Keyboard with Touch ID](https://www.apple.com/shop/product/MK293KU/A/magic-keyboard-with-touch-id-for-mac-models-with-apple-silicon-korean)

### Steps To Reproduce

1. hold global key
2. press arrow keys

### Expected Behavior

preview show up

### Actual Behavior

radial menu show up, but when press arrow keys nothing happen. (WASD keys works well)

### MacOS Version

Ventura 13.4.1

### Loop version

Version 1.0.0-beta.7 (256)

**Comment by MrKai77** [comment]
Thanks for reporting this bug!
I can reproduce this with my built-in keyboard on my MacBook as well. I will look into this!

**Comment by MrKai77** [comment]
Here's the latest build with this bug fixed 😉
[Loop.zip](https://github.com/MrKai77/Loop/files/12481364/Loop.zip)

**Comment by caocanx** [comment]
> Here's the latest build with this bug fixed 😉 [Loop.zip](https://github.com/MrKai77/Loop/files/12481364/Loop.zip)

Thank you, it works.
