### ISSUE TITLE
🐛 Displaced window when using `Restore window frame on drag`

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#148]
### Bug Description

When `Restore window frame on drag` is enabled, moving from `Maximize` or `Top Half` by dragging from the right side of the window makes it shift to the left.

### Steps To Reproduce

1. Dra a window to `Maximize` or `Top Half`
2. Drag a window from the right side

### Expected Behavior

The window should be located under the mouse pointer.

### Actual Behavior

The window is shifted to the left.

### Screenshots

![Displaced window](https://github.com/MrKai77/Loop/assets/101254295/a1043594-ce32-4464-8f64-90410f70c7e6)

### MacOS Version

Sonoma 14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (599)

### Additional Context

I'm using the latest build found in #77.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Here's a fixed build, which also contains the latest features from #149 :)
[Loop.zip](https://github.com/MrKai77/Loop/files/13837791/Loop.zip)

**Comment by Zabriskije** [comment]
Awesome! Everything seems working :)
