### ISSUE TITLE
🐛 Resizing maximized window from the left border triggers Loop

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#149]
### Bug Description

When a maximized window is resized from the left border, Loop gets triggered.

### Steps To Reproduce

1. Maximize a window
2. Drag from the left border

### Expected Behavior

Loop shouldn't get triggered.

### Actual Behavior

Loop gets triggered.

### Screenshots

![Left border bug](https://github.com/MrKai77/Loop/assets/101254295/288e101e-e23e-4109-a52d-effcc1df6ccc)

### MacOS Version

Sonoma 14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (599)

### Additional Context

I'm using the latest build found in #77.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thanks for the bug report!
I just realized that window snapping triggers when a window's top left corner has been moved, but I guess a better way to do that would be to detect if the top left *and* bottom right corner of a window have been moved.

**Comment by MrKai77** [comment]
Let me know how this build is! I also managed to improve its behaviour on multi-display setups :)
[Loop.zip](https://github.com/MrKai77/Loop/files/13823040/Loop.zip)

**Comment by Zabriskije** [comment]
Now Loop doesn't get triggered, but it seems like the border is "sticky" until a certain point. It also makes `Maximize` and `Top Half` not working after the first try.

![Latest build test](https://github.com/MrKai77/Loop/assets/101254295/bb97a5e3-40cd-49f0-ae6b-c859642c5b84)

**Comment by MrKai77** [comment]
Alright, I fixed the `Maximize`/`Top Left` not triggering on the first try! 
[Loop.zip](https://github.com/MrKai77/Loop/files/13836662/Loop.zip)

As for the "stickiness", I'm fairly sure that it's a feature built-in to MacOS to assist with moving windows, since I'm able to reproduce it when Loop isn't running.

**Comment by Zabriskije** [comment]
> As for the "stickiness", I'm fairly sure that it's a feature built-in to MacOS to assist with moving windows, since I'm able to reproduce it when Loop isn't running.

Yup, you're right. I didn't notice that until today.

Seems fixed 👌
