### ISSUE TITLE
✨ Possibility to trigger emoji shortcut if just tapped

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#151]
### Feature Request Description

There is an issue where if the delay is set to 0 and the fn key is used, the emoji shortcut set by macOS will be overridden, which I believe is expected behavior. Would it be possible to trigger this shortcut if the fn key is just tapped without any shortcut keys or mouse movement registered? Just hoping there might be a way to enable both.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Let me know how this is!
[Loop.zip](https://github.com/MrKai77/Loop/files/13837575/Loop.zip)


Unfortunately, looping fast also triggers the emoji menu, but I don't think there's a way to bypass that :(

**Comment by jacksongoode** [comment]
Yep this works! Hmm I see what you mean about looping with the mouse quickly triggering it. Is it possible to suppress if mouse activity is registered?

**Comment by MrKai77** [comment]
Great idea! Here's a build with that feature:
[Loop.zip](https://github.com/MrKai77/Loop/files/13867199/Loop.zip)

**Comment by jacksongoode** [comment]
Works well! Hopefully there's a path into main?

**Comment by MrKai77** [comment]
Awesome!
Yup, I made sure that this won't interfere with any other keybindings, so I'll probably merge this tomorrow :)
