### ISSUE TITLE
✨ Larger Window Padding Values

### ISSUE THREAD

**Issue by lk-code** [MrKai77/Loop#154]
### Feature Request Description

another little thing :D

I can currently specify a maximum of 20px as window padding. I love the space around the windows, so I would appreciate it if I could get even bigger options ;)

### Screenshots

<img width="480" alt="Bildschirmfoto 2024-01-06 um 00 37 25" src="https://github.com/MrKai77/Loop/assets/1656571/99c31fbc-cbb5-441a-8022-c179788f27d3">

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by JaceThings** [comment]
Preferably each value with a slider should be a numerical input :P

**Comment by lk-code** [comment]
Yeah, I mean a max value at 50px (for example) not 20px ;)

**Comment by MrKai77** [comment]
Done!
[Loop.zip](https://github.com/MrKai77/Loop/files/14003097/Loop.zip)

> Preferably each value with a slider should be a numerical input :P

Since I think this might better if it was applied on all sliders, I think this might be better suited as its own issue :)

**Comment by lk-code** [comment]
thanks, i love it :D
