### ISSUE TITLE
✨ Adjust Size Feature

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#155]
### Feature Request Description

I often use the window resizing feature to test various resolution sizes without needing to access the inspect panel in my browser.

It would be great to use my personal keybind (`⌘ ⌥ ⌃ ⇧` + `+` / `-`) to resize a window by a specific amount and direction.

Rectangle achieves this by checking if the window is touching any desktop walls. If it is, it expands the window by X units on each side.

### Screenshots

![002439@2x](https://github.com/MrKai77/Loop/assets/60551230/14e668d4-ee91-4353-8902-4f7eeb6355cf)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by JaceThings** [comment]
Bump

**Comment by MrKai77** [comment]
Sorry for the late answer!
Here's a build with these changes: [Loop.zip](https://github.com/MrKai77/Loop/files/14795628/Loop.zip)

Edit: Already noticed a bug when the preview window is disabled 💀

**Comment by MrKai77** [comment]
Alright, here's a fixed version:
[Loop.zip](https://github.com/MrKai77/Loop/files/14796353/Loop.zip)

Let me know if you find any bugs!

**Comment by JaceThings** [comment]
I don't know if it's a bug, but it feels like that when lessening to the size, and your window is already touching certain parts of the screen, like in the video, instead of decreasing size from all four sides it should decrease the size from the area that is not already touching a part of the edge of the screen. Increasing the size works as expected, but reducing the size feels weird.

Also, I think it would be cool to
1. Be able to specify the amount of size that will be added or removed.
2. Have individual keybinds for bottom, top, left, and right, and each of the four corners (asking too much probably)


https://github.com/MrKai77/Loop/assets/60551230/aca36df0-c8f4-4790-bd51-b3e42cd8f6e9

**Comment by MrKai77** [comment]
Phew, just finished! Try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14798857/Loop.zip)
I didn't do corners for the time being, since the user can already resize the window from the sides :)

**Comment by JaceThings** [comment]
1. Seems like one can not swap an existing keybind to any of the new ones:

| Add New | Change Existing |
|--------|--------|
| ![007003@2x](https://github.com/MrKai77/Loop/assets/60551230/a755a08b-057c-4393-a7ef-6d5ccdabd355) | ![007002@2x](https://github.com/MrKai77/Loop/assets/60551230/b2938c7d-6016-4e76-97e2-44a0fad30bbe) | 


2. I see you made "Make size increments user-configurable" in e5f5a669411832374df5d6b5582df65c192e21bf, but i can't seem to find that?

![007004@2x](https://github.com/MrKai77/Loop/assets/60551230/fed8af39-2392-4609-aca3-7de21450ae7e)

3. In reference to this, there are many bugs. Gonna post a video with speech just because its easier to explain.
 > I don't know if it's a bug, but it feels like that when lessening to the size, and your window is already touching certain parts of the screen, like in the video, instead of decreasing size from all four sides it should decrease the size from the area that is not already touching a part of the edge of the screen. Increasing the size works as expected, but reducing the size feels weird.
 
Video:
 https://li.mt/ylXt9v7S

**Comment by MrKai77** [comment]
> 2. I see you made "Make size increments user-configurable" in https://github.com/MrKai77/Loop/commit/e5f5a669411832374df5d6b5582df65c192e21bf, but i can't seem to find that?

It is available in the "More" Tab of the settings window:
![image](https://github.com/MrKai77/Loop/assets/68963405/8491bc3c-8e61-43b4-aea2-8aacc79b7699)

As for 1 and 3, try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14806693/Loop.zip)
Thank you so much for the voiced video! You were correct: Loop didn't know when the user changed sides :)

**Comment by JaceThings** [comment]
1. Works :)
2. Omg you implemented hold to repeat for sizing, this is so nice, would love to have it for all actions, like in https://github.com/MrKai77/Loop/issues/111

**Comment by MrKai77** [comment]
> Omg you implemented hold to repeat for sizing, this is so nice, would love to have it for all actions, like in https://github.com/MrKai77/Loop/issues/111

Yup! However, unlike #111, this simply implements `NSEvent.isARepeat`, which is something the user can configure in System Settings!

Anyways, I am also planning to release a new version of Loop tonight so let me know if you find any bugs (since they need to be fixed asap)! Otherwise, I will merge this later today!
