### ISSUE TITLE
🐛 Window Snapping and Displacement Issue in MacOS (Both Standard and Stage Manager Modes)

### ISSUE THREAD

**Issue by KoukeNeko** [MrKai77/Loop#156]
### Bug Description

In MacOS, resizing a window often triggers an unintended window snapping feature. This issue is prevalent both in standard mode and in Stage Manager mode. The cursor changes to a double-sided arrow when it reaches the screen edge, leading to unwanted window snapping. In Stage Manager mode, this behavior becomes more pronounced. After a window is maximized to fill the screen and then resized again, it tends to move unexpectedly and lose its previous placement. This issue is acute with external monitors but also occurs with the built-in screen.

### Steps To Reproduce

1. Enter Stage Manager mode on MacOS. (Optional)
2. Maximize a window to fill the screen.
3. Try resizing the window by dragging the edges.
4. Observe the window snapping and displacement behavior.

### Expected Behavior

The window should resize smoothly without unintended snapping or displacement, maintaining its position and size as adjusted by the user.

### Actual Behavior

The window snaps unexpectedly to screen edges and displaces from its intended position when resized, especially in Stage Manager mode and more so with external monitors.

### Screenshots

https://youtu.be/SYT9LsfWSPw
https://youtu.be/0cVamrJJd4s

### MacOS Version

Sonoma 14.2.1 (23C71)

### Loop Version

Loop 1.0.0-beta.1

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thank you so much!
This should have been fixed in #149, so I'd recommend testing that build :)
