### ISSUE TITLE
✨ Multi Monitor

### ISSUE THREAD

**Issue by jberard415** [MrKai77/Loop#158]
Firstly, I must say that I really appreciate this software for its design and ease of use, among other things. However, I would like to point out an issue I’ve encountered. When I use Loop on my Mac, which is connected to a second display, the window snapping feature doesn’t seem to function properly on the second display. It appears as though the window will snap into a certain position, but then it unexpectedly jumps up to my main display.

**Comment by MrKai77** [comment]
that's weird... can you try the build posted in #149? I also fixed some external display issues there.

**Comment by jberard415** [comment]
It worked with the build posted in #149 !

**Comment by MrKai77** [comment]
Awesome! That means that the bug fix has already been implemented for the next release, so I'll be closing this issue!
