### ISSUE TITLE
✨ Disable arrow key bindings, for a mouse-only interactions, but leave on the trigger keybinding.

### ISSUE THREAD

**Issue by soundslikeinfo** [MrKai77/Loop#159]
### Feature Request Description

I would like to use loop just with its trigger keybinding and the mouse. I use loops trigger key (right control key) and arrows for switching deskspaces, so I'd like to disable the arrows' binding with loops, and just use mouse gestures. Is there a way for us to keep the trigger keybinding, and remove the arrow group's bindings. 
Kind of like entering a mouse-only/non-keyboard mode for the loop application.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by soundslikeinfo** [comment]
I know about the trigger key delay, but it still gets in the way, let's say when I'm triggering the loop while switching across 4 desk spaces, which I would still be holding onto the trigger for longer than 3-4 seconds.

**Comment by MrKai77** [comment]
Yup, it's already totally possible to have a mouse-only mode! You can right-click existing keybinds to remove them.

As for the arrow keys, you can click on the keybind to reassign a new one. I also use <kbd>Control</kbd> as my trigger key and the arrow keys to switch between spaces, so I've reassigned the default shortcuts to the <kbd>W</kbd>,  <kbd>A</kbd>,  <kbd>S</kbd> and  <kbd>D</kbd> keys :)

**Comment by soundslikeinfo** [comment]
That works out great. Thanks!
