### ISSUE TITLE
✨ Add option for having gaps/padding

### ISSUE THREAD

**Issue by mobabur94** [MrKai77/Loop#16]
### Feature Request Description

Would be nice to be able to specify a padding to have around the window after moving it for aesthetics.

**Comment by MrKai77** [comment]
This is something I've been thinking of adding too :)  
Will definitely start looking into this!

**Comment by MrKai77** [comment]
Alright, so I've tried implementing this. You can find the padding settings inside the "More" section of the settings window. Is this how you envisoned it would work? I'd love some feedback!

[Loop.zip](https://github.com/MrKai77/Loop/files/12491661/Loop.zip)

**Comment by MrKai77** [comment]
Alright, so based on my daily testing, this seemed to be pretty stable, so I have merged it into the `develop` branch. The settings have been relocated into the "General" tab in the settings window. Should you ever notice any more bugs regarding this, please feel free to open another issue!

**Comment by mobabur94** [comment]
perfect! thank you :)
