### ISSUE TITLE
🐛 Some percentages don't work on dual monitors.

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#163]
### Bug Description

When using a specific keybind that cycles between all 6ths of a display, trying to use the shortcut on a top display does not yield the same result as using a bottom display.

### Steps To Reproduce

1. Import my config.
2. Change the "6ths" keyboard shortcut to your preference.
3. Test out all six states on a "bottom" display and observe that it works.
4. Move your mouse to a "top" display (do not click anything with the mouse).
5. Activate your "6ths" keyboard shortcut.
6. Watch as some areas do not snap.

### Expected Behavior

The windows snap to their appropriate corners on both displays, regardless of preview status.

### Actual Behavior

When preview is enabled, windows become glitchy and stick to the bottom display. When preview is disabled, windows snap to odd positions on the top display.

## Display layout
![002740@2x](https://github.com/MrKai77/Loop/assets/60551230/4059c0a0-2843-4550-8816-d640ff95dd0e)

## Video – Preview On
https://github.com/MrKai77/Loop/assets/60551230/c88a6837-42d0-458a-b92f-d8c382e057b8

## Video – Preview Off/On

Uploading 2024-01-13 00-44-45.mp4…

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (620)

### Additional Context

[Loop Keybinds – Bug Report.json](https://github.com/MrKai77/Loop/files/13925011/Loop.Keybinds.Bug.Report.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Ohhh that's really odd
This seems to have been working in the pre-multi-monitor builds, so it must be a bug in that was introduced in #162.
I'll look into this!

**Comment by MrKai77** [comment]
Haha looks like it was a single-line fix!

Here's a fixed build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13925150/Loop.zip)

**Comment by JaceThings** [comment]
... holy... it's fixed... perfect

it took longer to write the ticket than you fixing it 😭
