### ISSUE TITLE
💄 Reduce Useless Cycle Creation Click

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#164]
### Feature Request Description

When a user creates a cycle, I think it would be nice to automatically open the cycle menu because why would I leave it empty?

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/e855d598-ca5c-498d-80a9-21f3824c2070

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
That's a really good point haha
I'll also do this with custom window sizes too!
