### ISSUE TITLE
🐞 Loop Just Sometimes Doesn't Respond

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#166]
### Bug Description

Sometimes, Loop quite literally stops reading my inputs. To solve this issue, you can either wait and do nothing for a few minutes or restart the loop once or twice.

### Steps To Reproduce

After encountering this about 6 times since the last update, I still can't reliably reproduce it. However, I have seen some users on Reddit express this issue.

### Expected Behavior

Loop always reads inputs.

### Actual Behavior

Sometimes, Loop quite literally stops reading my inputs.

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Yep, I saw the reports on Reddit as well, and I think it's caused by [`CGEventMonitor`](https://github.com/MrKai77/Loop/blob/1f12045581d9492e48b25e131e7d24fd3c40b621/Loop/Utilities/EventMonitor.swift#L81), but I don't know where exactly it goes wrong, so this might take a while to fix :(

**Comment by JaceThings** [comment]
No problem! Just wanted to report it as I was maybe expecting it to be an accident and fixed in the new update. Still isn't, but glad to see there's a potential reason.

**Comment by JaceThings** [comment]
This issue is still happening, although I might have something reproducible in some cases. I will update later, but until now, I've needed to have a Raycast extension made that quits the loop, opens it, and closes the window as a solution.

![006034@2x](https://github.com/MrKai77/Loop/assets/60551230/a5b61c24-8775-4f26-83d9-ebfb21401296)

**Comment by SenpaiHunters** [comment]
Seems to be fixed, if anyone else has an issue like this, feel free to make a post!
