### ISSUE TITLE
🐛 100% width is applied before movement on multi-displays.

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#167]
### Bug Description

When moving some apps across multiple displays using the "top" array of actions, the 100% width seems to be applied before movement. As a result, when arriving on the second monitor, the window does not fill the width, but instead seems to match the width of the second monitor.

### Steps To Reproduce

1. Use the attached configuration.
2. Use the "Top Cycle" keyboard shortcut.
3. Transition window from a small display to a larger one.
4. Watch as the window

### Expected Behavior

The window accurately takes up the full width of the display regardless of where it came from.

### Actual Behavior

The window does not take up the full width of the arrival display regardless of where it came from.

## Setup
![002764@2x](https://github.com/MrKai77/Loop/assets/60551230/4164065e-25ab-463d-bd39-70aead254f92)

## Video
https://github.com/MrKai77/Loop/assets/60551230/2863afdd-2698-4215-9991-cf598c1f0a4d

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[100% width is applied before.json](https://github.com/MrKai77/Loop/files/13925319/100.width.is.applied.before.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
ohhh ok I'll look into this!

**Comment by MrKai77** [comment]
Alright, here's a build that should fix this as well as #169!
[Loop.zip](https://github.com/MrKai77/Loop/files/13930388/Loop.zip)
