### ISSUE TITLE
🐛 Loop can tell the difference between fast and slow key presses.

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#168]
### Bug Description

It seems as though Loop can tell the difference between a quick tap and a longer press of a key. When tapping the keyboard shortcut quickly, the "full" action does not occur. Watch the video and see that when the shortcut is tapped, the window does not fully expand to the full screen size as it should.

When clicking the button for slightly longer, the correct actions occur.

### Steps To Reproduce

1. Please use the attached configuration.
2. Move your mouse to the second display.
3. Use the "Maximize" shortcut (any), but quickly tap the key as fast as you can to activate it on the secondary display.
4. Observe that the window does not fully expand on the second display.

5. Move the window back to the smaller monitor.
6. Move your mouse to the second display.
7. Use the "Maximize" shortcut (any), but hold the key down to activate it on the secondary display.
8. Observe that the window fully expands on the second display.

### Expected Behavior

The window expands on the second display regardless of how fast you press a key.

### Actual Behavior

The window expands on the second display depending on how fast you press a key.

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/9b603040-5d83-4ed0-ba4c-b6995c8b2ba8

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[Config.json](https://github.com/MrKai77/Loop/files/13926047/Config.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
For me, no matter how quick I press the key, it doesn't fully expand. Interesting to see that it sometimes works and sometimes doesn't on your side!

edit: I take that back. This seems to only be an issue with certain applications for some reason 🤔

**Comment by MrKai77** [comment]
Alright, here's a fixed build, which also contains the changes from #167/#169!
[Loop.zip](https://github.com/MrKai77/Loop/files/13930419/Loop.zip)
