### ISSUE TITLE
🐛 Mirrored commands don't appear to be mirrored.

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#169]
### Bug Description

I have two mirrored actions: one moves windows to the left, and the other moves windows to the right.

When using the action that moves windows to the right across screens, everything seems to work fine. However, when arriving on the second display, the window takes up 50% of the left side.

On the other hand, when using the action that moves windows to the left across screens, the window appears in the wrong size when arriving on the second screen, even though the actions are mirrored 1:1 from the right version.

### Steps To Reproduce

1. Use my configuration.
2. Start on a small display.
3. Try using the `⌘ ⌥ ⌃ ⇧ A` shortcut, which moves windows to the left.
4. Repeat the shortcut until the window moves across screens.
5. Observe that the window arrives in an incorrect size.
6. Repeat steps 2-4 using the `⌘ ⌥ ⌃ ⇧ D` shortcut.
7. Observe that the window arrives in a correct size.

### Expected Behavior

When using the shortcuts `⌘ ⌥ ⌃ ⇧ A` and `⌘ ⌥ ⌃ ⇧ D` to move windows to the left and right across screens, respectively, the expected behavior is that the windows should move seamlessly from one screen to the other, maintaining their size and positioning. 

The windows should ideally take up an equivalent proportion of the screen space on the second display as they are described to be.

### Actual Behavior

When using the action that moves windows to the left across screens, the window appears in the wrong size when arriving on the second screen,

## Actions
![002782](https://github.com/MrKai77/Loop/assets/60551230/cfea4727-06cd-4ccf-828d-10e2d2561674)
![002781](https://github.com/MrKai77/Loop/assets/60551230/de9e4a46-e341-495a-b75b-61ff1a472c30)

## Video

https://github.com/MrKai77/Loop/assets/60551230/4fc2086f-0962-4afc-8e03-4e2f793a4c67

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[keybinds.json](https://github.com/MrKai77/Loop/files/13928602/keybinds.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Looks like my multi-monitor implementation wasn't that stable :P
Anyways, I think this may be related to #167, but I'll have to see later.
Unfortunately, I'm busy for most of the day today, so I probably won't be able to get much done 😕

**Comment by JaceThings** [comment]
🫡

**Comment by JaceThings** [comment]
This has been fixed in https://github.com/MrKai77/Loop/issues/168#issuecomment-1890854138
