### ISSUE TITLE
🐛 Respect fixed dock size

### ISSUE THREAD

**Issue by mobabur94** [MrKai77/Loop#17]
### Bug Description

When the dock is set to not automatically hide, moving/maximizing/centering windows does not take into account the dock size/position.

### Steps To Reproduce

1. Set dock to not auto hide
2. Move / maximize / center a window

### Expected Behavior

Expecting the window to take the dock's size/position into account when moving / maximizing / centering a window.

### Actual Behavior

The dock's size/position is not taken into account.

### MacOS Version

Ventura 13.5.1

### Loop version

Version 1.0.0-beta.7 (256)

**Comment by MrKai77** [comment]
Great catch! Will try and fix this today!

**Comment by MrKai77** [comment]
Thank you so much for reporting this bug!
Here's a build with the latest changes: [Loop.zip](https://github.com/MrKai77/Loop/files/12491085/Loop.zip)

**Comment by mobabur94** [comment]
thanks babe
