### ISSUE TITLE
🐛 Shift + Key Trigger activates Loop

### ISSUE THREAD

**Issue by patelheet30** [MrKai77/Loop#170]
### Bug Description

I use Left Command as my trigger key. Screenshots.app uses Left Command + Shift + 4/5 to start. I also have Double Click Trigger Key enabled. When I do Left Command + Shift it activates Loop, which I don't think is the expected behaviour. 

I think this might also be a MacOS issue since changing the shortcut to Left Command + Shift + 4/5 changes it to Shift + Left Command + 4/5. Then obviously when I do Left Command + Shift + 4/5 it activates Screenshots but it also activates Loop. It lets me take the screenshot first but then immediately starts changing the location of the window unless I press escape which just adds to the whole shortcuts process.

I understand there have been a few issues that were similar and were fixed, but I downloaded the latest version and it still has the same issue.

### Steps To Reproduce

1. Set trigger key to Left Command.
2. Activate Double Click Trigger Key
3. Set Screenshots to Left Command + Shift + 4/5
4. Take a screenshot :)

### Expected Behavior

Should just take a screenshot without activating Loop.

### Actual Behavior

Takes a screenshot but activates Loop.

### Screenshots

https://github.com/MrKai77/Loop/assets/75808215/b04f089f-2ea6-473f-ba76-94dc54c638cc

### MacOS Version

Sonoma 14.3 Beta (23D5033f)

### Loop Version

Version 1.0.0-beta.12 (562)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by patelheet30** [comment]
I've updated to `Version 1.0.0-beta.13 (595)` and still facing the same issue

**Comment by MrKai77** [comment]
Interesting, I never thought of using Loop like this!
While this does look like a MacOS issue, I think I might be able to figure out a way around it :)
I'll look into this after I finish with #162 :)

**Comment by JaceThings** [comment]
Hey thats me in the video :D (red name)

**Comment by patelheet30** [comment]
> Interesting, I never thought of using Loop like this! While this does look like a MacOS issue, I think I might be able to figure out a way around it :) I'll look into this after I finish with #162 :)

I have very very weird ways of using apps and shortcuts and finding weird glitches. I've realised its not just an issue with screenshots but with any shortcut that uses Left Command + Shift.

**Comment by patelheet30** [comment]
> Hey thats me in the video :D (red name)

Go away Jace 🙄

**Comment by MrKai77** [comment]
> Hey thats me in the video :D (red name)

Arc discord server... I'm in there too!

Anyways, I'll start working on this now!

**Comment by MrKai77** [comment]
Alright, I made Loop prioritize system keybinds if the currently pressed keys aren't already a valid Loop keybind, let me know how this is :)
[Loop.zip](https://github.com/MrKai77/Loop/files/13933483/Loop.zip)

**Comment by patelheet30** [comment]
That fixed the issue 👍. Thanks for the help
