### ISSUE TITLE
✨ Support for MX Master 3S

### ISSUE THREAD

**Issue by kacper-serewis** [MrKai77/Loop#178]
### Feature Request Description

I'm want to use the following custom gestures in LogiOptions+

Hold + Move Left: Cycle Left
Hold + Move Right: Cycle Right 

And so on, my previous window manager handled it correctly. But Loop does nothing when I do the gesture.

### Screenshots

![Logi Options+ gesture overview](https://github.com/MrKai77/Loop/assets/16763276/61f4d32f-0cfa-4464-8322-a243f6d8cffd)
![Loop keybinds](https://github.com/MrKai77/Loop/assets/16763276/c3e68cf3-998a-4d86-91df-988a6887e742)

### Additional Context

I think it's because the Logitech gesture performs way too fast.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Hmm I think this could also maybe be because LogiOptions+ might use right control/right option instead of their left alternatives? Would you be able to try and re-record the trigger key from the mouse's buttons instead of the keyboard and see if that works?

**Comment by MrKai77** [comment]
@K4CZP3R Any updates on this? I believe my previous comment should address this.

**Comment by kacper-serewis** [comment]
I will test it today and let you know!

**Comment by MrKai77** [comment]
Alright, I got access to a Logitech mouse and tried my solution out. Unfortunately, it didn't work. I tried everything I could do to try and fix this, but to no ado. My solution was to use Karabiner Elements to remap the mouse buttons into the correct keys. I'd highly recommend you do this too, as it's an excellent app and will get your mouse working with Loop :)
