### ISSUE TITLE
🐛 Multi-monitor does not seem to work

### ISSUE THREAD

**Issue by kacper-serewis** [MrKai77/Loop#179]
### Bug Description

When performing multiple `Cycle *` keybinds, my application window stays on the current monitor.

### Steps To Reproduce

1. Open app
2. Try to move it from monitor 1 to monitor 2 using `Cycle Left` or `Cycle Right`

### Expected Behavior

App window moves to 2nd monitor

### Actual Behavior

App window stays on 1st monitor no matter what

### MacOS Version

Sonoma 14.1.1

### Loop Version

1.0.0-beta.13 (595)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by JaceThings** [comment]
Could you attach your cycle? In order for a window to move, the cycle must contain a "move" action to display.

Also use this version Version 1.0.0-beta.13 (625):
https://github.com/MrKai77/Loop/issues/170#issuecomment-1891114800

![003063@2x](https://github.com/MrKai77/Loop/assets/60551230/2941080e-b717-466c-8bb1-573c758708cd)

**Comment by jacksongoode** [comment]
Is this still an issue? I'm not sure if this issue needs to be more narrow?

**Comment by MrKai77** [comment]
Yeah I think this can be closed. `1.0.0-beta.13 (595)` didn't have multi-monitor support, whereas `1.0.0-beta.13 (625)` does. But if this issue does persist, feel free to reopen this issue @K4CZP3R :)
