### ISSUE TITLE
🐛 False snap recognition on multiple screens

### ISSUE THREAD

**Issue by baschte** [MrKai77/Loop#180]
### Bug Description

I have several displays in use and Loop works wonderfully and as expected on my main display. However, if I drag my window to my empty second screen, the snap feature no longer works as desired and I can no longer bring the window to full screen when dragging it to the top edge. I have to use the hotkey to do this.

Here you have an example how it looks on my second screen.
![Ohne Titel](https://github.com/MrKai77/Loop/assets/9203613/8cb47594-d5cf-42d2-aa82-eded886f7c87)

Tried to set animations off but it doesn't seems to work.

### Steps To Reproduce

1. Connect two Displays
2. Try to snap a window fullscreen on the second display

### Expected Behavior

Window should get fullscreen if i snap it to the centered top edge of the screen.

### Actual Behavior

Only the half screen is used. Snap feature doesnt recognizes the screen correct.

### MacOS Version

14.2.1

### Loop Version

Version 1.0.0-beta.13 (595)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Hmm I'm unable to reproduce this on my side. Maybe I could have already made a change on the develop branch that could have addressed this. 
Would you mind trying this latest build?
[Loop.zip](https://github.com/MrKai77/Loop/files/14003034/Loop.zip)

**Comment by baschte** [comment]
@MrKai77 
i've tested this version and the problem still exists.
Here is a screenshot of my display settings

![Bildschirmfoto 2024-01-22 um 08 43 43](https://github.com/MrKai77/Loop/assets/9203613/dadcf4ab-5c0f-4182-b649-00cbb22babab)

if i align the screens the problem exists as well.

**Comment by MrKai77** [comment]
Alright, I tried the same layout on my own setup and could not reproduce this bug.
Unfortunately, I can't fix something if I can't figure out what causes it, so this might take a while to fix. Sorry about that :(

**Comment by MaximilianZenz** [comment]
I have the same issue with a more classic screen layout.
![image](https://github.com/MrKai77/Loop/assets/48351547/25f6bdc5-f715-4e9c-9a14-030704a783d6)

**Comment by MrKai77** [comment]
Alright, I'm getting the sense that this might be a pretty bad bug so I'm going to try my best and investigate it again today.

**Comment by baschte** [comment]
@MrKai77 
My setup is a m3 16 Inch MacBook Pro with an Apple Studio Display. Dont know if it helps.

**Comment by MrKai77** [comment]
I think I was able to fix it! Let me know!
Build: [Loop.zip](https://github.com/MrKai77/Loop/files/14043468/Loop.zip)

**Comment by baschte** [comment]
@MrKai77 @MaximilianZenz 
That version works like a charm for my setup. Thank you 👍
