### ISSUE TITLE
✨ Hide radial menu

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#183]
### Feature Request Description

I don't know if this is too much to ask for, since it's kind of Loop's branding, but I never use the mouse or the actual Radial menu itself.

I'm putting these two requests together as I think they complement each other. If the mouse + trigger key is disabled, the radial menu is just an aesthetic thing for keyboard users.

Obviously, disabling them independently would be nice, but to reduce scope, it could be one ticket.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yeahh I saw this coming sooner or later...

> I'm putting these two requests together as I think they complement each other.

I only see one request here, which is to be able to disable the radial menu. Would you be able to elaborate on that?

**Comment by JaceThings** [comment]
1. Disable the radial menu (only the menu).
2. Disable holding down a key and moving your mouse to place and have the window go there.

You can't have the mouse drag without the radial menu, but if you get rid of both, the menu becomes useless.

**Comment by MrKai77** [comment]
Got it, thanks!

So your second point is to basically disable mouse interaction?
I feel like that's a little unintuitive, since radial menus are primarily based around mouse input. I think that having one option to disable the radial menu, like the option to disable the preview window would be more simple from the user's perspective.

But I'm still debating on whether I should do this, as the radial menu is what Loop is all about (although I also mostly use keyboard shortcuts as well). I'm thinking that being able to add a delay to the radial menu might be more ideal? Like the delay to the trigger key, but specifically for the radial menu. This would essentially address this issue, as well. Let me know what you think :)

Also, thank you so much for always reporting so many issues!

**Comment by JaceThings** [comment]
> So your second point is to basically disable mouse interaction?

Yes! I personally have activated it by accident like 2 times so far (I know it's small, but just funny) and I don't even know how.

> I feel like that's a little unintuitive, since radial menus are primarily based around mouse input.

Yeah, I agree. That's why, as I said before, it doesn't make sense to hide the radial menu if you're using a mouse. But if you've disabled the feature, the radial menu is pointless. As you mentioned, radial menus are more suitable for mouse actions.

> I think that having one option to disable the radial menu, like the option to disable the preview window would be more simple from the user's perspective

Yeah, no problem. These were just ideas after all. I like Loop's menu, but hey, if I can get an option to remove it, I'm gonna ask :)

> I'm thinking that being able to add a delay to the radial menu might be more ideal?

That's an interesting one. My first thought would be, "If I set the delay to, like, 4 seconds, does that mean if I complete my action in less than 4 seconds via the keyboard, the menu won't show up?" If so, I'm so down!

> This would essentially address this issue, as well. Let me know what you think :)

If it works as I explained, it does! Minus the accidental mouse activation, but that only happens when I'm cross-armed for some fucked-up reason 😭

> Also, thank you so much for always reporting so many issues!

I love Loop. I want it to be the best. I'd love to help in any way I can! I'm also a designer, so if you ever need any non-"default Apple settings" looking settings, hmu ;)

**Comment by MrKai77** [comment]
Awesome!

> That's an interesting one. My first thought would be, "If I set the delay to, like, 4 seconds, does that mean if I complete my action in less than 4 seconds via the keyboard, the menu won't show up?" If so, I'm so down!

Yup, that's exactly what I meant! I'll go ahead and put this on the to-do list!

> Minus the accidental mouse activation, but that only happens when I'm cross-armed for some fucked-up reason 😭

How do you activate Loop by accident from the mouse haha... If it's middle click you can disable that in the settings 😉 Or is it something else?

> I love Loop. I want it to be the best. I'd love to help in any way I can! I'm also a designer, so if you ever need any non-"default Apple settings" looking settings, hmu ;)

I really appreciate it :) Also, what do you mean by 'non-"default Apple settings"'? I personally think the current settings window is starting to clutter, so I'm down to explore other designs!

**Comment by JaceThings** [comment]
> How do you activate Loop by accident from the mouse haha... If it's middle click you can disable that in the settings 😉 Or is it something else?

Trackpad! I'm pretty sure when it happens, it occurs when I need to press my Super key (right ⌘) and some other weird key that I can only access with my left hand. Somehow, my palm ends up pressing down on the trackpad. I'll be sure to check out my hand positions when it happens next time 😭

> Also, what do you mean by 'non-"default Apple settings"'?

Some settings panels that are more styled, like not "Apple-looking settings," just as Safari (image 1), AirBuddy, Cleanshot (image 3), and many other apps do. They all look the same! Apple Grey, with tabs on the top and checkboxes and switches.

Image 1
![003404@2x](https://github.com/MrKai77/Loop/assets/60551230/bbde500d-8a64-4ef1-92de-02dac7edf086)
 
Image 2
![003405@2x](https://github.com/MrKai77/Loop/assets/60551230/4d431ad5-72e5-4fee-a638-bbec5ebd6c85)

Image 3
![003406@2x](https://github.com/MrKai77/Loop/assets/60551230/a7c72710-de48-4e6d-b7c7-879a0854c7b1)

What I'm proposing is a custom UI like Telegram (Image 4) or Raycast (Image 5), or especially like Craft (Image 6), since Loop has custom icons.

Image 4
![003407@2x](https://github.com/MrKai77/Loop/assets/60551230/f7b385df-4262-43de-b7ac-09cae8a7ee06)

Image 5
![003408@2x](https://github.com/MrKai77/Loop/assets/60551230/20be4305-60a9-4265-9c1c-ba8737699958)

Image 6
![003410@2x](https://github.com/MrKai77/Loop/assets/60551230/3b14778e-a4fd-4403-a1ae-576835120aaa)

**Comment by MrKai77** [comment]
> Trackpad! I'm pretty sure when it happens, it occurs when I need to press my Super key (right ⌘) and some other weird key that I can only access with my left hand. Somehow, my palm ends up pressing down on the trackpad. I'll be sure to check out my hand positions when it happens next time 😭

Got it haha!

> What I'm proposing is a custom UI like Telegram (Image 4) or Raycast (Image 5), or especially like Craft (Image 6), since Loop has custom icons.

I really like the Raycast or Craft ones! But with how complicated Loop is becoming, I think something like Craft (aka having a sidebar) would be more suitable in the long-term. But I also want Loop to follow Apple's HIG at least a little, so I'm thinking of something along the lines of a combination of Apple's System Settings sidebar and Craft's settings?
And I'm just throwing ideas out here, but maybe the background of the settings window could be translucent kind of like Raycast? This is something I did do in the first few versions of Loop, but ended up taking out because it looked pretty bad in light mode (which I don't use). But I think this could be possible with a blur gradient like Raycast.

EDIT: I was looking through Loop's graphics folder and found this old screenshot 😂
This is how Loop's settings looked with the background blur!
https://github.com/MrKai77/Loop/blob/develop/assets/graphics/radial_menu.png

**Comment by MrKai77** [comment]
Let me know how this is! You can find the setting under the radial menu section of the settings window.
[Loop.zip](https://github.com/MrKai77/Loop/files/14091791/Loop.zip)

**Comment by JaceThings** [comment]
My keybind is now not accepted. 💀

Left ⌘ works, this doesnt

![003996](https://github.com/MrKai77/Loop/assets/60551230/778b329e-07bc-4f3d-963b-5b0f2b20c5ec)

**Comment by MrKai77** [comment]
How did I not notice that 😭
Will fix that right now!

**Comment by MrKai77** [comment]
Fixed!
[Loop.zip](https://github.com/MrKai77/Loop/files/14091891/Loop.zip)

**Comment by JaceThings** [comment]
Love it! It works!

I find it funny how it's maxed at one second (random number), but it works for my use case!

**Comment by SenpaiHunters** [comment]
Hey, @MrKai77 and @Soft-Bred, you can actually add more than one second. The up and down buttons are capped at one second, but if you enter a number and then click off, it will be set to that value.
![Loop - January 01 2024 - 12 06 PM@2x](https://github.com/MrKai77/Loop/assets/103985728/534daa0d-c515-4a02-9c02-d6a3193ac59c)

**Comment by JaceThings** [comment]
Oh, nice! Very cool. I will definitely use more than one second <3

**Comment by MrKai77** [comment]
Perfect!

> I find it funny how it's maxed at one second (random number), but it works for my use case!

Good point! as @SenpaiHunters pointed out, you can manually go higher, but I think I should also be able to remove the closed range (which is currently set from 0 to 1), so I'll look into that!

**Comment by MrKai77** [comment]
Alright, here's an update:
Removing the closed range on the `Stepper` seems to remove the textbox with the current value, which also makes it impossible to type in your own values. To solve this, I tried adding my own textbox inside it but then all the alignment was VERY off, and I couldn't fix it (it looked pretty terrible haha). So, I decided to increase the max value to 10, which should be more than enough :)

**Comment by MrKai77** [comment]
From #274:

> This seems to be a popular request, I think I will just add a toggle button haha (plus who wants a delay on the radial menu itself anyway??)

**Comment by MrKai77** [comment]
New build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14794162/Loop.zip)
<img width="480" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/776174e4-1231-4ae4-9841-6697d7437bad">

**Comment by JaceThings** [comment]
lol 
![006985](https://github.com/MrKai77/Loop/assets/60551230/0d4c6876-6ad3-4f9f-85f0-dac6146819ac)

**Comment by MrKai77** [comment]
wow what happened there??
that doesn't seem to be related to this issue though... probably is to #268 (maybe?)

**Comment by JaceThings** [comment]
Nope, hasn't happened on the last few builds, at least this is the first time I've seen it do this triangle thing when testing

**Comment by MrKai77** [comment]
Ohhh I see
It happens when the corner radius is set to the minimum and the thickness it set to the maximum
<img width="426" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/c5300aa1-e2d0-4237-8607-cd8fb57a6b34">
Not caused by this issue but will fix it haha

**Comment by JaceThings** [comment]
oh yeah I thought that was obvious lol, I always try to max out values 😅
