### ISSUE TITLE
💄 Better Update Notifications

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#186]
### Feature Request Description

The current update model looks a bit bland as it's just an embed of what I assume to be GitHub. This isn't an important ticket at all, but I thought I would just created for the future. I would probably take inspiration from something like Arc for update menus.

### Screenshots

![003521@2x](https://github.com/MrKai77/Loop/assets/60551230/d38a4b08-2993-4eae-9444-a00f4cb7b9b8)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup, I like this idea! The Arc one feels much more playful :)

**Comment by SenpaiHunters** [comment]
This is done, @MrKai77 as you know, so we can close this issue, or @Soft-Bred , in reference to PR #403
