### ISSUE TITLE
🐛 "Double-click trigger key to trigger Loop" recognized incorrectly

### ISSUE THREAD

**Issue by MaximilianZenz** [MrKai77/Loop#187]
### Bug Description

I currently use loop with doup press left cmd but it also trigger when I for example press cmd+option or cmd+shift or cmd+ctrl which is really annoying because for example the screenshot shortcut uses cmd bus crtl/shift.

### Steps To Reproduce

- bind loop to trigger with double pressing cmd or any other of the described keys
- hold the trigger key and press the another key (cmd/option/control/shift) shortly after
- loop will trigger even if it shouldn't trigger

### Expected Behavior

that loop doesn't trigger when i hold the trigger key and press any other of cmd,option,ctrl or shift

### Actual Behavior

loop triggers when holding the trigger key and pressing any other of the ones described

### MacOS Version

Sonoma 14.2.1

### Loop Version

1.0.0.beta.14

### Additional Context

This already happened with older Loop Versions

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
I can reproduce this as well. I'll try and fix this ASAP since it's a really annoying bug!

**Comment by MrKai77** [comment]
Fixed!
Here's the build: [Loop.zip](https://github.com/MrKai77/Loop/files/14043056/Loop.zip)
Let me know if there's any other issues!

**Comment by MaximilianZenz** [comment]
Looks like it fixed the Bug. Nice work. Thank you 🙂
