### ISSUE TITLE
✨ iCloud Sync for Loop Stats & Settings

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#191]
### Feature Request Description

It would be cool if our Loop statistics and settings were able to be synced via iCloud.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
This requires an Apple Developer Program account, so this is impossible at the moment. However, I can look into this in the future as I plan to purchase one!

**Comment by falzm** [comment]
@MrKai77 in absence of a native way to sync settings via iCloud, can you indicate how to proceed manually? I've copied the `$HOME/Library/Preferences/com.MrKai77.Loop.plist` file from one computer to another, however this doesn't seem to be effective 🤔

**Comment by MrKai77** [comment]
@falzm copying that plist file should be the best way of doing it at the moment.
