### ISSUE TITLE
🐛 Settings window opens itself "randomly"

### ISSUE THREAD

**Issue by hoelderlin** [MrKai77/Loop#197]
### Bug Description

Sometimes, when using mac OS or any app, the configuration window of the app opens itself randomly.

### Steps To Reproduce

I can replicate it by: 1. go to "About this mac" in the apple logo icon in the menu bar and 2. close it with the Command+W keyboard shortcut

### Expected Behavior

It should just close the window of the app I'm using

### Actual Behavior

It closes the app window I'm using but at the same time it opens the settings menu.

### MacOS Version

Sonoma 14.3

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
I am unable to reproduce this bug on my computer :(
Would you be able to send a screen recording after having had quitted and relaunched Loop?

**Comment by hoelderlin** [comment]
Hi here's a video. The quality is low but I think you'll get it. This also happens when quit apps.
After restaring the app the issue is gone. But this is the second time it happened to me.


https://github.com/MrKai77/Loop/assets/79167071/25d36bbd-23f4-41cf-99e3-d5ee3c12d8ea

**Comment by MrKai77** [comment]
Thanks!
That's really weird behavior!
Loop currently only opens the settings window if it becomes the active app. I suspect that this is happening because Loop is becoming the "last active app" when all other windows are closed? 
I'll have to dig deeper and try and find the root cause though.

**Comment by hoelderlin** [comment]
I have these custom key-bindings. Not sure if it might be casuing this.

<img width="448" alt="keyb" src="https://github.com/MrKai77/Loop/assets/79167071/42f1f9e7-1cc1-4b3b-bfc2-8b68391a2ac3">

**Comment by tlgnkl** [comment]
the same problem :(

**Comment by just-doit** [comment]
May be implementing `applicationShouldHandleReopen` in the app delegate like this would work:

```swift
    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
        self.openSettings()
        return false
    }
```

Instead of 
```swift
    func applicationWillBecomeActive(_ notification: Notification) {
        guard canOpenSettings else { return }
        self.openSettings()
    }
```

You may want to change `applicationDidFinishLaunching` like this, to open settings when the app is launched but not as login item:
```swift
        if !self.launchedAsLoginItem {
            self.openSettings()
        }
```

**Comment by MrKai77** [comment]
@just-doit Great point! I've never used `applicationShouldHandleReopen` before but it might fix the problem!

Does this build with the above changes fix this issue? (I can't test it since I could never reproduce the bug)
[Loop.zip](https://github.com/MrKai77/Loop/files/14625255/Loop.zip)

**Comment by yougotwill** [comment]
I have this bug every time I start up. Using the test build now and will report back.

**Comment by yougotwill** [comment]
So far so good!
