### ISSUE TITLE
✨ Customizable Radial Menu

### ISSUE THREAD

**Issue by NHUJI** [MrKai77/Loop#198]
### Feature Request Description

Is it possible to add a feature that allows for a customizable Radial Menu? For example, setting it to maximize the window when swiping up, and to hide when swiping down, etc.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup! This is what is planned in #107 :)
