### ISSUE TITLE
🐛 Ventura 14.4 Beta Breaks Loop

### ISSUE THREAD

**Issue by pmvrsi** [MrKai77/Loop#200]
### Bug Description

When utilising the beta Windows Animate feature, it encounters issues on macOS Ventura 14.4 Developer Beta. Specifically, it prompts for screen recording permission every time.

<img width="286" alt="Screenshot 2024-02-02 at 2 41 41 pm" src="https://github.com/MrKai77/Loop/assets/121735202/292d09ee-e4b5-4872-b315-3f7a928fedd6">

### Steps To Reproduce

Be on macOS Ventura 14.4

### Expected Behavior

Windows moves with no issues. 

### Actual Behavior

Notifies the user about screen recording every time windows is moved.

### MacOS Version

Ventura 14.4 Developer Beta

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Oh.. This seems like a really bad problem :( 
Just making sure that it only happens when window animations are on? If so, for now, I'd recommend turning them off (if you haven't already).
Otherwise, I'll look into how to fix this! Hopefully that doesn't involve removing window animations :(

**Comment by MrKai77** [comment]
Found some other reports with the same issue. Hopefully Apple reverts this change in the next beta release 🙏
- https://www.reddit.com/r/MacOSBeta/comments/1aepo6a/141_does_this_now_every_time_you_relaunch/
- https://www.reddit.com/r/MacOSBeta/comments/1ah2gju/screen_capture_pop_up/

But for now, I'll have to look into alternate ways around this issue 😕

**Comment by pmvrsi** [comment]
> Oh.. This seems like a really bad problem :( Just making sure that it only happens when window animations are on? If so, for now, I'd recommend turning them off (if you haven't already). Otherwise, I'll look into how to fix this! Hopefully that doesn't involve removing window animations :(

Yeah I turned of animations because the pop ups :(

**Comment by MrKai77** [comment]
I just updated to `macOS 14.4 (23E214)` and I don't seem to be getting this alert, so it looks like this is no longer an issue. Would you be able to confirm?

**Comment by MrKai77** [comment]
Closing as this seems to be working fine :)
