### ISSUE TITLE
✨ Option to not make the window Looped the active window.

### ISSUE THREAD

**Issue by y-u-s-u-f** [MrKai77/Loop#201]
### Feature Request Description

If we loop a window that isn't the active window, add a setting to not make it the active one.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Got it! This will be fairly easy, so will definitely be in the next release!

**Comment by MrKai77** [comment]
Here's a build with those changes :D
[Loop.zip](https://github.com/MrKai77/Loop/files/14155626/Loop.zip)
