### ISSUE TITLE
✨ Display times looped in about section

### ISSUE THREAD

**Issue by y-u-s-u-f** [MrKai77/Loop#206]
### Feature Request Description

Display the times looped in the menubar icon

### Screenshots

![Screenshot 2024-02-06 at 07 21 44 AM@2x](https://github.com/MrKai77/Loop/assets/67281394/855df9e3-9d2d-443a-905a-c8a9860bda4b)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Great idea! Will definitely do this!

**Comment by y-u-s-u-f** [comment]
@MrKai77 Any update on this?

**Comment by MrKai77** [comment]
I will look into this after the settings window redesign 😉
