### ISSUE TITLE
🐛 Window snapping activates Mission Control

### ISSUE THREAD

**Issue by iamliushuyuan** [MrKai77/Loop#212]
### Bug Description

when dragging a window to the top edge of the screen the mission control will be activated.

### Steps To Reproduce

drag a window to the top edge of the screen

### Expected Behavior

mission control shouldn't show up

### Actual Behavior

mission control shows up

### MacOS Version

sonoma 14.2

### Loop Version

1.0.0

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Yup, I have noticed this too. Will look into this!

**Comment by Melonchanism** [comment]
I know that BetterSnapTool is able to delay Mission Control, so it is possible.
