### ISSUE TITLE
🐛 Can‘t restore window frame on drag

### ISSUE THREAD

**Issue by acocoadog** [MrKai77/Loop#219]
### Bug Description

If the window to be restored exceeds the boundary of the screen, it will cause the window to not be restored.

### Steps To Reproduce

1. Adjust the window to maximum
2.Use Loop to adjust the window to Right Half
3. Drag the window to the left

### Expected Behavior

In fact, many similar app have this problem. Among them, Switch avoids this problem. When dragging the window with the mouse, firstly move the window to the appropriate position according to the expected size of the recovery to ensure that the window does not touch the screen boundary after it is restored, and then restore the window size.

### Actual Behavior

As described in the description, when the window restoring, it may be limited by the screen boundary and therefore cannot restore its original size.

### MacOS Version

14.3

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Interesting, I never noticed this! Will fix!

**Comment by acocoadog** [comment]
Thank you very much! In fact, few app have noticed this problem. In addition, in the scenario I described in "Steps To Reproduce", if we drag the window to the right (that is, the direction of the edge of the screen), then this problem will not occur, I really do not know why.
Also attached is a video showing how Switch solves this problem. I hope it will be helpful to you!
![备忘录截屏2024-02-18 at 10 00 55](https://github.com/MrKai77/Loop/assets/109275092/f79469ef-99de-42f6-8328-250a44a079c4)

**Comment by MrKai77** [comment]
Let me know how this is!
[Loop.zip](https://github.com/MrKai77/Loop/files/14320980/Loop.zip)

**Comment by acocoadog** [comment]
> Let me know how this is! [Loop.zip](https://github.com/MrKai77/Loop/files/14320980/Loop.zip)

That's so cool! The problem seems to have been solved.
