### ISSUE TITLE
✨ Smaller snapping trigger areas for the top area

### ISSUE THREAD

**Issue by acocoadog** [MrKai77/Loop#222]
### Feature Request Description

The trigger area of snapping seems to be too large. Especially for the top area, the current trigger area is probably below the menu bar, so I often mistakenly trigger the snapping function when I want to move a window to the edge of the screen.

I know this may be to avoid conflicts with Mission Control, but that can be achieved by delaying Mission Control when you drag the window to the top. Similar feature is available on BetterTouchTool.

However, even so, the Snapping to top function is still easily triggered by mistake in use. In my opinion, it can be replaced by other gestures, such as triggering Snapping to top by shaking the window, which can avoid the conflict.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup, I totally agree with this! I have triggered it by accident many times too 😉
I will definitely look into fixing this! It will most likely be fixed at the same time as #212.
