### ISSUE TITLE
✨ Ability to center a window using the radial menu

### ISSUE THREAD

**Issue by andrwmai** [MrKai77/Loop#226]
### Feature Request Description

It'd be a nice addition to center a window using the radial menu. I'm a guy that mostly has one hand on the mouse so this ability would make it faster and more convenient to center a window.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
I totally agree!
It will be implemented with #107 :)

**Comment by MrKai77** [comment]
Since this is essentially #107, I'll be closing this as a half-duplicate in effort to organize information :)
