### ISSUE TITLE
✨ Haptic feedback 

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#232]
### Feature Request Description

So i was thinking if we can have haptic feedback as soon as we get the preview while looping, like i dragged a windows to the area where it starts snapping if we have haptic feedback at that time it will be seriously amazing imo, like you would be able to really feel that

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by frieza213** [comment]
@MrKai77 ??

**Comment by MrKai77** [comment]
Hey sorry for the late response, I've been super busy lately 😅
Anyways, this is a really interesting idea! I will definitely try it out!

**Comment by MrKai77** [comment]
Just finished! This was a wonderful idea, thanks for recommending it!!

Test build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14531098/Loop.zip)

EDIT: Still working on fixing a couple of bugs, but will merge once those have been sorted!

**Comment by frieza213** [comment]
No problem mate happy to help♥️

**Comment by AISLVE** [comment]
but doesn't apple already support this
![CleanShot 2024-03-08 at 13 12 21@2x](https://github.com/MrKai77/Loop/assets/121119257/bba8d1ea-0e8f-444b-8cf1-6e0a550c369a)
