### ISSUE TITLE
✨ Ability to hide/turn off Radial menu

### ISSUE THREAD

**Issue by CollinsVakayil** [MrKai77/Loop#234]
### Feature Request Description

I would really appreciate an option to toggle the radial menu off not the ability or it's functions just the appearance of the loop.

### Final Checks

- [x] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
See #183. By setting a large number as the trigger delay, you can effectively hide the radial menu.

Also: I am on vacation at the moment which is why I haven't been able to release a new version of Loop with this feature, but it is something I plan to do as soon as I get back home :)
