### ISSUE TITLE
✨ Cycle feature should save index

### ISSUE THREAD

**Issue by Dhairy2003** [MrKai77/Loop#235]
### Feature Request Description

I love the custom cycle , but it would be much better if it an just save up the last index it used for a window. That would just save up a lot of time to get to the desired layout. 

### Screenshots

https://github.com/MrKai77/Loop/assets/101127874/f0994ed5-1e59-4928-971a-ab7cfa7eef9c

### Additional Context

if a particular window is already in index 0 , Loop should not suggest index 0 ans should start from index 1

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Oh interesting idea! I will definitely look into this :)
This would be really useful when a user has a really long cycle keybind set!

**Comment by JaceThings** [comment]
Agreed. I never knew how to phrase it. I've been running into this for a while.
