### ISSUE TITLE
🐛 No preview when undoing the previous loop

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#237]
### Bug Description

So suppose i maximized a windows accidentally and wanted to revert it to it's original position in that case i will not be able to see the preview of where the current windows will go 

### Steps To Reproduce

1. Loop a windows however you want 
2. Try undoing the loop

### Expected Behavior

It should show a preview of the window's position

### Actual Behavior

It just snaps it into place, skipping the preview altogether

### Screenshots

Sorry for the keystrokes not showing every keypress cleanshot is behaving like that for some reason idk why

https://github.com/MrKai77/Loop/assets/121119257/6cd0cde1-44c6-4560-a8e8-37f7e4ef9d11

### MacOS Version

Sonoma 14.3.1

### Loop Version

Version 1.0.0 beta 14(644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Oh! I feel like this used to work in an earlier version.. maybe I accidentally made a change to the code that also removed this functionality? I will definitely fix this!

**Comment by MrKai77** [comment]
Whoops, looks like I forgot to mention this but this was fixed in PR #263!
