### ISSUE TITLE
🐛 Loop preview triggered when resizing dock or moving widgets

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#238]
### Bug Description

So when i resize dock or move widgets loop thinks of them as an application dragon and preview is activated for no reason

### Steps To Reproduce

1. Resize dock to the smallest or move widget to one of those areas where you would normally snap a window

### Expected Behavior

Loop should do nothing

### Actual Behavior

Loop preview appears

### Screenshots

https://github.com/MrKai77/Loop/assets/121119257/dfbd6a9e-6a8f-4ebc-9f6e-1a07328a1256

### MacOS Version

Sonoma 14.3.1

### Loop Version

Version 1.0.0 beta 14(644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Interesting, will definitely look into this as well!

**Comment by MrKai77** [comment]
I can't seem to reproduce this on my computer. Maybe it's because I'm running a newer build?
Would you be able to try this build which is directly from the `develop` branch:
[Loop.zip](https://github.com/MrKai77/Loop/files/14547457/Loop.zip)

**Comment by frieza213** [comment]
can't reproduce the bug in this build but haptic feedback is there when moving widgets into the snap area(in the build you provided)

**Comment by frieza213** [comment]
also, in the previous build you provided loop was sometimes not activated i would have to close and reopen the app

**Comment by MrKai77** [comment]
> also, in the previous build you provided loop was sometimes not activated i would have to close and reopen the app

Oh? And you're completely sure that this didn't exist in the last release version?

**Comment by MrKai77** [comment]
> can't reproduce the bug in this build but haptic feedback is there when moving widgets into the snap area(in the build you provided)

Oh yeah you're right. I will fix this!

**Comment by frieza213** [comment]
> > also, in the previous build you provided loop was sometimes not activated i would have to close and reopen the app
> 
> Oh? And you're completely sure that this didn't exist in the last release version?

yeah there was no such bug in the stable release but the build that you provided in an issue before this one has the bug

**Comment by MrKai77** [comment]
Here's a build that should fix this issue (with the widgets) :D
[Loop.zip](https://github.com/MrKai77/Loop/files/14547915/Loop.zip)
