### ISSUE TITLE
🐛 Wrong top gap produced when `Looping`

### ISSUE THREAD

**Issue by qkdxorjs1002** [MrKai77/Loop#24]
### Bug Description

Thank you for dev this amazing app.

There is an unexpected top gap when i sorted the window.

### Steps To Reproduce

1. [Hold `Globe` & Move mouse]
2. [Align window]
3. [Unexpected top gap]

### Expected Behavior

There's no gap on top of desktop.

### Actual Behavior

There's unexpected gap on top of desktop.

### Screenshots

https://github.com/MrKai77/Loop/assets/3241479/b6f79d31-c90f-4382-bb6d-6fc9f8477f93

### MacOS Version

Ventura 13.5.1(22G90)

### Loop version

Version 1.0.0-beta.8 (298)

### Additional Context

Macbook Pro 14 M1 2021
2 External display

**Comment by MrKai77** [comment]
Thank you so much for reporting this bug! I can also reproduce it as well.
It seems like the top gap is caused by Loop thinking the dock is on the top... I should be able to fix this within the few days :)

**Comment by MrKai77** [comment]
Actually, I was able to fix it pretty quickly! Here's a build with the latest changes!
[Loop.zip](https://github.com/MrKai77/Loop/files/12544502/Loop.zip)
EDIT: This does not seem to work correctly on an external display.

**Comment by MrKai77** [comment]
Alright, here's the corrected version: [Loop.zip](https://github.com/MrKai77/Loop/files/12544557/Loop.zip)
Sorry for the inconvenience! Please let me know if the bug persists 😉

**Comment by qkdxorjs1002** [comment]
@MrKai77
I tested with attached app. The issue is gone! working perfectly. Thank you!
