### ISSUE TITLE
🐛 Whatsapp doesn't reposition properly to the bottom

### ISSUE THREAD

**Issue by jrvgr** [MrKai77/Loop#244]
### Bug Description

Currently, when i try to move whatsapp to any of the bottom corners or the bottom half, it instead will do that action on the top

### Steps To Reproduce

1: Open whatsapp
2: try to resize or reposition to any of the bottom halfs

### Expected Behavior

should reposition properly

### Actual Behavior

will do the action, but on the top of the screen on my macbook screen

### MacOS Version

Sonoma, 14.3.1

### Loop Version

Version 1.0.0-beta.14 (644)

### Additional Context

I'm using 2 1920x1200 screens alongside my macbook, repositioning issue only occurs on my macbook screen

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by frieza213** [comment]
Yeah whatsapp breaks mission control too, which means it must a problem on their end

**Comment by jrvgr** [comment]
> Yeah whatsapp breaks mission control too, which means it must a problem on their end

I haven't had that bug yet, but it doesn't surprise me. Hope they fix it soon!

**Comment by MrKai77** [comment]
Interesting... I'll investigate this! But it most likely is a Whatsapp problem and won't be fixable on Loop's side.
But would you be able to try toggling window animations on/off (depending on the current setting) and see if that fixes it?

**Comment by AISLVE** [comment]
@MrKai77 check #245

**Comment by jrvgr** [comment]
Had window animations on, when turned off it works fine.

**Comment by MrKai77** [comment]
Oh got it! In that case, this is a duplicate of #95.

Window animations are still very unreliable, so I would recommend having them off for now :)
