### ISSUE TITLE
🐛 "Resize window under cursor" is always active, even when disabled

### ISSUE THREAD

**Issue by Stooovie** [MrKai77/Loop#248]
### Bug Description

Even when "Resize window under cursor" is disabled, Loop doesn't windows that are not under cursors, even when the window is active/focused. The setting doesn't do anything.

### Steps To Reproduce

1. disable "Resize window under cursor"
2. open a window
3. carry out a command, for example Maximize
4. unless cursor is over that window, command is not carried out

### Expected Behavior

Command is carried even when cursor is not over active window

### Actual Behavior

Command is not carried when cursor is not over active window

### MacOS Version

sonoma 14.4

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
That's weird, it seems to work fine on my side 🤔

Can you try this build and see if it works? (It's directly off the `develop` branch)
[Loop.zip](https://github.com/MrKai77/Loop/files/14551463/Loop.zip)

If that doesn't work, would you be able to also send a quick screen recording of this behavior?

**Comment by Stooovie** [comment]
Working as expected now but Loop is generally very confused with a dual display setup. I'll open a new report, this is working now. Thanks!
