### ISSUE TITLE
✨ Configuration for Loop triggering time

### ISSUE THREAD

**Issue by qkdxorjs1002** [MrKai77/Loop#25]
### Description
If it works so that the Loop takes a certain amount of time to be triggered, I can use both `the action assigned(macOS)` and `the Loop triggering`.

### Example
Tap Globe to trigger `action assigned(macOS)`
Hold (100ms) to trigger `the Loop triggering`

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/3241479/c61766a0-8b48-45b9-a243-54078b7ac293)

**Comment by MrKai77** [comment]
Really cool idea! Thanks for the diagram too! I'll definitely look into this!

**Comment by MrKai77** [comment]
I tried implementing it! Here's the latest build with these changes:
[Loop.zip](https://github.com/MrKai77/Loop/files/12554371/Loop.zip)
