### ISSUE TITLE
✨ Ignore mouse screen

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#251]
### Feature Request Description

Currently, when using the center window command, loop does not consider where the window is located. It will set the window's location based on the monitor where the mouse is currently positioned. This can be frustrating because when setting specific sizes and locations for windows on secondary monitors while your mouse is on the primary monitor, centering that window will undo all your changes and move it back to the primary monitor.

Allowing the ability for loop to ignore the mouse position and be completely based off of the keyboard would be great :)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Agreed! This is more of a remnant from before Loop supported multi-monitor setups, where this was the only way to make it support those setups (at least partially). I can definitely implement this :D

**Comment by iamk3v** [comment]
This should be added as a togglable option in settings. Could be a new setting heading "Mouse behavior" or something, where #359 (and others if there are more cursor feature requests) could be. Could be cases where `NSScreen.screenWithMouse` is better than `NSScreen.Main` :)

**Comment by MrKai77** [comment]
Hmm interesting, I guess so!

@Soft-Bred do you think you could quickly add this option into the redesign Figma file when you have time 😉

**Comment by JaceThings** [comment]
Solved:

https://www.figma.com/design/7JLRVafMYI9kbpnDcwd9Of/Loop?node-id=285-1693&t=CgClOoR4o9vbmtKe-11

**Comment by hoelderlin** [comment]
Hi, when are you planning to sort out this issue? As mentioned in another post, if you disable preview it works fine.

**Comment by MrKai77** [comment]
Yes, it has been implemented :)
Try this build:
[Loop.zip](https://github.com/user-attachments/files/15878257/Loop.zip)

**Comment by hoelderlin** [comment]
Oh, wow! You changed the settings interface. It looks awesome and apart from that it is indeed working! When are you going to release this version?

**Comment by MrKai77** [comment]
Within the next few days!

**Comment by JaceThings** [comment]
actually now lol

**Comment by dropalltables** [comment]
lmao yeah

**Comment by donflopez** [comment]
When working with multiple screens, how can I make my window jump across them so I place my window in the screen I want it to be without having to move the mouse?

**Comment by JaceThings** [comment]
What are the actions you're trying to perform? Are you using the keyboard to resize the window on the display that your mouse is not on or are you trying to change the display via your keyboard?

Try turning this off and see if it helps:
![000485@2x](https://github.com/MrKai77/Loop/assets/60551230/969daa60-4d07-4e65-9997-3df6d7f96c9f)

**Comment by donflopez** [comment]
I've tried that, I see there is a specific next screen command but I was looking for the same experience I've seen in other managers like ivvy and rectangle.

For example, when maximizing with action + space I would expect it to do it in the screen the app is and if I press twice to jump to the next screen. Is this possible?

**Comment by MrKai77** [comment]
@donflopez Try making this cycle keybind:
<img width="464" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/d4a5c1e5-449e-4c7c-8bd4-ea3f073dfcea">

**Comment by donflopez** [comment]
that works! thank you, that is a very powerful setup. It'd be great to have one of these by default so users know that is an option. It took me a good amount of time looking the docs, poking around setting and finally searching issues that could have something about that.
