### ISSUE TITLE
✨ More options for moving windows

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#254]
### Feature Request Description

Hey, could you add more options to place and window like not just center, but also bottom center/right/left, top center/right/left, left and right and so on, what i mean is to be able to just place the windows in the positions give above and not resize it

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Interesting, will look into this!

**Comment by MrKai77** [comment]
Here's a build with those options!
[Loop.zip](https://github.com/MrKai77/Loop/files/14717331/Loop.zip)
(I am still working on this so I will send a more finalized build later!)

**Comment by frieza213** [comment]
Thanks a lot, will try after some days, currently busy

**Comment by MrKai77** [comment]
Here's the finalized build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14717504/Loop.zip)
<img width="416" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/cfa177e8-2ffd-4e34-a24d-40e36839e1ae">
Since it works off of custom window actions, the chances it will contain a bug are very low, so I will probably merge this tomorrow!

**Comment by JaceThings** [comment]
> the chances it will contain a bug are very low

Centering windows on external displays is broken lol

https://github.com/MrKai77/Loop/assets/60551230/2fa67ddd-9162-4ba0-8acd-279fcbda6936

**Comment by MrKai77** [comment]
That's funny 💀

Anyways, since I did find that it was much less stable than preferred, I have been in the process of completely remaking it using a different method, so I'd recommend staying off this build haha 😂

**Comment by MrKai77** [comment]
An updated working build can be found [here](https://github.com/MrKai77/Loop/issues/225#issuecomment-2021614555) :)
