### ISSUE TITLE
🐞 Can't grant accessibility access on DMG built from action

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#256]
### Bug Description

 I just downloaded the built DMG from the GitHub actions and upon installing it it requests accessibility access which it appears to have however it doesn't end up controlling windows.

### Steps To Reproduce

1. Download DMG from latest build
2. Open Loop
3. Attempt to grant access

### Expected Behavior

Working	

### Actual Behavior

Not working

### MacOS Version

14.3

### Loop Version

Latest build

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Yup, this is an issue I also used encounter with my local builds. When an app is granted accessibility permissions in System Settings, it only seems to work for that specific instance of the app, and somehow not for others (maybe this is related to codesigning or the app's installation folder?)

Anyways, a temporary fix for this is to run:
`tccutil reset Accessibility com.MrKai77.Loop` to force-reset Loop's accessibility permissions. The same goes for screen recording, except that `Accessibility` would need to be replaced with `ScreenCapture`. Then, you can relaunch the app to re-grant those permissions.

I'll keep this issue open for now while I work on getting the GitHub Actions build working reliably :)

**Comment by jacksongoode** [comment]
Hmm, even after following your instructions I still suffer from the same issues.

**Comment by MrKai77** [comment]
Hey @jacksongoode! I got prereleases working, you should be able to use them without any issues now :)

**Comment by jacksongoode** [comment]
Awesome, thanks!
