### ISSUE TITLE
✨ Restore to initial window size

### ISSUE THREAD

**Issue by X1AOX1A** [MrKai77/Loop#257]
### Feature Request Description

Hi! Is there a way to restore to the default window size of the app (instead of "Initial Frame") ?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
I see, so the window size would be restored but it's position wouldn't? Would the window simply resize to the original size on the spot relative to the top left corner or would it center itself relative to the screen?

**Comment by X1AOX1A** [comment]
I would favor restoring it to the center—truly appreciate this fantastic application!

**Comment by MrKai77** [comment]
Alright, I have added this feature in #263 where instead of being limited to centering the initial size, you can put the initial size anywhere :)
<img src='https://github.com/MrKai77/Loop/assets/68963405/bb932e0e-18d4-408d-a401-6f210d8f4ca5' width='500'>

**Comment by X1AOX1A** [comment]
Greatly appreciated!
