### ISSUE TITLE
✨ Enable Trigger Key when Caplock is on

### ISSUE THREAD

**Issue by X1AOX1A** [MrKai77/Loop#258]
### Feature Request Description

Hi, I found that the Trigger Key (Left control+Left option) doesn't work when Caplock is on, is there a way to  enable Trigger Key when Caplock is on?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Made some changes, this seems to work!
[Loop.zip](https://github.com/MrKai77/Loop/files/14629160/Loop.zip)

**Comment by X1AOX1A** [comment]
Thanks for the quick fix! It functions exactly as anticipated.
