### ISSUE TITLE
Clicking sound when using trackpad with loop

### ISSUE THREAD

**Issue by stffz** [MrKai77/Loop#267]
### Feature Request Description

I would like the possibility to turn off the clicking sound that trackpad makes when choosing window size with your app.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup, actually this was implemented in #175 :)
I am planning to release a new Loop version very soon, but for the time being, you can use this build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14747526/Loop.zip)

You will find it in the "More" section in the settings window:
<img width="435" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/99b082e3-e469-4745-a13c-ad2f768389f1">

**Comment by stffz** [comment]
Thanks!
