### ISSUE TITLE
🐛 Window resizes in opposite direction

### ISSUE THREAD

**Issue by loyaniu** [MrKai77/Loop#269]
### Bug Description

I just heard of this app today, and it really attracted me. So I tried it just now around half an hour. For some reason, the resize didn't behave as it is expected. For example, if I click `right third`, the window moves to the left, and then I click the button again, it behaves as it should. Movements like `maximize`, and `center` also have this problem.

### Steps To Reproduce

1. Open up a window
2. Try to move it around...

### Expected Behavior

The window should be moved and resized correctly.

### Actual Behavior

As I mentioned in bug description.

### MacOS Version

14.4.1

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
That's really odd 🤔
Can you try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14765457/Loop.zip)?

**Comment by loyaniu** [comment]
It is! I just installed OBS and trying to take a screen record.

**Comment by loyaniu** [comment]
https://github.com/MrKai77/Loop/assets/112656202/ae9f4e9e-1a79-4035-ba09-af1ef0269ee0

**Comment by MrKai77** [comment]
> 2024-03-27.16-55-31.mov

I'm not sure if I understand the problem. Is it fixed now?

**Comment by loyaniu** [comment]
I think I didn't demonstrate it well in the video. But the problem is gone now, I don't know why.

Thanks for such a good app.

I will try to provide a better video if it happens again.
