### ISSUE TITLE
✨ Localization

### ISSUE THREAD

**Issue by Zero-Cjh** [MrKai77/Loop#270]
### Feature Request Description

This is a great application.
There are many people who use it, so we should add multilingual adaptation function.
Thank

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Since Loop is currently still in beta, I have not looked into localization yet (since many things could change during this time). However, there are certainly parts of Loop that I know will not change for a long time, so I will definitely look into this :)
