### ISSUE TITLE
✨ Customized Roulette Wheel

### ISSUE THREAD

**Issue by ohhcarina** [MrKai77/Loop#271]
### Feature Request Description

I hope the wheel can be customized! For example, moving the cursor to the right side of the wheel means 3/4 of the screen on the right, but it just right half now. The default settings are not frequently used by me. 

That's the feature I most desire! 

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Duplicate of #107
