### ISSUE TITLE
✨ 希望提供多语言支持 Hope to provide multilingual support

### ISSUE THREAD

**Issue by yamazakitouma** [MrKai77/Loop#272]
### Feature Request Description

I hope to use AI for translation and provide support for multiple languages, especially Simplified Chinese. This is very important to me. Thank you

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Seems like a duplicate of #270 to me (correct me if I am wrong)
