### ISSUE TITLE
🐛 Often crashes when frequently adjusting the window using Loop

### ISSUE THREAD

**Issue by ahaostudy** [MrKai77/Loop#273]
### Bug Description

When I use the trigger key to frequently adjust the window, Loop crashes and becomes unresponsive.

### Steps To Reproduce

I have not yet found a pattern. My operation process is to use the middle key as the trigger key, hold the middle key, and continuously move the mouse. After about 10 times, it will freeze.

### Expected Behavior

Smooth adjustment is possible.

### Actual Behavior

Loop crashes.

### Screenshots

<img width="2560" alt="image" src="https://github.com/MrKai77/Loop/assets/92586826/b488d208-1356-467e-93b9-531983b20151">

### MacOS Version

Sonoma 14.4

### Loop Version

1.0.0-beta.14

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by ahaostudy** [comment]
It doesn't seem to need 10 times. Sometimes, it freezes even when I just move it a bit. I've only installed it for a few tens of minutes, and it has already happened four or five times.

**Comment by MrKai77** [comment]
I am unable to reproduce this. Would you be able to try this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14765457/Loop.zip)?

**Comment by ahaostudy** [comment]
Thank you. I made some adjustments to the Loop configuration just now and it appears the issue is no longer occurring for me. If I find a way to reproduce the problem, I will sync up.

**Comment by ahaostudy** [comment]
If necessary, you can close this issue for now. I will reopen it once I find the steps to reproduce the problem.
