### ISSUE TITLE
Macbook and external (Apple) Keyboard

### ISSUE THREAD

**Issue by macTiGerman** [MrKai77/Loop#275]
### Feature Request Description

When using the MacBook without an external keyboard, using the "globe" key to invoke Loop works nicely. But I am using often an external keyboard, that does not have the globe key. So I would need another invoke key for that setting. Best scenario would be, that Loop recognises, if an external keyboard is used and switches the invoke key accordingly.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yes, unfortunately it is impossible to detect the <kbd>fn</kbd> key. 
I would recommend using [Karabiner Elements](https://karabiner-elements.pqrs.org/) to remap that key on your external keyboard to Loop's trigger key :)
