### ISSUE TITLE
✨ Chinese localization

### ISSUE THREAD

**Issue by biaohhh** [MrKai77/Loop#276]
### Feature Request Description

hello designer,I really like this software so much, I am a Chinese student and I hope to have a Chinese translation,it will make it easier to use. thanks a lot!!

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Awesome! Loop is currently not yet set up for localization, but as soon as it is, I will let you know so that you can get started :D

**Comment by kamiimeteor** [comment]
Hello! I'm really excited about the application you've developed and am very interested in the localization effort you mentioned. 
I noticed that you're not quite ready for localization yet, but I wanted to express my keen interest in joining the team when the time comes. 
I'm also from China and work as a UX and UI designer, so I believe I could contribute significantly to the project, especially in terms of localizing the app for Chinese users. 
Please consider me when you start recruiting for the localization team. Looking forward to the opportunity to contribute!

**Comment by MrKai77** [comment]
Oh! Actually, Chinese localization was merged in #303, as seen above :)
It will be included in the next release! For now, you can use this build: [Loop.zip](https://github.com/MrKai77/Loop/files/14819167/Loop.zip)
