### ISSUE TITLE
🐛 Drag and resize still working even after I delete the app

### ISSUE THREAD

**Issue by Jiaxin-Pei** [MrKai77/Loop#277]
### Bug Description

I love loop. However, one thing that prevents me from using it is the drag and resize feature. It's really bothering me that even when I'm just trying to move the window to another place, it automatically pad it to half of the screen, and i cannot even turn it off. Another bigger issue is: even after I delete LOOP, this feature is till there and I don't know how to remove it.

### Steps To Reproduce

Uninstall loop and the drag&resize feature is still there

### Expected Behavior

Uninstall loop and the drag&resize feature will also be removed

### Actual Behavior

Uninstall loop and the drag&resize feature is still there

### MacOS Version

14.4.1

### Loop Version

Latest

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Can you send a screen recording? Also check if Loop is somehow still running in Activity Monitor :)

**Comment by Jiaxin-Pei** [comment]
Hi @MrKai77, I have checked that loop is not running in the activity monitor. It seems that this issue happens when mac is connected to an external monitor. 

Here is the screen recording:
![loop_screenshot](https://github.com/MrKai77/Loop/assets/42936410/0e27e801-2784-437d-8bd3-6d12715b9aa3)

**Comment by MrKai77** [comment]
Can you please try restarting your computer (if you haven't already)?

**Comment by Jiaxin-Pei** [comment]
@MrKai77 I restarted it multiple times, and it's still there. I'm sure it's not active in the activity monitor. It's so mysterious.

**Comment by MrKai77** [comment]
Hm... I've never seen this happen before but try re-installing Loop and disabling window snapping, then uninstalling it again maybe?

**Comment by Jiaxin-Pei** [comment]
@MrKai77 it's still there. Is there a way to disable this feature when LOOP is installed?

**Comment by MrKai77** [comment]
Right here: 
<img width="423" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/6b1670dc-b986-493f-8818-2f5d473e9dbf">
It is disabled by default, so if you never turned it on, it *could* be another app that is triggering the window snapping.

**Comment by Jiaxin-Pei** [comment]
@MrKai77 Interesting, I tried to turn it off and then uninstall but the snapping is still there. Do you know any other apps that might trigger this? I'm using a brand new mac and didn't install other window management tools.

**Comment by MrKai77** [comment]
There's a lot that can vary, but are there any other window managers you may have installed recently?
And, if possible, would you be able to provide a full-screen-sized screen recording of the window snapping?

**Comment by Jiaxin-Pei** [comment]
@MrKai77  Nope, I didn't.

Here's the full screen recording. I tried to restart the computer. I found that at the beginning this snapping is not there. But after around one minute, it appears. 


https://github.com/MrKai77/Loop/assets/42936410/bb7a317d-7c46-48a5-89cf-a785ea7f48ab

**Comment by MrKai77** [comment]
Interesting. Can you send a screenshot of the apps in `Settings` -> `Privacy & Security` -> `Accessibility`?

**Comment by Jiaxin-Pei** [comment]
@MrKai77 Heyy I'm so sorry! I found out what's going on.

My computer has [DDPM](https://www.dell.com/support/kbdoc/en-us/000201067/dell-display-and-peripheral-manager-for-macos) installed, which is a software to help manage Dell monitors, somehow this application has the snapping feature. I don't if it's loop or something else that triggers DDPM to do this. But I'm so sorry for wasting your time on this and I appreciate your kind help!

**Comment by MrKai77** [comment]
No problem! Glad you found the cause :)
