### ISSUE TITLE
🐛 It can move widget on my mac

### ISSUE THREAD

**Issue by junming-24** [MrKai77/Loop#286]
### Bug Description

When I use shortcut, it can move my widget. This is annoying.

### Steps To Reproduce

n/a

### Expected Behavior

Fic this bug

### Actual Behavior

n/a

### MacOS Version

14.4

### Loop Version

Latest

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
The latest update will fix this. Please update to `1.0.0-beta.15` :D

**Comment by junming-24** [comment]
Thank you so much!!!
