### ISSUE TITLE
🐛 Preview laggy while maximizing for the first few times

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#288]
### Bug Description

When i maximize any windows using ⌥ + ⌥ + space , i can see some framedrops, but after doing it a few time it is smooth as any other preview for example the right half or any other than the maximizing

### Steps To Reproduce

1. Trigger preview for the maximize 

### Expected Behavior

It should be smooth like any other preview animation

### Actual Behavior

It lags and drops frames

### MacOS Version

Sonoma 14.3.1

### Loop Version

Version 1.0.0 beta 14(644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
In Loop 1.0.0-beta.15, I have remade the preview window to animate using a different mechanism. Can you see if the issue still exists in the latest version?

**Comment by frieza213** [comment]
****First Impressions****
- The animations are way smoother than before
- The radial loop animations too are tactile
- Overall, a very nice improvement

But will update you if i face any bugs or issues
