### ISSUE TITLE
🌐 Localization: Italian

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#297]
### Feature Request Description

I'm willing to translate the app into Italian :)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Awesome, thanks! I am still setting up localization within Loop but I will let you know when it's ready!

**Comment by MrKai77** [comment]
Just got it ready! Here's the localization file that you will need to fill in: [it.xcloc.zip](https://github.com/MrKai77/Loop/files/14813580/it.xcloc.zip)
After unzipping, you can open the file with Xcode, and the rest should be pretty easy :)

There are some entries where it only shows `%@` or `%@ %@` (you will see them as soon as you open the file above), but you don't need to fill these in.

This is my first time dealing with localization, so if you find anything that looks confusing or doesn't make sense, please feel free to ask for help :)

Edit: please hold off on this as there will be changes to the localization process caused by #303 :)

**Comment by MrKai77** [comment]
Alright, here's an updated file you can work on!
[it.xcloc.zip](https://github.com/MrKai77/Loop/files/14817481/it.xcloc.zip)

**Comment by Zabriskije** [comment]
There you go: [it.xcloc.zip](https://github.com/MrKai77/Loop/files/14826497/it.xcloc.zip) :)

**Comment by MrKai77** [comment]
This is awesome! There are, however, two missing translations: 
![image](https://github.com/MrKai77/Loop/assets/68963405/4e389f93-809e-4629-9bb1-bd434b415827)
Maybe they were missing from the file I sent sorry 😓 
If you could send them here that would be great :D

**Comment by Zabriskije** [comment]
No problem. There is a third attribute in mine (`%3$@`), so it's that maybe

Current version:
```
Versione attuale: %1$@ (%2$@)
```

Version:
```
Versione %1$@ (%2$@)
```

**Comment by MrKai77** [comment]
Awesome, thanks!! I am also in the process of remaking the settings window (since some panes are starting to get oversized), so I *might* be asking you to translate a few more strings once that's done!

**Comment by MrKai77** [comment]
@Zabriskije Can you retranslate this? Most strings should be transferable from the old version :)
[Loop Localizations - Italian.zip](https://github.com/user-attachments/files/15905977/Loop.Localizations.-.Italian.zip)
Sorry for the inconvenience.

**Comment by Zabriskije** [comment]
There you go: [Italian.zip](https://github.com/user-attachments/files/15912787/Italian.zip)

I've found that `%@ places windows slightly above the absolute center, which can be found more ergonomic.`, `Add`, and `Remove` are absent (and maybe some more?). While the first could have been removed in a new version, I doubt this also happened to the last two :)

**Comment by MrKai77** [comment]
Thanks @Zabriskije!

You are correct, looks like I was missing a few strings 😅

Can you translate the 5 remaining strings in here:
[it.xcloc.zip](https://github.com/user-attachments/files/15915316/it.xcloc.zip)

EDIT: I was missing another one: "Include development versions". I'd appreciate it if you could translate that too :)

**Comment by Zabriskije** [comment]
You've got me geeking out a bit with this one 🤓

Just for future situations where I may have to do this again, is it correct (or rather, is it the easiest thing) to download the project and run `xcodebuild -exportLocalizations -localizationPath /CUSTOM-PATH -project /LOOP-PATH -exportLanguage it`?

I have done this via CL since I couldn't build the project and didn't know what was going wrong.

Anyway, [here's the file](https://github.com/user-attachments/files/15920929/it.xcloc.zip) ✨

**Comment by MrKai77** [comment]
Haha thank you so much!! Looks like you know more about localization than me 👀
Anyways, running that command next time will be totally fine :D
I'm guessing that the problem is that you didn't clone recursively? Try `git clone --recursive` next time.

**Comment by MrKai77** [comment]
Hey @Zabriskije, looks like I missed the string "Contributors on GitHub":
<img width="385" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/1c95aa9b-5352-46cd-91c2-821cf14f2a97">
Can you translate that too, just a reply to this message will be alright :)

**Comment by MrKai77** [comment]
Actually, some more were found :p
5 more strings are to be translated in this file:
[it.xcloc.zip](https://github.com/user-attachments/files/15935792/it.xcloc.zip)

Sorry for not noticing these earlier.

**Comment by Zabriskije** [comment]
No problem, there you go: [it.xcloc.zip](https://github.com/user-attachments/files/15937515/it.xcloc.zip) :)

**Comment by MrKai77** [comment]
Thank you!!

**Comment by MrKai77** [comment]
I have more strings to be translated before releasing, it would be awesome if you could fill this in: [it.xcloc.zip](https://github.com/user-attachments/files/16257254/it.xcloc.zip)

Most of these are more update messages with pop culture references, so if there aren’t any equivalents in Italian, simply fill them in with a “-“ or feel free to add your own references!

**Comment by Zabriskije** [comment]
Sent on Discord ;)
