### ISSUE TITLE
🐛 Instant animation is not instant

### ISSUE THREAD

**Issue by YonglinChann** [MrKai77/Loop#299]
### Bug Description

Hello! I noticed that in the past Beta 14, when I set the speed of the animation to Instant, the animation preview will be canceled and only Preview will be provided, which is a simple effect. However, in the latest Beta 15, no matter how the dynamic level is set, the effect of Instant is almost the same as Fast, and the animation is forced to be provided. However, on the MacBook Pro with ProMotion refresh rate, the animations of Loop do not fit the 120Hz display, and these animations are very stuck on the ProMotion screen.

### Steps To Reproduce

When set to Instant, animation will be forced to appear every time it is used.

### Expected Behavior

It is hoped that Loop can restore the ability to provide only previews and cancel the mandatory dynamic effect when the animation is set to Instant.
Or Loop's animation can be perfectly adapted to MacBook Pro with ProMotion 120Hz refresh rate.

### Actual Behavior

It is hoped that Loop can restore the ability to provide only previews and cancel the mandatory dynamic effect when the animation is set to Instant.
Or Loop's animation can be perfectly adapted to MacBook Pro with ProMotion 120Hz refresh rate.

### MacOS Version

macOS Sonoma 14.4.1 (23E224)

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Got it! I remade the preview window in the latest version, and it seems like I may have forgotten to remove the animation from `instant`. I will restore the original functionality from beta 14!

**Comment by MrKai77** [comment]
Try this: [Loop.zip](https://github.com/MrKai77/Loop/files/14812979/Loop.zip)

**Comment by YonglinChann** [comment]
Thank you very much for taking the time to answer my questions! 
At the same time, I also hope that the animation of Loop can better adapt to the MacBook Pro with a ProMotion high refresh rate screen. Because in the same type of software, their animation is not well adapted to the high refresh rate. If Loop can do this, it will be a great experience! Thank you!
