### ISSUE TITLE
🐛 Color picker in Settings still pops out on the next start

### ISSUE THREAD

**Issue by alvin96** [MrKai77/Loop#305]
### Bug Description

I would say it's the best window management tool I've ever used. I've tried Rectangle before, but it's still not as intuitive for me because I need to drag the window to the desired position or use shortcut keys. Plus, I'm not someone who remembers a ton of shortcut keys, haha. However, I found a tiny bug today (please close this issue if it's a feature). After I changed the color of the radial menu, the color picker in Settings still pops up the next time I go to settings.

### Steps To Reproduce

1. Go to "Settings" and disable "Use System Accent Color"
2. Select "Custom Accent Color" (Close the color picker dialog using x button on the menubar)
3. Enable "Use Gradient"
4. Select "Custom Gradient Color" (Close the color picker dialog using x button on the menubar)
5. Close "Settings"
6. Reopen "Settings" again and you will see color picker also pop out

### Expected Behavior

Color picker won't pop out after "Settings" reopen

### Actual Behavior

Color picker in Settings still pops out on the next start

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/20142859/71c1e8ef-a44f-4f6b-acd2-3f9cfd8feedf)

### MacOS Version

Sonoma 14.4.1 

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Yep, this is indeed a bug. I will look into it!

**Comment by alvin96** [comment]
> Yep, this is indeed a bug. I will look into it!

Thanks, looking forward to this #107 feature too✨
