### ISSUE TITLE
🐛 a wrong word hhh

### ISSUE THREAD

**Issue by biscuitbicky** [MrKai77/Loop#308]
### Bug Description

The word "ergonomic" was spelt with an additional 'n'.
![image](https://github.com/MrKai77/Loop/assets/110220931/259c9b35-8fd2-422e-9032-963af2eedea3)
<img width="590" alt="image" src="https://github.com/MrKai77/Loop/assets/110220931/3185d8b6-1ba5-49f8-a0fc-45a6f02809fc">

As a beginner to Github, I'm not sure whether issue is used in the way. Please tell me if I did anything wrong, I'll correct it next time. Thanks for your patience. QWQ

### Steps To Reproduce

...

### Expected Behavior

...

### Actual Behavior

...

### MacOS Version

Sonoma 14.2.1

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
This was fixed when localization support was added!
This build has that fix: [Loop.zip](https://github.com/MrKai77/Loop/files/14819167/Loop.zip)
