### ISSUE TITLE
🐛 Check for accessibility permits automatically so that relaunch isn't required

### ISSUE THREAD

**Issue by sagarishere** [MrKai77/Loop#309]
### Bug Description

Kindly note that I am new to Loop (that you for creating such a fantastic product under MIT).
I do not know if this is expected behaviour. 

Here is what I observed: I have updated the permission, however, I still see that the permission is not granted in the loop settings.

### Steps To Reproduce

1. Open Loop.
2. Update setting to grant permission.
3. The permission granted is still red dot.

### Expected Behavior

The permission window should auto-detect if the permission is granted for the next 5 minutes, every 3 to 4 seconds, if the button of permissions has been click in the Loop settings, to dynamically update the permission.

### Actual Behavior

The permission is not updated in the settings to display the actual reality of the permission that has been granted.

### Screenshots

<img width="1163" alt="image" src="https://github.com/MrKai77/Loop/assets/5121817/55d85751-7227-4512-8bce-faa662761530">

### MacOS Version

14.4.1 (23E224)

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
I will look into this! Currently, this requires a relaunch of Loop, but I do agree that periodically checking the state instead would lead to a better user experience :D
