### ISSUE TITLE
🌐 Localization: Brazilian Portuguese

### ISSUE THREAD

**Issue by willianba** [MrKai77/Loop#312]
### Feature Request Description

I'd like to help translating the app to pt-br 😁

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thank you! I am currently in the middle of re-arranging the settings window, (and potentially renaming/remaking some parts), so I can send you a localization file once that's finished :)

**Comment by willianba** [comment]
hey @MrKai77! sure.
just let me know and I can work on it 😉

**Comment by MrKai77** [comment]
Loop is now ready to be localized :)

Open the file in here in Xcode to start!
[Loop Localizations - Brazilian Portuguese.zip](https://github.com/user-attachments/files/15906028/Loop.Localizations.-.Brazilian.Portuguese.zip)

**Comment by willianba** [comment]
thanks for the heads up @MrKai77!! will try to work on it tomorrow.

**Comment by willianba** [comment]
hey @MrKai77 quick question. is there an easy way to check where the strings are going to appear in the app?

some are longer and some are too generic without context. i was wondering if i can try it first before sending it back to you

**Comment by MrKai77** [comment]
Unfortunately not :(
If you'd like, when you're done, you can send the translations over, and I can send you a build containing the strings, so that you can verify it before approving it 😉 

EDIT: unless you want to build the app yourself*

**Comment by MrKai77** [comment]
To add on, if you have any specific strings you're confused about, feel free to just ask me about them and I'll tell you where they appear :)

**Comment by willianba** [comment]
i never worked with Swift for trying to build it myself 🤣 
I'll finish it this evening (around 7pm EST) and will send it over here.

if it's not much effort for you to build a pt-br version so i can check it, i wouldn't complain.

**Comment by MrKai77** [comment]
That's great to hear! 

> if it's not much effort for you to build a pt-br version so i can check it, i wouldn't complain.

Yup, it's pretty easy to do :)

**Comment by willianba** [comment]
[Loop Localizations - Brazilian Portuguese.zip](https://github.com/user-attachments/files/15934655/Loop.Localizations.-.Brazilian.Portuguese.zip)

there you go. the only one i couldn't think about a good translation was "stage strip size". but i think it ended up great

let me know if there's something bad 🫡

**Comment by MrKai77** [comment]
Awesome! It looks really good to me :) (although I don't understand most of it 😅)

Here's a build with those changes:
[Loop.zip](https://github.com/user-attachments/files/15934702/Loop.zip)

Additionally, it looks like I missed a few strings in the initial file I gave you, would you be able to translate the 5 remaining strings in here?
[pt-BR.xcloc.zip](https://github.com/user-attachments/files/15934704/pt-BR.xcloc.zip)

Thank you very much!!

**Comment by willianba** [comment]
oh yeah i missed the "Add" while i was translating the "Press 'Add' to ...". but i moved on and forgot about it.

found a couple strings that weren't translated though... i think that's my system. i put it in portuguese now to check but i was lazy to reboot 🤣 

<img width="401" alt="image" src="https://github.com/MrKai77/Loop/assets/26071084/0e568eae-29be-4973-ae92-ad13775eef23">

also fixed some inconsistencies i found. i realized i can't find the "Contributors on GitHub" in the file you provided. is that expected?

![image](https://github.com/MrKai77/Loop/assets/26071084/acd039fd-d7e6-4f06-96cb-1d39407b70c7)

here's the updated file:

[pt-BR.xcloc.zip](https://github.com/user-attachments/files/15934732/pt-BR.xcloc.zip)

**Comment by MrKai77** [comment]
Oh wow, good eye, I completely missed the "Contributors on GitHub" part! If you can just reply to this message with the Brazilian Portuguese translation of it, I can just quickly add that in :)

As for the cycles, it's probably because the cycle name is customizable when you press the edit button. I'm guessing that the localization only applies to the first launch of Loop, then the names are kept as-is.

**Comment by MrKai77** [comment]
Actually, some other translators found more missing strings. Please translate the remaining strings in this file:
[pt-BR.xcloc.zip](https://github.com/user-attachments/files/15935799/pt-BR.xcloc.zip)
Apologies for not noticing these earlier!

**Comment by willianba** [comment]
[pt-BR.xcloc.zip](https://github.com/user-attachments/files/15937120/pt-BR.xcloc.zip)

there it is

**Comment by MrKai77** [comment]
Thanks!

**Comment by MrKai77** [comment]
Hey @willianba! I'm currently making a Discord server for Loop, and I think that it will be an ideal place to let you know when new strings are added to Loop that need to be localized. Here's an invite: https://discord.gg/EZgFSZYY

If you don't have Discord, just let me know, that's fine too :)
