### ISSUE TITLE
🐛 Hyperkey conflict

### ISSUE THREAD

**Issue by njthebaud** [MrKai77/Loop#314]
### Bug Description

Loop is triggered whenever I use the hyperkey, no matter what single or combination of left side modifiers I use.

### Steps To Reproduce

1. Use the app hyperkey to configure caps lock to ^⌥⌘⇧
2. Set loop to use any left side modifiers
3. Trigger caps lock (i.e. ^⌥⌘⇧+V)

### Expected Behavior

Loop should not trigger when all modifiers are pressed even though it's set to use only two modifiers.

### Actual Behavior

Loop triggers when I press hyperkey even though I set loop to trigger only when ^+⌥ are pressed. 

### MacOS Version

Sonoma 14.4.1 (23E224)

### Loop Version

Version 1.0.0-beta.15 (817)

### Additional Context

I use the app hyperkey to have caps lock trigger the modifiers ^⌥⌘⇧, which I use as a shortcut for something like bringing up my clipboard manager on Raycast (hyperkey+V). I want the left ^+⌥ to be set for Loop, but when I do and I try to use hyperkey+V it triggers Loop. It seems this issue has been raised before (#261, #102, #74), and though they were ostensibly solved, I seem to be having the same problem. Also, it doesn't seem to be hyperkey since I was able to replicate the issue by holding down all the left side modifiers, as opposed to caps lock, plus "V" and Loop still gets triggered and conflicts with the clipboard manager launching.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
When Loop detects something like a hyperkey, it automatically decides to use a different mechanism to detect keys, and I believe that this is the likely cause of this problem. I will look into this!

**Comment by MrKai77** [comment]
When Loop detects something like a hyperkey, it automatically decides to use a different mechanism to detect keys, and I believe that this is the likely cause of this problem. I will look into this!

**Comment by y-u-s-u-f** [comment]
@MrKai77 Any update? This is the one thing that I really don't like about Loop and I would love for it to be fixed ASAP.

**Comment by MrKai77** [comment]
@y-u-s-u-f no updates yet :(

I've been very busy this past month, and I've actually wanted to release the next version of loop (with the redesigned settings) earlier too.

But this issue is definitely on my high-priority list, so I hope to fix it by the next release :)

**Comment by MrKai77** [comment]
Alright... I tried working on it :)

There's probably still a lot I need to fix, but please try this build!
[Loop.zip](https://github.com/MrKai77/Loop/files/15396583/Loop.zip)

**Comment by MrKai77** [comment]
Tried making it more reliable, try this build :D
[Loop.zip](https://github.com/MrKai77/Loop/files/15397522/Loop.zip)

**Comment by y-u-s-u-f** [comment]
thanks for the quick fix! i'll test this out in around a week (i'm
travelling right now).


btw, i had a dream yesterday night that you fixed this bug and released a
new version with the only release note being the fix of this bug 🤣 it was
version 1.0.0-beta.19 or something like that lmaooo

**Comment by MrKai77** [comment]
@y-u-s-u-f LOL.. That's actually really funny 🤣
