### ISSUE TITLE
double-click the window title bar to maximize

### ISSUE THREAD

**Issue by n0rv1n** [MrKai77/Loop#316]
### Feature Request Description

can I double-click the window title bar to maximize current window?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Hello! Thanks for the feature request!
Let me know if I'm wrong, but this seems to be a built-in feature to MacOS?  I am already able to do it without Loop running.
