### ISSUE TITLE
✨ Window Snapping is too sensitive

### ISSUE THREAD

**Issue by ghost** [MrKai77/Loop#317]
### Feature Request Description

The window snapping is too sensitive and is very easy to trigger when dragging and dropping the window close to the screen edge. I think a response delay can be added to this function.Or set the decision area of the function to the most edge of the screen instead of the near the edge of the screen.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
I agree on the fact that window snapping is too sensitive. 

> Or set the decision area of the function to the most edge of the screen instead of the near the edge of the screen.

I would actually prefer doing this, as it is simpler, and would be less complicated to the end-user. I will look into this!
