### ISSUE TITLE
✨ Secondary Functions for radial menu

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#318]
### Feature Request Description

so i wanted to suggest to have like different types of actions mapped to a new radial loop(secondary loop) which has a different trigger shortcut [loop trigger key + ⌃ for example] that we can add custom actions to, such that moving the windows to different sections(top, left, bottom, right) while preserving size or any other preferred actions

### Final Checks

- [X] My issue title is descriptive
- [x] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Duplicate of #108
