### ISSUE TITLE
🌐 Localization: Simplified Chinese

### ISSUE THREAD

**Issue by WYJ053X** [MrKai77/Loop#319]
### Feature Request Description

Hello author, I can help translate this software.
I am a user from China.
I can help you translate it into Simplified Chinese.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thank you so much for the offer!! But that was added in PR #303 :)
I'll make sure to reach out if there's anything else I need translated!

**Comment by NullTar** [comment]
Hi, Is there any progress on the current work? Can I help with work

**Comment by MrKai77** [comment]
Thanks for bringing this to my attention! Because of Loop's new settings window, I will definitely require a lot to be re-translated. There's still one or two more parts I need to make, then I will send a translation file over :)

**Comment by dufu1991** [comment]
I think we should store all the texts that need to be translated in a separate folder, so that you can modify the corresponding texts. This is the fastest way to complete the internationalization process. When there are changes in English documents, you can modify the corresponding language based on the changes.

**Comment by MrKai77** [comment]
Yes, the localization process will be done through a `Localizable.xcstrings` file. All that will need to be done is a Simplified Chinese translation file to be sent online, translated, then sent back. Then, I will be able to import it into a central `Localizable.xcstrings` file within Loop :)

I will be sending out that file very soon :)

**Comment by MrKai77** [comment]
Here's the translation file! You can open it in Xcode, and all you should need to do is fill in the blanks :)
[Loop Localizations - Simplified Chinese.zip](https://github.com/user-attachments/files/15905938/Loop.Localizations.-.Simplified.Chinese.zip)

**Comment by KrLite** [comment]
> Here's the translation file! You can open it in Xcode, and all you should need to do is fill in the blanks :) [Loop Localizations - Simplified Chinese.zip](https://github.com/user-attachments/files/15905938/Loop.Localizations.-.Simplified.Chinese.zip)

@MrKai77 I've done the translations! Is it ok to just drop it here?

The file:

[Loop Localizations - Simplified Chinese (Translated).zip](https://github.com/user-attachments/files/15913213/Loop.Localizations.-.Simplified.Chinese.Translated.zip)

**Comment by MrKai77** [comment]
Thanks @KrLite, I really appreciate it!! I just realized that I had 5 missing strings in the previous file I sent, can you translate those too? This file should already contain your current changes too :)
[zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15915631/zh-Hans.xcloc.zip)

**Comment by KrLite** [comment]
> Thanks @KrLite, I really appreciate it!! I just realized that I had 5 missing strings in the previous file I sent, can you translate those too? This file should already contain your current changes too :) [zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15915631/zh-Hans.xcloc.zip)

Sure! Here's the updated one.
[zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15915930/zh-Hans.xcloc.zip)

**Comment by MrKai77** [comment]
This is amazing!! Thank you so much!

**Comment by MrKai77** [comment]
@KrLite my bad, I forgot one! This one is moreso for future-proofing, but can you translate: "Include development versions"?
You can just reply below :)

**Comment by KrLite** [comment]
> @KrLite my bad, I forgot one! This one is moreso for future-proofing, but can you translate: "Include development versions"? You can just reply below :)

That would be `包含开发版本`, and if a period is needed, use `。`.

**Comment by KrLite** [comment]
I see another commented line above: `Automatically check for updates`. In case you need the translation, it is `自动检查更新`.

**Comment by MrKai77** [comment]
Thanks!! Loop now uses a custom updater, so I haven't implemented that functionality yet, but I'll keep that in mind in case I do :D

**Comment by KrLite** [comment]
@MrKai77 Some updates (for now):

| Key | New Translation |
|:--|:--|
| `Accessibility Request: Content` | `请授予权限以允许调整窗口大小。` |
| `%@ places windows slightly above the absolute center, which can be found more ergonomic.` | `%@将窗口放置在稍高于屏幕中心的位置，使其更加人性化。` |
| `Cursor` | `光标` |

**Comment by MrKai77** [comment]
@KrLite thanks, will update them!

**Comment by KrLite** [comment]
Here're some more updates, as I'm finishing my review:

| Key | New Translation |
|:--|:--|
| `Size increment` | `尺寸增量` |
| `Icon Unlock Message: Loop Master` | `5000次环绕达成！这个宇宙见证了又一位Loop大师的诞生！享受你应得的奖励吧：一个全新设计的纪念图标！` |
| `Suggest new icon` | `建议新图标` |
| `The Force is strong with this version!` | `此版本的原力很强大！` |
| `Use screen with cursor` | `使用光标所在的屏幕` |
| `Window Direction/Name: Grow Bottom` | `扩张底部` |
| `Window Direction/Name: Grow Top` | `扩张顶部` |
| `Window Direction/Name: Grow Left` | `扩张左侧` |
| `Window Direction/Name: Grow Right` | `扩张右侧` |
| `Window Direction/Name: Larger` | `扩大一点` |
| `Window Direction/Name: Smaller` | `缩小一点` |

**Comment by MrKai77** [comment]
Thanks! Just updated it in-code right now :)

**Comment by MrKai77** [comment]
@KrLite, looks like I missed the string "Contributors on GitHub":
<img width="385" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/1c95aa9b-5352-46cd-91c2-821cf14f2a97">
Can you translate that to Chinese (Simplified) and Chinese (Hong Kong) too, just a reply to this message will be alright :)

**Comment by MrKai77** [comment]
Actually, 5 more strings were found. Can you translate the remaining strings in this file:
[zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15935793/zh-Hans.xcloc.zip)

I'm sorry for not finding these earlier.

**Comment by KrLite** [comment]
> Actually, 5 more strings were found. Can you translate the remaining strings in this file: [zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15935793/zh-Hans.xcloc.zip)
> 
> I'm sorry for not finding these earlier.


OK!

[zh-Hans.xcloc.zip](https://github.com/user-attachments/files/15935800/zh-Hans.xcloc.zip)

And for Chinese (Hong Kong), almost the same:

| Key | Translation |
|:--|:--|
| `Contributors on GitHub` | `GitHub上的貢獻者` |
| `Initial Size` | `初始大小` |
| `Size` | `大小` |
| `Preserve Size` | `保持大小` |
| `Position` | `位置` |

**Comment by MrKai77** [comment]
Thank you!!

**Comment by MrKai77** [comment]
Hey @KrLite! I'm currently making a Discord server for Loop, and I think that it will be an ideal place to let you know when new strings are added to Loop that need to be localized. Here's an invite: https://discord.gg/EZgFSZYY

If you don't have Discord, just let me know, that's fine too :)
