### ISSUE TITLE
✨ Please notarize the app

### ISSUE THREAD

**Issue by nevotheless** [MrKai77/Loop#323]
### Feature Request Description

Can't launch the app without circumvent security features. I would like to launch the app without having to create an exception.

### Screenshots

<img width="651" alt="Bildschirmfoto 2024-04-10 um 17 48 26" src="https://github.com/MrKai77/Loop/assets/779797/fab17edb-7344-4338-90c4-a91ba579414e">

<img width="306" alt="Bildschirmfoto 2024-04-10 um 17 48 42" src="https://github.com/MrKai77/Loop/assets/779797/c1b9baff-10d3-4370-9df0-447c45f68039">

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Actually, notarization requires a paid Apple Developer account, which I do not have. This means that I am unable to notarize the app at the moment. However, I do plan to get one in the near future, at which point Loop will be notarized :D
