### ISSUE TITLE
✨ Globally close preview, Window occupied

### ISSUE THREAD

**Issue by simonmz20** [MrKai77/Loop#326]
### Feature Request Description

Loop is the the best window manager I used. 
there are some advise about this project
1. when I trun off the preview → appearance → show preview when looping, and I drag the window to left or right, the preview window still appeared, if I use the radial menu (middle-click), it did  not appear.  
2. when I turn off the preview → appearance → show preview when looping, When I use radial menu to tile the Microsoft Word window on the right side of the screen, the Microsoft Word window will exceed half of the screen and occupy about two-thirds of the screen width.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thanks!
1. Yup, that does seem like a bug
2. So it works perfectly when the preview window is enabled? A screen recording would be appreciated :D

**Comment by simonmz20** [comment]
Uploading iShot_2024-04-17_09.56.52.mp4…

**Comment by simonmz20** [comment]
[screen recording](https://www.simonmz.cn:888/52.mp4)

the window preview still display after I had turn off  the show preview when looping in  preference
thanks for your replay

**Comment by MrKai77** [comment]
Hmm.. does it work better when window animations are disabled?

**Comment by simonmz20** [comment]
it looks laggy after turn on the preview
and the animation speed option does not  seem to be working when i drag the window or use radial menu
<img width="434" alt="image" src="https://github.com/MrKai77/Loop/assets/122550177/c4a6e0a4-69d7-44d3-9b0d-071b9f00e2c8">

**Comment by MrKai77** [comment]
Interesting, do you have more than 1 monitor connected?

**Comment by MrKai77** [comment]
Also, since 1 and 2 seem to be separate issues, please open a new issue for 2.

**Comment by MrKai77** [comment]
As for 1, I have just fixed it, and will be merging it now :)
