### ISSUE TITLE
🌐 Localization: Chinese (Hong Kong)

### ISSUE THREAD

**Issue by zXiaoyuLuo** [MrKai77/Loop#327]
### Feature Request Description

As a new fish on github, i donot know how to pull my translation i have translate it on my location.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Awesome! I will let know when I have a translation file ready! For the time being, would you be able to install Xcode from the App Store?

---
Link: https://github.com/MrKai77/Loop/pull/303#issuecomment-2058156603

**Comment by zXiaoyuLuo** [comment]
moment please, I have made the traditional-chinese translation, and pulled my translation by github desktop. Is something wrong i ignore?

**Comment by MrKai77** [comment]
Perhaps I misunderstood. Can you send a screenshot of this traditional-chinese translation?

**Comment by zXiaoyuLuo** [comment]
it looks like it, it is differ chinese simplied
<img width="1512" alt="image" src="https://github.com/MrKai77/Loop/assets/128496390/497e90aa-6811-450d-a11f-867c76110104">

**Comment by MrKai77** [comment]
Oh perfect! In Xcode, would yo be able to do `Product -> Export localizations` and send me the localization file for "Chinese (Hong Kong)"?

**Comment by zXiaoyuLuo** [comment]
I have do that and now it shows successful, did i do right?
<img width="1512" alt="image" src="https://github.com/MrKai77/Loop/assets/128496390/389598bb-c011-4f5c-8772-ae23b3744d02">

**Comment by MrKai77** [comment]
Hopefully! It should have prompted you for a location to save the localization file in. Can you find that file, and send it here?

**Comment by zXiaoyuLuo** [comment]
Yep, I have found the file, and how could I do now, Should I send this file to you now?

**Comment by MrKai77** [comment]
Yes!

**Comment by zXiaoyuLuo** [comment]
Then please give me an approach so that I could send the profile to you.发自我的 iPhone在 2024年4月17日，21:59，Kai Azim ***@***.***> 写道：﻿
Yes!

**Comment by MrKai77** [comment]
You should be able to drag the localization file into here (GitHub), and simply send it :)

**Comment by zXiaoyuLuo** [comment]
[zh-HK.xcloc.zip](https://github.com/MrKai77/Loop/files/15022974/zh-HK.xcloc.zip)
Did i do right?

**Comment by MrKai77** [comment]
Yes, that is perfect :)

I am currently remaking the settings window, so I may ask you to translate a bit more in the future :)

**Comment by MrKai77** [comment]
@zXiaoyuLuo Can you retranslate? Basically everything has been re-formatted, but you should be able to transfer most strings from your first version :)

Open this file with Xcode:
[Loop Localizations - Chinese (Hong Kong).zip](https://github.com/user-attachments/files/15905968/Loop.Localizations.-.Chinese.Hong.Kong.zip)

**Comment by KrLite** [comment]
I have it translated. Most of the translations are migrated from the old one provided by @zXiaoyuLuo with some slight modifications to match the formulations in Simplified Chinese localization, while others are newly translated.
[zh-HK.xcloc.zip](https://github.com/user-attachments/files/15921702/zh-HK.xcloc.zip)

**Comment by MrKai77** [comment]
Thanks again @KrLite! Can you translate these as well:
<img width="562" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/619590f7-9495-4bf6-aafd-48ca4c5bed78">

**Comment by KrLite** [comment]
> Thanks again @KrLite! Can you translate these as well: <img alt="image" width="562" src="https://private-user-images.githubusercontent.com/68963405/341616692-619590f7-9495-4bf6-aafd-48ca4c5bed78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Mzc3MzgsIm5iZiI6MTcxODkzNzQzOCwicGF0aCI6Ii82ODk2MzQwNS8zNDE2MTY2OTItNjE5NTkwZjctOTQ5NS00YmY2LWFhZmQtNDhjYTRjNWJlZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAyMzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzN2IzY2IxOTlkZThjOGM2NjEyOTY2YjFjMjRiZmE4NTU0ZTA3NzdlZjJhNWZkMGQzNGMzMWUzOWNjMTZhNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mVHe7PyWbhA55GWMM0f0-x8ENLjR9gwqBEkAn9rhTaE">

Sure:

| Key | Translation |
|:--|:--|
| `Remove` | `移除` |
| `Red` | `紅色` |
| `Green` | `綠色` |
| `Blue` | `藍色` |
| `Add` | `添加` |

**Comment by MrKai77** [comment]
Thank you very much :D

**Comment by MrKai77** [comment]
Hey @KrLite! Some more strings were found, please translate this file:
[zh-HK.xcloc.zip](https://github.com/user-attachments/files/15935795/zh-HK.xcloc.zip)

**Comment by KrLite** [comment]
> Hey @KrLite! Some more strings were found, please translate this file: [zh-HK.xcloc.zip](https://github.com/user-attachments/files/15935795/zh-HK.xcloc.zip)

Done now.

[zh-HK.xcloc.zip](https://github.com/user-attachments/files/15935822/zh-HK.xcloc.zip)

**Comment by zXiaoyuLuo** [comment]
OK i will do that and sent you in another account.
