### ISSUE TITLE
✨ window restore

### ISSUE THREAD

**Issue by tony-swg** [MrKai77/Loop#338]
### Feature Request Description

Thank you for developing the application, I would like to ask how can I restore the adjusted window to the original window size and position after using loop for window adjustment?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
You can do so like this in the keybinds tab :)
<img width="400" alt="49866" src="https://github.com/MrKai77/Loop/assets/68963405/225d3ba9-2248-45ab-b354-e9a6e0cdd40d">

On top of that, if you want the window to restore its size on drag, enable this in the first tab of the settings window:
<img width="400" alt="10012" src="https://github.com/MrKai77/Loop/assets/68963405/73393fd8-b87e-47cf-b06f-34282eb7f17f">

**Comment by tony-swg** [comment]
thanks ：）
