### ISSUE TITLE
1 more Keybinds option pls

### ISSUE THREAD

**Issue by Chaninf88** [MrKai77/Loop#346]
### Feature Request Description

for now, I can add horizontal thirds > horizontal center third into Keybinds, but can I also have horizontal center two third  pls

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
You can use custom keybinds to achieve this :)
<img width="301" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/083b4d71-8f8b-454d-8a1f-d4ae5cb1439a">
