### ISSUE TITLE
🐛 Loop stays open when `Caps Lock` is enabled

### ISSUE THREAD

**Issue by walnut-the-hacker** [MrKai77/Loop#35]
### Bug Description

Loop stays open when `Caps Lock` is enabled.

### Steps To Reproduce

1. Enable `Caps Lock`
2. Open Loop with trigger key
3. Select direction and release trigger key

### Expected Behavior

Loop should close when the trigger key is released

### Actual Behavior

Loop stays open

### MacOS Version

Sonoma 14.0 Beta

### Loop version

Version 1.0.0-beta.9 (337)

**Comment by MrKai77** [comment]
Thanks for reporting this bug! I can reproduce this as well. It seems like having Caps Lock enabled changes the `NSEvent.modifierFlags.rawValue` from `256` to something else on the keyUp event, so Loop can't detect when the key is released.

**Comment by MrKai77** [comment]
I fixed it! It seems like this bug also affected the new `Keycorder` introduced in #31, so I fixed that as well!
