### ISSUE TITLE
🐛 Window snapping won't work in secondary display screen

### ISSUE THREAD

**Issue by ClarkGeng996** [MrKai77/Loop#350]
### Bug Description

1. My secondary screen is above my macbook internal screen. Like the attachment.
![13891715412652_ pic](https://github.com/MrKai77/Loop/assets/73984994/9cafeb14-49de-41f8-a174-e725b9545f76)
2. In internal screen, window snapping works well.
3. If you snap the windows from internal screen to external screen edge without interruption, it also works well.
4. SO the bad case is if you sanp the windows already in external screen to its edge, it won't works.

### Steps To Reproduce

Sanp the windows already in external screen to its edge, the funtion of window snapping won't works.

### Expected Behavior

Obviously window snapping should work well in any displays.

### Actual Behavior

 SO the bad case is if you sanp the windows already in external screen to its edge, it won't works.

### MacOS Version

Sonoma 14.4.1 (23E224)

### Loop Version

Version 1.0.0-beta.15 (817)

### Additional Context

Thanks for your hardworking to building this brilliant software.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thanks for the report!
However, I am unable to reproduce that bug. Would you be able to send a quick screen recording of this bug if possible?

**Comment by ClarkGeng996** [comment]
No Problem.
Please see the attached file.

https://github.com/MrKai77/Loop/assets/73984994/75a7efd6-9e56-4423-ab08-3f511a432940

**Comment by MrKai77** [comment]
Alright, somehow I was just able to reproduce this issue! I will definitely try and fix this by the next update :)

**Comment by ClarkGeng996** [comment]
So great news! Thanks for your hard working!  Looking forward to next update and checking update everyday.
Loop is a REAL macOS style window management App. 
Excited.

**Comment by MrKai77** [comment]
Try this :)
[Loop.zip](https://github.com/MrKai77/Loop/files/15425090/Loop.zip)

Turns out that Loop wasn't correctly calculating mouse coordinates on external screens when window snapping :P

**Comment by ClarkGeng996** [comment]
Hi Mrkai77, thanks for your new version.
BTW. It seems you changed trigger condition for window snapping？Only if I drop window to the very top of my screen(just same as magnet) instead of at the beginning of touching menu bar.
I think the original method is better for user.

**Comment by MrKai77** [comment]
That change was made by #212. I will look into it again, since I do find that it does become a little hard to snap windows to the top when two screens are stacked vertically too :)
