### ISSUE TITLE
🐞 Menu bar icon overlapping with another app's icon

### ISSUE THREAD

**Issue by OutShining** [MrKai77/Loop#351]
### Bug Description

When I am using a different space number between menu bar items, the loop icon just overlaps with another app's icon.
I have changed the space between menu bar items according to this blog. [https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch](https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch)

![image](https://github.com/MrKai77/Loop/assets/73104323/5ffbbd66-c553-43f6-8d8c-5cca175e9c85)

### Steps To Reproduce

type these two command using terminal:
`defaults -currentHost write -globalDomain NSStatusItemSelectionPadding -int 5`
`defaults -currentHost write -globalDomain NSStatusItemSpacing -int 10`

and re-login to your mac

### Expected Behavior

loop icon just overlaps with another app's icon.

### Actual Behavior

loop icon just overlaps with another app's icon.

### MacOS Version

14.4.1

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Interesting.. Never seen this before, will look into it!

**Comment by MrKai77** [comment]
Latest prerelease should fix this!
