### ISSUE TITLE
Would it be possible to add a centre two-thirds option

### ISSUE THREAD

**Issue by ghoetker** [MrKai77/Loop#356]
### Feature Request Description

On my display, a centre 2/3 window is often exactly the right size.  Loop can do right and left 2/3rds. Any possibility of extending same to centre? (Ideally, by keyboard and window snapping). Thanks for considering.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
You can use custom window actions and create these yourself :)
<img width="303" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/720850d0-6e8d-465c-a159-e15dc2df67ad">
