### ISSUE TITLE
🐛 Loop does not work by default with MacOS using the touchpad

### ISSUE THREAD

**Issue by fdebbabi** [MrKai77/Loop#358]
### Bug Description

When pressing the designated hotkey (globe) to trigger the radial menu, the radial menu is shown, but moving the touchpad to control the windows place does not do anything.

Does loop app only work with the mouse? or is it expected to work also with the touchpad?

### Steps To Reproduce

Place yourself in a normal finder window, click the hotkey, move the touchpad to organize windows.

### Expected Behavior

I expected after pressing the hotkey, to be able to use the macbook touchpad to control the windows organizations.

### Actual Behavior

When clicking the hotkey, the radial menu shows and it stays there while mainting the hotkey clicked, but moving the cursor with the touchpad does not do anything.

### MacOS Version

Sonoma 14.5

### Loop Version

Version 1.0.0-beta.15 (817)

### Additional Context

I have a Macbook Air M2 15"

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
That's really weird, I exclusively use Loop with a trackpad on my side!

Would you be able to send a video? 

Loop currently calculates the window action based on the cursor location, so it doesn't make sense to me that the peripheral used to move it would change the outcome.

**Comment by fdebbabi** [comment]
Here is the video (I uploaded it on google drive): https://drive.google.com/file/d/1la-fHHcgGr-J1pQevi__p2QQBbjy5FD5/view?usp=sharing

It looks like maybe it does not have access to reading the cursor location or something.

Here it looks like it has access to the computer: 
<img width="715" alt="Screenshot 2024-05-21 at 13 18 01" src="https://github.com/MrKai77/Loop/assets/94532372/9e30c9bd-ba98-42bb-8328-dd10f945f8c4">

Here also it has access to screen recording: 
<img width="715" alt="Screenshot 2024-05-21 at 13 35 19" src="https://github.com/MrKai77/Loop/assets/94532372/fcb83c55-accb-4f46-9739-39fa9b9d61c5">



For your information, moving the windows are working fine using the keyboard shortcuts (for example: hotkey + left arrow will move properly the window with the smooth animation and all)

**Comment by MrKai77** [comment]
Hmm.. do you have a multi-monitor setup? It's possible that Loop could be miscalculating the cursor position.

**Comment by fdebbabi** [comment]
no, I have only the Macbook Monitor, I did the manual installation for your information, do you think it might work better with homebrew installation method?

**Comment by MrKai77** [comment]
They both essentially do the same thing, but it's worth a try! Maybe it might fix something that's currently broken/missing?

Another option could be to boot into safe mode, and see if Loop works from there :)

**Comment by fdebbabi** [comment]
I tried both of them but still same issue (very weird).

**Comment by MrKai77** [comment]
Hmm alright.
Would you be able to try [this](https://github.com/MrKai77/Loop/files/15409613/Loop.zip) build? Maybe the latest changes will fix it?

**Comment by MrKai77** [comment]
Any updates on this?

**Comment by fdebbabi** [comment]
Same issue, no problem, I am already very happy with it with shortcuts (It is wonderful) you can close the issue.

**Comment by MrKai77** [comment]
Oh alright… but if anyone else has this bug, please comment below! Otherwise, I will close this issue.
