### ISSUE TITLE
🐛 Loop immediately crashes when Next + Previous screen in a Cycle is triggered

### ISSUE THREAD

**Issue by akincan-kilic** [MrKai77/Loop#363]
### Bug Description

When a Cycle is created with 2 Screen Switching components inside (Next and Previous), and that shortcut is triggered Loop will crash, leak memory.

### Steps To Reproduce

1. Open **Loop** settings
2. Go to keybindings
3. Click `+` -> `More` -> `Cycle`
4. Click to edit the `Cycle`
5. Add Screen Switching -> `Next Screen`
6. Add Screen Switching -> `Previous Screen`
7. Name the Cycle "_Screen Switching_" and save it.
8. Assign any keyboard shortcut to it (Mine is &#8997; + &#8963; + &#8679; + <kbd>Space</kbd>)
9. Try the assigned keyboard shortcut.

### Expected Behavior

Loop will show a preview of the window appearing on my other screen, and after repeating the shortcut make it appear on my first screen. Thus cycling between my two main monitors.

### Actual Behavior

Loop immediately crashes, leaving a hollow circle that is fixed on screen. Not only Loop will become unresponsive but it will start taking up more and more memory as time passes, reaching to infinity before killing itself.

### Screenshots

# The Hollow Circle after crash

![SCR-20240526-eldt](https://github.com/MrKai77/Loop/assets/65862487/7ba77166-c72e-4996-ae16-c079b9b5905d)

# The Cycle details

![SCR-20240526-emcl](https://github.com/MrKai77/Loop/assets/65862487/e6a2dc78-1926-4b4c-b1e8-db81cb7db89e)

# The Cycle in the keybinds menu

<img width="226" alt="SCR-20240526-emec" src="https://github.com/MrKai77/Loop/assets/65862487/b7d32977-0e24-4c86-8dca-6f65edd391a6">

# My Loop Settings

## General Settings

<img width="281" alt="SCR-20240526-emjv" src="https://github.com/MrKai77/Loop/assets/65862487/5a80b248-a3b5-41fe-a2f9-12a11e285596">

## More Settings

<img width="281" alt="SCR-20240526-emhc" src="https://github.com/MrKai77/Loop/assets/65862487/390d0930-0bec-48e6-9ca2-1dea5776ce90">

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0-beta.15 (817)

### Additional Context

I have a **Macbook Pro M1 Pro 16"** laptop as my secondary display and a main display **MSI Optix G32CQ4 31.5"** running at 2560x1440 resolution and 120HZ with [BetterDisplay](https://github.com/waydabber/BetterDisplay) application running to scale it to HiDPI.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Yes, actually, when a screen switching action is added into a cycling window action, it will also automatically advance onto the next action (it assumes that the next action is a window resize). You can see this in action in the built-in actions in Loop. What is happening in your case is that it is looping through the cycling actions infinitely 😓

 I would recommend adding a "buffer" non-screen-switching action in between them for now, but I will definitely try and fix this by the next release!
