### ISSUE TITLE
🐛 Version 1.0.0-beta.15 (868) just stops working sometimes

### ISSUE THREAD

**Issue by andrwmai** [MrKai77/Loop#364]
### Bug Description

I'm using this build that fixes a bug with 'Animate windows being resized' when using MacBook + external screens, and I notice most of the time when waking up from sleep, Loop just stops working. The trigger keys can’t get the radial menu to show up, and snapping windows also doesn’t work. I have to quit the app and relaunch it to start using again.

### Steps To Reproduce

1. Sleep the Mac
2. Wake Mac up
3. Start Looping and notice it doesn’t work

### Expected Behavior

It should Loop like usual

### Actual Behavior

The app just doesn’t work, even though I can still open its settings

### MacOS Version

Sonoma 14.5

### Loop Version

Version 1.0.0-beta.15 (868)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by andrwmai** [comment]
After a short while using this version, it resolves the issue but I think it's not very stable.

**Comment by MrKai77** [comment]
Alright, can you try this build to see if it's any better?
[Loop.zip](https://github.com/MrKai77/Loop/files/15450383/Loop.zip)

**Comment by andrwmai** [comment]
Thank you. Just downloaded. Will test it out and let you know.

**Comment by MrKai77** [comment]
Any updates?

**Comment by andrwmai** [comment]
Hey @MrKai77 yea sorry I forgot to keep you updated. The app works fine now, it's just that now it remembers the last spot it was in and the next time I loop it automatically goes to the next spot instead of reset. Could you add an option to disable that?

**Comment by MrKai77** [comment]
Alright, I can look into that :) 

I will also now close this issue now that it has been resolved!
