### ISSUE TITLE
Add quarters, thirds and center half. Allow selection of snaps you want and don't possibly.

### ISSUE THREAD

**Issue by vbcoach** [MrKai77/Loop#365]
### Feature Request Description

I have a wide monitor. Half left or right and quarter screen are way too big. Would be great to have quarter left or right, half or third center... etc. Raycast windows management extension has this functionality, but your interface is way nicer. Perhaps ability to select the screen sizes you want so it's not so jumpy as you drag.

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/45717494/4c7b7822-69e3-4f05-85f3-091657926242)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Alright, so as for the having fourths, you can add custom window actions here:
<img width="310" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/c21f7912-8797-43d4-9073-60f999c51c3b">
However, these actions require keybinds. You can't access these from the radial menu yet, but soon will be with #107 :D

**Comment by vbcoach** [comment]
Ahh,

I didn’t see that in the documentation and I missed the little + icon.
First glance, I would like to be able to either enter a numeric percentage, or have 5% increments in the sliders but this is very cool.

I’ll play with it and donate. Thanks for building this.

Marc Swindle

**Comment by MrKai77** [comment]
By dragging the slider by a bit, you can input values rather than approximate the desired size:
https://github.com/MrKai77/Loop/assets/68963405/f739a63f-6eb7-4582-ad4c-a45bb3ee597a

Thank you so much!

**Comment by vbcoach** [comment]
OK, very cool.


Marc Swindle

**Comment by MrKai77** [comment]
Will close 🙂 
But please feel free to let me know if you have any other ideas!

**Comment by vbcoach** [comment]
Will do. I’ve been using it a little but will do more next week.

Marc Swindle
