### ISSUE TITLE
🐛 Maximizing/adjusting size in different screen

### ISSUE THREAD

**Issue by hoelderlin** [MrKai77/Loop#368]
### Bug Description

When I try to maximize or adjust the window size in the laptop screen using a keyboard shortcut the window always maximizes or adjust in the external display.

### Steps To Reproduce

1. perform keyboard shortcut in laptop screen
2. it goes to the external screen display

### Expected Behavior

to maximize/adjust window size in the same screen where the window is.

### Actual Behavior

maximizes or adjusts window size in external display.

### MacOS Version

Sonoma 14.5

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
This is likely because Loop currently resizes the window the cursor is present on. It is currently being resolved in #251 :)
