### ISSUE TITLE
🌐 Localization: German

### ISSUE THREAD

**Issue by Xtrwe2** [MrKai77/Loop#369]
### Feature Request Description

I would like to translate loop into German. :D 

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
That would be awesome!! I am currently reworking the settings window in #361 but once that's finalized, I will send a translation file over to you :D

**Comment by Xtrwe2** [comment]
Ok, I'll wait till then.

**Comment by MrKai77** [comment]
Here's the localization file for german:
[Loop Localizations - German.zip](https://github.com/user-attachments/files/15906037/Loop.Localizations.-.German.zip)

Open in Xcode to begin translating :)

**Comment by MrKai77** [comment]
Oops, here's an updated file:
[de.xcloc.zip](https://github.com/user-attachments/files/15935801/de.xcloc.zip)

**Comment by L1am-cd** [comment]
Hey, are there any updates on this?

**Comment by SenpaiHunters** [comment]
Hey, @L1am-cd, there does not seem to be any response from, @Xtrwe2, at this current time, If you'd like to take over the localisation process, please create a new issue.
