### ISSUE TITLE
✨ Automatic Tiling

### ISSUE THREAD

**Issue by 0xCUB3** [MrKai77/Loop#37]
### Feature Request Description

It would be cool to have an option to automatically tile windows, rather than only being able to do it with shortcuts.

### Additional Context

This is what yabai and amethyst do, if you would like some inspiration :)

**Comment by MrKai77** [comment]
Very interesting! I haven't used amethyst/yabai extensively, but I get the general idea of how it works. While this *would* require rewriting a lot of the window management code for Loop, I'm definitely interested in implementing this! As for now, I'll just research how it works in code etc.!

**Comment by MrKai77** [comment]
Here's an update: I don't think I'll be able to add automatic tiling to Loop anytime soon. While it certainly sounds cool to have, I don't think I'd be using it, meaning that an implementation that I make may be quite buggy. Furthermore, I never had originally intended Loop to be made for this type of functionality. I hope you understand this decision, and I'm open to considering other feature requests or improvements that may align better with Loop's core purpose :)

However, if anyone else is interested in making an automatic tiling window manager, I'd be more than happy to support them with everything I've learned from making Loop!
