### ISSUE TITLE
💄 Gap Between Slider And Picker In Colour Picker

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#377]
### Improvement Description:

slider and needs 2px gap

| Live | Figma |
| -- | -- |
| ![010676@2x.png](https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/d344ec0a-0e40-452d-ab97-5e84fe94119b/f38d41f0-16b4-4d40-8f31-dbb6547a2029?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy9kMzQ0ZWMwYS0wZTQwLTQ1MmQtYWI5Ny01ZTg0ZmU5NDExOWIvZjM4ZDQxZjAtMTZiNC00ZDQwLThmMzEtZGJiNjU0N2EyMDI5IiwiaWF0IjoxNzE3NzY2Nzg5LCJleHAiOjMzMjg4MzI2Nzg5fQ.XsRa9h6lO1t_9VvuChleqhjkgkIyEd_31sTVdSMx_rk "=180x") | <img src="https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/4f2e2d4e-b504-41ad-81ef-f97db18e5b16/bbdb0b40-e6aa-4b98-aba7-8676a579929e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy80ZjJlMmQ0ZS1iNTA0LTQxYWQtODFlZi1mOTdkYjE4ZTViMTYvYmJkYjBiNDAtZTZhYS00Yjk4LWFiYTctODY3NmE1Nzk5MjllIiwiaWF0IjoxNzE3NzY2Nzg5LCJleHAiOjMzMjg4MzI2Nzg5fQ.IwAtQ1vKjcmVM8dZXaO4gWslmurcwFZ1f7RdMnkcjfg " alt="010677@2x.png" width="1026" height="1750" /> |

### Why tho…?:

because i said so

**Comment by SenpaiHunters** [comment]
I'll fix this later (I won't this is for Kai)!

**Comment by MrKai77** [comment]
| Before |  |  |
| -- | -- | -- |
| After | ![image.png](https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/fa9317db-609d-4cdb-8de2-4fa55b2f154d/e3e4c4ab-c0a4-4c6d-897c-8628ae8b703a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy9mYTkzMTdkYi02MDlkLTRjZGItOGRlMi00ZmE1NWIyZjE1NGQvZTNlNGM0YWItYzBhNC00YzZkLTg5N2MtODYyOGFlOGI3MDNhIiwiaWF0IjoxNzE3ODA5MzcwLCJleHAiOjMzMjg4MzY5MzcwfQ.5PsFER0rGkJD0Kjahx2s6TmmPT-eNyAw79Gjhq9EE08 "=206x") | ![95744.png](https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/7cfabdae-1ff8-4a39-82f2-3bf22ec3033f/b6819680-e204-462f-9a27-3097d2efaebe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy83Y2ZhYmRhZS0xZmY4LTRhMzktODJmMi0zYmYyMmVjMzAzM2YvYjY4MTk2ODAtZTIwNC00NjJmLTlhMjctMzA5N2QyZWZhZWJlIiwiaWF0IjoxNzE3ODA5MzcwLCJleHAiOjMzMjg4MzY5MzcwfQ.Sn8NU1FbGNDMOBcmrPnpgJAYouUvvnBxN_v9CLQlPDw "=355x") |

Easy fix!
