### ISSUE TITLE
✨ Ability to restore previous window size

### ISSUE THREAD

**Issue by walnut-the-hacker** [MrKai77/Loop#39]
### Feature Request Description

Would be nice if there was a way to restore the previous window size, maybe with a keybind like:
`trigger key` + `z`, which is similar to the system keybind `command` + `z`

**Comment by MrKai77** [comment]
Sounds cool! I can see this being pretty useful! 
Will try and put this in loop within the next few days!

**Comment by MrKai77** [comment]
Alright, here's a working build! It toggles between the current & last position of the window.

[Loop.zip](https://github.com/MrKai77/Loop/files/12697781/Loop.zip)

**Comment by walnut-the-hacker** [comment]
Works well! Thank you!!
