### ISSUE TITLE
🐞 Settings page pops up after logging in every time

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#392]
### Bug Description

When you logout or restart the loop app's window opens even though there is no need for it to, initially i didn't give it much thought but overtime it is irritating to close it everytime you login

### Steps To Reproduce

1. Restart and login

### Expected Behavior

Loop should work without opening the settings page

### Actual Behavior

The settings windows popup(out of focus as well)

### MacOS Version

Sequoia 15 Beta (24A5264n)

### Loop Version

1.0.0-beta.15 (817)

### Additional Context

Also it happened in sonoma too, so not a macos sided bug

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Can you still reproduce this on the latest release (1.0.0)?

**Comment by frieza213** [comment]
nope, looks like it's fixed, thanks!!! this update is nice not gonna lie

**Comment by MrKai77** [comment]
That's great to hear :D
