### ISSUE TITLE
✨ New Version

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#393]
### Feature Request Description

Hey i have been following the repo for quite a while and think that the features are enough for another refining QOL update, i really like this time's commits and feature implements🔥❤️

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by frieza213** [comment]
Plus its been like 2.5 months since the last update

**Comment by MrKai77** [comment]
Thank you so much!! The next update is indeed going to be a large update, and there are only a few things left that I do want to fix before releasing it! Stay tuned :)
