### ISSUE TITLE
💄 Adjust Finder Icon Alignment for Balanced Aesthetics

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#394]
### Improvement Description:

Can we move the finder icon more to the left, so the top and bottom distance looks the same as the right distance?

<img src="https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/0955512f-db1a-42b8-a1a5-c6ce1dc5c73b/4d0ce6f0-67b1-42e1-999c-f18f28391bf7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy8wOTU1NTEyZi1kYjFhLTQyYjgtYTFhNS1jNmNlMWRjNWM3M2IvNGQwY2U2ZjAtNjdiMS00MmUxLTk5OWMtZjE4ZjI4MzkxYmY3IiwiaWF0IjoxNzE4NDA2NDI0LCJleHAiOjMzMjg4OTY2NDI0fQ.wc8ZKfmQJ20K5hmOmQnSYrjnUSVJ7Lg8Ypj2VOoGXdo " alt="000147@2x.png" width="186" height="218" />

### Why tho…?:

Even spacing

**Comment by MrKai77** [comment]
Definitely, I can't unsee it now 😭

**Comment by MrKai77** [comment]
<img src="https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/0594f5f4-0c72-4e7c-88b7-51407672bc3f/d5ccfee6-2678-49ae-bda9-6fc1642f593a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy8wNTk0ZjVmNC0wYzcyLTRlN2MtODhiNy01MTQwNzY3MmJjM2YvZDVjY2ZlZTYtMjY3OC00OWFlLWJkYTktNmZjMTY0MmY1OTNhIiwiaWF0IjoxNzE4NDA2ODk3LCJleHAiOjMzMjg4OTY2ODk3fQ.EHATAtccDl8l1AJqf-YiXNoXf7NN0MaQZe07XlNmIiE " alt="image.png" width="382" height="69" />

Fixed! Also made the icon slightly more transparent to better reflect the Figma file

**Comment by JaceThings** [comment]
lov u <3
