### ISSUE TITLE
✨ Hardcode credits icons

### ISSUE THREAD

**Issue by MrKai77** [MrKai77/Loop#400]
### Feature Description:

Currently, icons are downloaded on demand, which is pretty much unneeded:

<img src="https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/abeba966-b950-4208-9790-f681f478ab83/cd20f7eb-0113-40ec-a466-53ea69b35750?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy9hYmViYTk2Ni1iOTUwLTQyMDgtOTc5MC1mNjgxZjQ3OGFiODMvY2QyMGY3ZWItMDExMy00MGVjLWE0NjYtNTNlYTY5YjM1NzUwIiwiaWF0IjoxNzE4NDEwOTg5LCJleHAiOjMzMjg4OTcwOTg5fQ.vIj5R486JJ-53DtYUWJonY1DSpLqDenILgykWm_jJ_Y " alt="image.png" width="612" height="948" />

(image credits to @jace)

It would be better to already have them saved to save internet connection too!

**Comment by JaceThings** [comment]
i request mine to be from [https://x.com/JaceThings](https://x.com/JaceThings), thank you
