### ISSUE TITLE
✨ Option to disable preview animations 

### ISSUE THREAD

**Issue by lakubuDavid** [MrKai77/Loop#402]
### Feature Request Description

I think it would be helpful to have the ability to turn off the preview animations when selecting window placement or size. Sometimes, the animation causes a slight delay even when I already know where I want my window to be,I still have to wait for the animation to complete.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by SenpaiHunters** [comment]
The animation can be turned off, this is to animate the windows to be moved, below it you should also see "Hide Loop until direction is chosen" this should disable Loops preview from showing until you've confirmed where the window will go. You can also totally disable the preview (see second image)

---

![Loop - June 06 2024 - 14 51 PM@2x](https://github.com/MrKai77/Loop/assets/103985728/d817f3e5-3e97-4dba-85f8-56312144b351)


![Loop - June 06 2024 - 14 54 PM@2x](https://github.com/MrKai77/Loop/assets/103985728/9727045a-9600-45de-a0ef-dfe3da55cc43)

**Comment by MrKai77** [comment]
Thanks @SenpaiHunters!

To add on - you can also completely disable animations with this setting in the General tab:
<img width="424" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/78eb15e8-72e9-4eb4-94e6-e0a4890f9ec9">

**Comment by SenpaiHunters** [comment]
> Thanks @SenpaiHunters!
> 
> To add on - you can also completely disable animations with this setting in the General tab: <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/68963405/340067988-78eb15e8-72e9-4eb4-94e6-e0a4890f9ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTk5MzksIm5iZiI6MTcxODUxOTYzOSwicGF0aCI6Ii82ODk2MzQwNS8zNDAwNjc5ODgtNzhlYjE1ZTgtNzJlOS00ZWI0LTk0ZTYtZTBhNDg5MGY5ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA2MzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NWMyYTg5YzFlYjFjZDM4ODBhOTg0ZDEzYWViZTdjOGEwODJlODU4YTZhNzYyZmVlNGZhMTJiZGNkZWVhYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vjFYFP7aptRmXCMgHwIyH5h7-gx3KHZXOpEL1v82Zrk">

Thank you for that one, i did semi forget about this as mine's always set to instant! 😂

**Comment by lakubuDavid** [comment]
Oh okay thanks @MrKai77 and @SenpaiHunters , I already had the animation speed set to instant,but I didn't realize I had to disable the preview also to make it instantaneous
