### ISSUE TITLE
✨ Setting UI revamp

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#404]
### Feature Request Description

I think you should make the setting UI more modern and add background blur and transparency, just like raycast it looks so much better than the loop's one and ofcourse this is not a priority but it would really add to the loop's design language with the blur

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
@AISLVE then you are going to LOVE the next update :D
This is the reason it has taken over 2 months, as I have been trying to perfect it:
<img width="1292" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/23290e26-0a79-42a4-8638-c971753440a9">

Hoping to release it super soon :)

**Comment by andrwmai** [comment]
I saw what Jace sent me. I'M EXCITED!!!!!!!!!!!!!!!!!
