### ISSUE TITLE
✨ Is Luminare no longer open source?

### ISSUE THREAD

**Issue by ChihGodlee** [MrKai77/Loop#406]
### Feature Request Description

The latest version of the source code cannot be built.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Hello @LIJHIH!
Luminare is the new framework used to make Loop's settings window, and its source will only be available to sponsors. However, if you have any interesting ideas to improve the settings window, feel free to let me know :D

EDIT: This is mainly to make Loop more profitable, as I have poured all my free time over the past few months into making it. It also makes use of a few private APIs, which took me a quite a while to figure out. I hope you understand - I can't afford to always work for free.
If you REALLY need access to Luminare and are not able to sponsor me, email me and we can sort that out :)

And for those who are currently sponsoring me - I don't have an automated system *yet* to give you access to Luminare, so contact me via email or a GitHub discussion and I will give you access!

…ANOTHER EDIT: Looks like Luminare being private may conflict with Loop’s GPLv3 license. I will look into this tomorrow!

**Comment by MrKai77** [comment]
Alright... Source is now available to the public :)
