### ISSUE TITLE
💄 Max Loop Counter Text

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#408]
### Improvement Description:

When your number of looks exceeds 999,999, the counter should say "I... uhh... I lost count"

### Why tho…?:

Funny

**Comment by SenpaiHunters** [comment]
"Bit loopy aren't we?"

**Comment by SenpaiHunters** [comment]
![ca1Bffo](https://github.com/MrKai77/Loop/assets/103985728/398ad4b5-f798-4c86-acea-7043f1e3cf95)
