### ISSUE TITLE
🐞 Snap recognition not working correct

### ISSUE THREAD

**Issue by baschte** [MrKai77/Loop#411]
### Bug Description

If i want to snap a window to fullscreen or to the side the snap indicator isnt working anymore. If i close and reopen Loop it works for several minutes. Dont know why its not working correct anymore. The old beta version works perfect before.

### Steps To Reproduce

1. Open Loop
2. Snap window to the top or to the side
3. Snapping indicator doesnt show up

### Expected Behavior

Window snapping with animation should run correct and on every time.

### Actual Behavior

Snapping doesnt work the whole time on my machine. Previous version works perfect here

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by frieza213** [comment]
yeah same here if i try snapping the window, nothing happens its almost as if i don't have have loop, keyboard shortcuts work fine though

**Comment by baschte** [comment]
Couldn't reproduce actual when it breaks

**Comment by CyberTimon** [comment]
I have the same issue. I really hope for a fix, the app otherwise is amazing!

**Comment by baschte** [comment]
Maybe it helps to say that i'm currently using two displays. Macbook one and a Studio Display.

**Comment by CyberTimon** [comment]
I'm just on my MacBook Pro 16" with no external monitors so I don't think that's the problem here.

**Comment by MrKai77** [comment]
Hello all, thanks for reporting! This seems like a pretty big problem, so it's on my high-priority list :)

Definitely will try and fix this asap

**Comment by CyberTimon** [comment]
Amazing, thank you!

**Comment by MrKai77** [comment]
Hey everyone! Try this development build, let me know if it works :)
[Loop.zip](https://github.com/user-attachments/files/15920904/Loop.zip)

**Comment by CyberTimon** [comment]
Will test it soon when I'm back home. Thank you!

**Comment by CyberTimon** [comment]
Btw, are you aware of the problem that when you move the window to e.g. the right the animation plays from the center? It looks a bit strange when the mouse is on the right and the animation plays (window pops up) from the center.

**Comment by baschte** [comment]
thank you @MrKai77 
give it a try right now and check if its working correct 👍

**Comment by MrKai77** [comment]
> Btw, are you aware of the problem that when you move the window to e.g. the right the animation plays from the center? It looks a bit strange when the mouse is on the right and the animation plays (window pops up) from the center.

This is intended behavior, are you suggesting that it comes from the radial menu? That's an interesting idea!

**Comment by CyberTimon** [comment]
> This is intended behavior, are you suggesting that it comes from the radial menu? That's an interesting idea!

In the radial menu you don't really notice that it's coming from the center, but if you use mouse window snapping it becomes much more noticeable (it should come from the side where the mouse is). So yes, it would be cool to have this as a feature, although I don't know how hard it is to implement.

**Comment by frieza213** [comment]
i know this isn't related but i don't think it should be another issue's topic, so the when you launch the app it has a blue highlight color on the icon which is not very aesthetic considering the design language and it looks even worse if your go to a different section

normal
![CleanShot 2024-06-21 at 12 00 12@2x](https://github.com/MrKai77/Loop/assets/121119257/b6ca6f23-a5d9-4497-a504-50406013c062)

after switching
![CleanShot 2024-06-21 at 12 02 30@2x](https://github.com/MrKai77/Loop/assets/121119257/d1a417a0-7845-4c84-9180-97aa37f1ef63)

**Comment by baschte** [comment]
@MrKai77 
So after testing your dev build it looks good. Snap is working fine for me now 👍 On multiple screens as well. Thank you!

**Comment by MrKai77** [comment]
@AISLVE That seems to be worth opening a new issue about :)

**Comment by MrKai77** [comment]
@AISLVE Nevermind, it seems like that is caused by this bug fix. Will fix it here :)

**Comment by frieza213** [comment]
(foreshadowing)😂

**Comment by MrKai77** [comment]
Looks like I was wrong 😂
It was caused by me tinkering with system settings...
<img width="454" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/fc2f2da6-d602-44fa-a8f9-c12446bb36bc">
Having this on seems to cause the bug. Anyways, this means that it **is** worth opening an issue for it.

**Comment by frieza213** [comment]
https://github.com/MrKai77/Loop/assets/121119257/6ab7df2a-aea7-4768-b714-72ba91b0b19d

**Comment by MrKai77** [comment]
Are you not able to reproduce the bug anymore? 🤔

**Comment by frieza213** [comment]
seems like it

**Comment by MrKai77** [comment]
Alright, that's really odd.. Do let me know if it ever happens again!
