### ISSUE TITLE
✨ Feature request: Please add hover to select the window

### ISSUE THREAD

**Issue by craigary** [MrKai77/Loop#412]
### Feature Request Description

Hi, it would be nice if we can select window (to be resized) when hovering it. This is super nice for organizing multiple windows without using mouse / trackpad to hover **and** click to select.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by JaceThings** [comment]
Does the "Resize window under cursor" toggle not achieve what you're explaining?
![000481@2x](https://github.com/MrKai77/Loop/assets/60551230/66f54520-2817-489e-aa13-475c9cc23534)

**Comment by MrKai77** [comment]
Would this be similar to #209?

**Comment by craigary** [comment]
@Soft-Bred @MrKai77 "Resize window under cursor" is exactly what I need! Thank y'all so much~
