### ISSUE TITLE
🐞 [Loop thinks it doesn't have accessibility permissions]

### ISSUE THREAD

**Issue by git-napkin** [MrKai77/Loop#414]
### Bug Description

When I updated to 1.0.0, It asked to have accessibility permissions again although it already has it, so i disabled it and re-enabled it, and it still asks. Loop doesn't work because it thinks it doesn't have accessibility permissions even though it does, tried quitting and re-opening and still doesn't work.

### Steps To Reproduce

1. [Update to 1.0.0]
2. [Open Loop and give it accessibility permissions]
3. [It keeps asking and doesn't work]

### Expected Behavior

Loop works just fine after giving it permissions.

### Actual Behavior

Loop doesn't appear to see the fact it has accessibility permissions and keeps asking after it gets it.

### Screenshots

<img width="1174" alt="Screenshot 2024-06-18 at 12 11 57 PM" src="https://github.com/MrKai77/Loop/assets/157659892/705ff7db-86e2-48c1-80d6-d884d73e811e">
<img width="500" alt="Screenshot 2024-06-18 at 12 12 17 PM" src="https://github.com/MrKai77/Loop/assets/157659892/38152478-909e-4b23-b98d-b2b0b20b1ee5">

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by dropalltables** [comment]
Try removing and adding loop in settings

**Comment by git-napkin** [comment]
> Try removing and adding loop in settings

As I explained, I already tried that and it didn't work.

**Comment by dropalltables** [comment]
I mean using the minus symbol, not just flipping a switch, you should remove loop from the list completely, and use the plus button to add the .app file again

**Comment by dropalltables** [comment]
If you have already tried this then use PearCleaner to uninstall and reinstall loop

**Comment by MrKai77** [comment]
This seems to be an issue with the latest version because I switched signing certificates.

Run this in Terminal:
```sh
tccutil reset Accessibility com.MrKai77.Loop
```

This will force-reset everything related to accessibility access from Loop.

**Comment by git-napkin** [comment]
Okay thanks, I'll try this.

> This seems to be an issue with the latest version because I switched signing certificates.
> 
> Run this in Terminal:
> 
> ```shell
> tccutil reset Accessibility com.MrKai77.Loop
> ```
> 
> This will force-reset everything related to accessibility access from Loop.

**Comment by cameronfairbairn** [comment]
I have this same issue. I tried the the tccutil reset but to no avail. I'm attempting to remove loop completely and reinstall now.

**Comment by darquill** [comment]
> This seems to be an issue with the latest version because I switched signing certificates.
> 
> Run this in Terminal:
> 
> ```shell
> tccutil reset Accessibility com.MrKai77.Loop
> ```
> 
> This will force-reset everything related to accessibility access from Loop.

Running this solved the issue for me (you'll need to re-enable the accessibility permission afterwards)

**Comment by cameronfairbairn** [comment]
<img width="849" alt="image" src="https://github.com/MrKai77/Loop/assets/13923520/d363d732-00b5-499e-ae23-3b255947e3e0">

I couldn't reinstall from homebrew - I got this error.

**Comment by cameronfairbairn** [comment]
A total remove and reinstall worked for me. I had originally installed via homebrew. When I tried to run the tccutil reset, loop was missing from the list after clicking accessibility access Request, so I wasn't able to add the required permissions. After I removed using homebrew I got the error in my previous screenshot, but I have downloaded the zip file and installed via that method and now it works. Loving the app btw

**Comment by MrKai77** [comment]
> <img alt="image" width="849" src="https://private-user-images.githubusercontent.com/13923520/340859726-d363d732-00b5-499e-ae23-3b255947e3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NTE4MzMsIm5iZiI6MTcxODc1MTUzMywicGF0aCI6Ii8xMzkyMzUyMC8zNDA4NTk3MjYtZDM2M2Q3MzItMDBiNS00OTllLWFlMjMtM2IyNTU5NDdlM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDIyNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNTUyOWYxNDU4MGZmMDQ3MjRlOGU0Y2YxMjEzZTI5OTQzMWNkNzVjOGE4NzJhNjQwMjgzN2ZkN2FhYWMyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iuRuGyHEEDvRqF52wz7nIVFZ2ZZxLzjb2JXNxC83vvo">
> I couldn't reinstall from homebrew - I got this error.

You have a typo - it's `mrkai77/cask/loop`, not "mrkair77/cask/Loop".
