### ISSUE TITLE
🐞 Accessibility Permissions not working on 1.0.0

### ISSUE THREAD

**Issue by McFlyssss** [MrKai77/Loop#418]
### Bug Description

First and foremost, thanks so much for such a nice piece of software. I love `loop` and I can not think of using a Mac in any other way since I installed it.

Since I have updated to 1.0.0(1030) every time I launch loop it's asking to grant Accessibility permissions
The toggle in the system preferences is already activated.

Since this seems not to be working, no resizing is working at all. No shortcuts not actions in the bar menu

### Steps To Reproduce

1. Launch loop
2. Get the `Loop Needs Accessibility Permissions` alert.
3. Tap OK and navigate to Accessibility permissions in the system preferences
4.  Disable / Enable
5. Kill lopp
6. Launch again

### Expected Behavior

Once the permission is granted the app does not ask again and can resize windows.

### Actual Behavior

App constantly asking for permissions. No resizing is working

### Screenshots

![Screenshot 2024-06-19 at 09 59 34](https://github.com/MrKai77/Loop/assets/5735738/2a10c742-e4ec-4f18-a8bf-2dab6dcf6365)
![Screenshot 2024-06-19 at 10 08 58](https://github.com/MrKai77/Loop/assets/5735738/d29c3321-79de-48d7-bba7-8a10753baa58)
![Screenshot 2024-06-19 at 10 10 05](https://github.com/MrKai77/Loop/assets/5735738/3eb7257e-31b3-45f7-bdff-eba0f4946d32)

### MacOS Version

13.5.2

### Loop Version

1.0.0(1030)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by jmo161** [comment]
I was having the same issue (on Sonoma 14.4.1) after updating Loop.  

I removed Loop from accessibility settings completely and restarted loop (interestingly, the popup for permissions didn't appear).  It (naturally) still didn't work at that point, but after manually adding Loop back into Accessibility permissions, it started working again.   

Now, after quitting/relaunching, it doesn't ask for permissions but does still work.  

The steps I took:

* Quit Loop
* Remove Loop from Settings -> Privacy & Security -> Accessibility using the `-` button
* Launch Loop (did not get Accessibility popup)
* Add Loop to Accessibility settings using the `+` button

I can't get Loop back into the broken state again to see if any of these steps are unnecessary, but I'm curious if it works for you too!

**Comment by JaceThings** [comment]
Yes this is an issue due to how macOS treats accessibility for different versions of applications, one must manually remove the application from the accessibility settings using the – sign and then add it again using the + sign

**Comment by rodolforfq** [comment]
Removing it from the Accessibility list did the trick for me. Didn't need to quit Loop.
- Remove Loop from Settings=>Privacy & Security=>Accessibility (highlight the existing Loop entry and click on the - button on the bottom.
- In the Loop window, go to Advanced and click on the "Request" button on the Permissions/Accessibility Access section
- Toggle the new Loop entry on Settings=>Privacy & Security=>Accessibility
- In the Loop window, the "Request" button should now be greyed out and a checkbox should be present indicating access has been granted.

Thanks for the new version. Looking great! 😄

**Comment by MrKai77** [comment]
Thanks @rodolforfq!
I'll be keeping this open as this seems like a common issue with the latest release.
In addition, here's a terminal command that will also resolve this: `tccutil reset Accessibility com.MrKai77.Loop` :)

**Comment by McFlyssss** [comment]
That just worked. Thank you all for your suggestions!

**Comment by whr3430633** [comment]
> Removing it from the Accessibility list did the trick for me. Didn't need to quit Loop.
> 
> * Remove Loop from Settings=>Privacy & Security=>Accessibility (highlight the existing Loop entry and click on the - button on the bottom.
> * In the Loop window, go to Advanced and click on the "Request" button on the Permissions/Accessibility Access section
> * Toggle the new Loop entry on Settings=>Privacy & Security=>Accessibility
> * In the Loop window, the "Request" button should now be greyed out and a checkbox should be present indicating access has been granted.
> 
> Thanks for the new version. Looking great! 😄

In my case, it's not working even though the "Request" button has already been greyed out.
Maybe I need to restore to the previous version.

**Comment by rodolforfq** [comment]
> In my case, it's not working even though the "Request" button has already been greyed out. Maybe I need to restore to the previous version.

I suggest checking your trigger key config. Any chance that was reset with the update?

**Comment by MrKai77** [comment]
@whr3430633 Did you try running the terminal command in my previous comment as well?

**Comment by BrandonSmith** [comment]
I too faced the "Loop Needs Accessibility Permissions" popup. Using the[ CLI command in an earlier comment](https://github.com/MrKai77/Loop/issues/418#issuecomment-2179451099) fixed me for a majority of the day. But now Loop isn't working again.

When I use my Trigger Key, I get the following Loop Radial Menu:

![IMG_3213](https://github.com/MrKai77/Loop/assets/10338/e259243e-e9a1-4f41-b425-6f79031d528f)

**Comment by MrKai77** [comment]
@BrandonSmith Have you tried relaunching Loop?

**Comment by BrandonSmith** [comment]
> @BrandonSmith Have you tried relaunching Loop?

I just relaunched and that fixed it.

**Comment by lcaproni-pp** [comment]
I also have just encountered the same issue that @BrandonSmith highlighted but i'm unable to fix it, here's what i've tried:

* Removing loop from mac entirely and deleting accessibility permissions then re-installing.
* Following all other combination of steps from this issue
* Changing keybinds to multiple different options, all of them just presented the same issue.

I'm on MacOS - 14.5 (23F79) and it's a silicon chip M1 Pro (same as OP).

Any ideas what it could be?

**Comment by MrKai77** [comment]
@lcaproni-pp that's really weird.. have you tried restarting your computer?

**Comment by lcaproni-pp** [comment]
@MrKai77 Huh, what do you know, that did fix it! I have no idea how or why mind you but happy to report it's working again, my Macbook did restart itself over the weekend for some reason which confused me but didn't think anything of it.  Thank you 🚀

**Comment by whr3430633** [comment]
> @whr3430633 Did you try running the terminal command in my previous comment as well?



> @whr3430633 Did you try running the terminal command in my previous comment as well?

That's weird. It's working again, but I didn't do anything, I just left my Mac there overnight. Anyway, thanks!

**Comment by leonlin21** [comment]
> Removing it from the Accessibility list did the trick for me. Didn't need to quit Loop.
> 
> * Remove Loop from Settings=>Privacy & Security=>Accessibility (highlight the existing Loop entry and click on the - button on the bottom.
> * In the Loop window, go to Advanced and click on the "Request" button on the Permissions/Accessibility Access section
> * Toggle the new Loop entry on Settings=>Privacy & Security=>Accessibility
> * In the Loop window, the "Request" button should now be greyed out and a checkbox should be present indicating access has been granted.
> 
> Thanks for the new version. Looking great! 😄

Works for me!! Thank you

**Comment by cloofsiu** [comment]
> I was having the same issue (on Sonoma 14.4.1) after updating Loop.
> 
> I removed Loop from accessibility settings completely and restarted loop (interestingly, the popup for permissions didn't appear). It (naturally) still didn't work at that point, but after manually adding Loop back into Accessibility permissions, it started working again.
> 
> Now, after quitting/relaunching, it doesn't ask for permissions but does still work.
> 
> The steps I took:
> 
> * Quit Loop
> * Remove Loop from Settings -> Privacy & Security -> Accessibility using the `-` button
> * Launch Loop (did not get Accessibility popup)
> * Add Loop to Accessibility settings using the `+` button
> 
> I can't get Loop back into the broken state again to see if any of these steps are unnecessary, but I'm curious if it works for you too!

It works. Thanks a lot!

**Comment by MrKai77** [comment]
Alright, I will be closing this now :)

**Comment by caiogondim** [comment]
Confirming that https://github.com/MrKai77/Loop/issues/418#issuecomment-2178849660 worked for me as well 🙇
