### ISSUE TITLE
🐛 Popup to allow screen recording, even if animations are off

### ISSUE THREAD

**Issue by kekscode** [MrKai77/Loop#42]
### Bug Description

If accessibility is allowed but screen recording is not and the feature screen recording needs is turned off, every movement action pops up the dialogue to enable screen recording.

### Steps To Reproduce

1. Allow accessibility access but not screen recording
2. Use Loop

### Expected Behavior

No popups

### Actual Behavior

Popups after every action.

### MacOS Version

13.6 (22G120)

### Loop version

1.0.0-beta.10 (brew)

**Comment by MrKai77** [comment]
Oh wow, thank you so much for reporting this! I thought I had tested this but it seems like I may have forgotten! 
This is really important, so I'll try and fix this today! Sorry for the inconvenience! 🙇

**Comment by MrKai77** [comment]
Here's a fixed build: [Loop.zip](https://github.com/MrKai77/Loop/files/12732268/Loop.zip)
Please let me know if you face any other issues!
