### ISSUE TITLE
✨ Move the window across different displays or workspaces. 

### ISSUE THREAD

**Issue by alexandertsukanov** [MrKai77/Loop#421]
### Feature Request Description

Hey, Loop team! 
As a user, I want to have an option to move the app's window across different displays or workspaces. I also want to have a shortcut for that.

So I want to use a radial menu for that, or I want to have an option to be some shortcuts for that option.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Moving windows across multiple displays is already supported!
As for moving the window across multiple spaces, that is tracked here: #223
Will be closing this as a duplicate as that, correct me if I am wrong :)
