### ISSUE TITLE
✨ Minimize by entering the center of the loop

### ISSUE THREAD

**Issue by BardiaKh** [MrKai77/Loop#423]
### Feature Request Description

I have been testing loop for a couple of days and it is AMAZING! Thank you to all the developers and designers for creating this neat experience. I have a feature suggestion to use the central part of the Loop for minimizing the window.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Hello Bardia, happy to hear that! 
This will be implemented in #107, so I'll be closing this as a duplicate :)
Feel free to reach out if you have any more ideas!
