### ISSUE TITLE
Customization for widescreen monitor

### ISSUE THREAD

**Issue by iambudi** [MrKai77/Loop#432]
### Feature Request Description

For a widescreen monitor with a 5K resolution, the left or right third size is still too wide. Is there a way to customize it to be smaller like 1/4 or even 1/6 for certain cases?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Totally! Loop is super flexible :)

You can configure that using a custom keybind:
<img width="397" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/53facb69-6b97-43ae-93d4-1231e25e9d96">

Let me know if you have any more questions!

**Comment by iambudi** [comment]
That's perfect. Love it. Thanks @MrKai77
