### ISSUE TITLE
✨ Allow more keys as trigger keys

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [MrKai77/Loop#440]
### Feature Request Description

It would be awesome to allow more keys, or even key combinations, as trigger keys. I am having a hard time finding a valid trigger key that does not interfere with my editor keybindings (which I use way more often, so I prefer having a key combination for Loop).

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yes, that is currently planned in #260! Will close this as a duplicate.
