### ISSUE TITLE
✨ Allow for dev version

### ISSUE THREAD

**Issue by SenpaiHunters** [MrKai77/Loop#441]
### Feature Description:

Allow users to test unstable and/or developmental versions of Loop ahead of its normal release. 

### Why Do You Want This?:

… yes, two modes for users.

**Comment by JaceThings** [comment]
duplicate of #182 🤭

**Comment by SenpaiHunters** [comment]
Shhh @Soft-Bred it's fine (I was too lazy to find the other one), plus it's a different method 😂
