### ISSUE TITLE
🐞 "Top Left Quarter" Keybinding not working on Mac Sonoma 14.4.1

### ISSUE THREAD

**Issue by JoRoan** [MrKai77/Loop#442]
### Bug Description

"Top Left Quarter" Keybinding not working on Mac Sonoma 14.4.1   I've tried re-mapping to the Up Arrow + Left Arrow, as well. Still doesnt work.  Loop Version 1.0.0 (1030)

### Steps To Reproduce

1. Press [Globe/fn] + Up arrow + Left Arrow
2. No action happens on the window

### Expected Behavior

1. Press [Globe/fn] + Up arrow + Left Arrow
2. Window resizes to Top Left Quarter

### Actual Behavior

1. Press [Globe/fn] + Up arrow + Left Arrow
2. Window does not resize. No action happens.

### MacOS Version

Sonoma 14.4.1

### Loop Version

Version 1.0.0 (1030)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thanks for reporting! I'm assuming that your other keybinds work? I would recommend remapping it to a single key and seeing if that works.

**Comment by JoRoan** [comment]
Yes, other key binds working fine.

I remapped to a single key (F16 on my extended keyboard) and is working fine now, thank you!

**Comment by MrKai77** [comment]
Awesome! So my guess is that the globe key is somehow interfering with other key combinations, so I will look into that :)

**Comment by JoRoan** [comment]
Oh, sorry, I thought you meant "One Key" meant replace the two arrows with 1 key :)
So I remapped "Top Left Quarter" to GLOBE + F16. And that is working.

Trying to keep your Loop as GLOBE + something (for muscle memory).

This is on an Apple wireless extended keyboard (w/ numpad).

**Comment by MrKai77** [comment]
Oh yes, that is what I meant :)<br>I have had issues with detecting arrow keys when the trigger key was the globe key before, so I believe that's the issue that you originally had here.
