### ISSUE TITLE
macOS system permission issues

### ISSUE THREAD

**Issue by jhnmyr233** [MrKai77/Loop#449]
### Feature Request Description

macOS一直在提示我打开系统权限并释放给loop，当我打开权限后，loop依旧无法使用（按下trigger key后没有跳出选择窗口的弹窗），我重启多次后依旧无法使用

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
See here: https://github.com/MrKai77/Loop/issues/418#issuecomment-2178849660

**Comment by jhnmyr233** [comment]
Just now, according to the suggestions of netizens, you can use it by manually deleting it and adding the access rights of the loop again. At present, the problem has been solved.thanks
