### ISSUE TITLE
✨ Ability to restore initial window frame

### ISSUE THREAD

**Issue by walnut-the-hacker** [MrKai77/Loop#45]
### Feature Request Description

Would be nice if we could restore the initial window frame, maybe using the already-existing keybind of `trigger` + `z`, after resizing (if that makes sense).

**Comment by MrKai77** [comment]
Yup, I was planning to implement that soon! Stay tuned!

**Comment by MrKai77** [comment]
Sorry for the delay! Here's a working build: 
[Loop.zip](https://github.com/MrKai77/Loop/files/12798414/Loop.zip)
