### ISSUE TITLE
macOS system permission issues

### ISSUE THREAD

**Issue by jhnmyr233** [MrKai77/Loop#450]
### Feature Request Description

macOS has been prompting me to open the system permissions and release them to the loop. When I open the permissions, the loop still can't be used (the pop-up window of the selection window does not pop up after pressing the trigger key), and I still can't use it after restarting many times.
The current version of my system is macOS Sonoma 14.5 (23F79)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
See here: https://github.com/MrKai77/Loop/issues/418#issuecomment-2178849660
