### ISSUE TITLE
🐞 Fullscreen window snap doesn't work on second monitor.

### ISSUE THREAD

**Issue by MaximilianZenz** [MrKai77/Loop#451]
### Bug Description

Snapping a window to fullscreen only works on the first monitor and not the second one while all other snaps work.

### Steps To Reproduce

drag a window to the top on the second screen

### Expected Behavior

The window snaps to the top

### Actual Behavior

Noting happens

### Screenshots

https://github.com/MrKai77/Loop/assets/48351547/b7556dfd-7b58-4510-ae12-4c02a8a800a1

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0 (1030)

### Additional Context

Snapping on the border of the two screens is also not really reliant because you need to hit it within one pixel which is quite hard when the mouse moves to the other screen. most likely the top thing is the same problem that you have to hit it within one pixel and that the mouse for some reason just can't move there. I think the best solution would be to make the thickness of the drop zone customizable.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Oh interesting! This is definitely caused by your menubar being hidden by default, as Loop uses that to calculate the top snap area. Definitely will fix!

**Comment by MaximilianZenz** [comment]
oh ok. And yeah the menu bar is hidden because I don't use separate spaces for my two monitors. When separate spaces is deactivated booth the menu bar and dock is only available on the primary monitor.

**Comment by MrKai77** [comment]
Fixed! You can download the latest prerelease to get the fix :)
