### ISSUE TITLE
Allow in the background

### ISSUE THREAD

**Issue by ruslan-korneev** [MrKai77/Loop#453]
### Feature Request Description

I want to use that even if i've closed the settings window, so it should work on the background.

### Screenshots

![telegram-cloud-photo-size-4-6037493248508935761-y](https://github.com/MrKai77/Loop/assets/79697348/7e55fbe2-ca7c-4c26-9322-8bcb1f0085d5)

### Additional Context

I've tried this approach but it just make Loop.app settings window open every time i use loop shortcuts:

`~/Library/LaunchAgents/com.loop.keepalive.plist`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>Label</key>
   <string>com.loop.keepalive</string>
   <key>ProgramArguments</key>
   <array>
       <string>/Applications/Loop.app/Contents/MacOS/Loop</string>
   </array>
   <key>KeepAlive</key>
   <dict>
       <key>PathState</key>
       <dict>
           <key>/Applications/Loop.app</key>
           <true/>
       </dict>
   </dict>
   <key>RunAtLoad</key>
   <true/>
</dict>
</plist>
```

**Load the launch agent using `launchctl`**:
```sh
launchctl load ~/Library/LaunchAgents/com.loop.keepalive.plist
```

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by ruslan-korneev** [comment]
I don't know how it works for [rectangle](https://rectangleapp.com/), the app is actually opened, but hidden in the dock/bottom-bar

**Comment by MrKai77** [comment]
Loop currently does work even if the settings window is closed (like Rectangle, Loop has a menubar icon). Just making sure that you've enabled accessibility permits for Loop?

**Comment by ruslan-korneev** [comment]
@MrKai77 I'm sorry, for taking you time, I reinstalled loop and did everything again, and now it works on the background. Don't know, mb i've missed something previous time. Thank you and sorry!

**Comment by 23426356587** [comment]
So - I had the same issue and couldn't get it resolved. Clicked the check for updates button to see if I missed anything, and still nothing.

Then I uninstalled, restarted, installed, and now it works without an dock icon.
