### ISSUE TITLE
Keeps asking for accessibility access

### ISSUE THREAD

**Issue by greg1075** [MrKai77/Loop#454]
### Bug Description

After update to 1.0, Loop asks for Accessibility access, which is already enabled. Pressing the trigger key does nothing. I tried rebooting and toggling Accessibility access off and back on, but no dice. 

### Steps To Reproduce

1. Update to 1.0
2. Loops asks for Accessiblity access when alread enabled

### Expected Behavior

No prompt asking for Accessiblity access

### Actual Behavior

After update to 1.0, Loop asks for Accessibility access, which is already enabled. Pressing the trigger key does nothing. I tried rebooting and toggling Accessibility access off and back on, but no dice. 

### Screenshots

<img width="529" alt="Screenshot 2024-06-23 at 6 30 59 PM" src="https://github.com/MrKai77/Loop/assets/28992145/3f6b6511-0555-4572-84e3-0974b30413fc">

<img width="827" alt="Screenshot 2024-06-23 at 6 31 09 PM" src="https://github.com/MrKai77/Loop/assets/28992145/a2946833-735d-4e07-b60e-64b76311e39b">

### MacOS Version

Sonoma 14.5 (23F79)

### Loop Version

1.0.0 (1030)

### Additional Context

n/a

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
See here: #418
