### ISSUE TITLE
🐞 When Loop (1.0.0) is running, dragging anything has a very noticable lag

### ISSUE THREAD

**Issue by luckman212** [MrKai77/Loop#459]
### Bug Description

M1 Mac Mini, 16GB, macOS 14.5

I don't know how to really describe this strange bug, but I took a couple of "before" and "after" videos with my phone to try to capture the symptom.

Basically, when Loop is running, anything I click and drag has a very noticable lag to it. This includes desktop icons, menubar items, etc (but strangely, not windows themselves)

Here's a video of me clicking and dragging an icon around while Loop is running (notice the slow refresh rate and how the icon lags and jerks behind the mouse position)

https://github.com/MrKai77/Loop/assets/1992842/0f448cae-5a5e-4a92-b987-84d0e6da9d12

And here's me quitting Loop and then playing around with that same icon. Notice how much smoother it is.

https://github.com/MrKai77/Loop/assets/1992842/92aab352-5889-43b1-90ac-17d25d697078

### Steps To Reproduce

1. Fresh boot
2. Make sure Loop is running
3. Click and drag desktop icon or menubar item around.

### Expected Behavior

Smooth

### Actual Behavior

Jerky

### Screenshots

(Videos)

### MacOS Version

14.5

### Loop Version

1.0.0 (1030)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Try this build: [Loop.zip](https://github.com/user-attachments/files/15920904/Loop.zip)

**Comment by luckman212** [comment]
@MrKai77 So far so good, that dev build seems to work fine for me! I will keep testing it. Awesome! 🙏 🚀

**Comment by MrKai77** [comment]
Awesome to hear! That dev build uses a different method to track window drags (used in window snapping and restoring window frames), which should interfere less with the system :)

**Comment by luckman212** [comment]
@MrKai77 The only side-effect so far that I *think* is related to having this Loop dev version running:

When using the <kbd>⌘cmd</kbd>+<kbd>⇧shift</kbd>+<kbd>4</kbd> keyboard shortcut to take screenshots, previously I could hold and release the spacebar while the <kbd>⌃CTRL</kbd> key was being held down to move the capture rectangle around. Now this only works 10-20% of the time, other times pressing spacebar does nothing. I never had this happen before, so I am fairly sure it's related somehow.

**Comment by MrKai77** [comment]
Hey @luckman212! That seems worth opening another issue for, I would appreciate it if you could do that :)

**Comment by luckman212** [comment]
Of course. I'll do that, thanks.
