### ISSUE TITLE
🐞 [Loop not resizing windows, asks for permissions even when all given]

### ISSUE THREAD

**Issue by KarolGralewski** [MrKai77/Loop#461]
### Bug Description

Loop stopped working after updating to the newest version. When opened, Loop asks for system permissions even when they are given. After that the Loop isn't enabled by the hotkey. Tried reinstalling and the issue is still present.

### Steps To Reproduce

1. Open Loop
2. Loop asks for permissions
3. Give permissions
4. Loop still doesn't enable while pressing hotkey

### Expected Behavior

Enabling Loop by the hotkey

### Actual Behavior

Nothing happens

### Screenshots

![image](https://github.com/MrKai77/Loop/assets/63659958/aad7dbd2-7529-4fd2-bcf1-de1fc0d24408)

### MacOS Version

Sonoma 14.5

### Loop Version

1.0.0

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
See #418.
