### ISSUE TITLE
✨ Allow function key as trigger key

### ISSUE THREAD

**Issue by T1mVo** [MrKai77/Loop#463]
### Feature Request Description

I am using an external keyboard with my mac and it does not have the globe key. It would be great if I could use the globe/fn key on both keyboards. I dont know if both of these keys are even the same though.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yes, I've actually spend a lot of time researching this. Unfortunately, macOS doesn't allow a `NSEvent` monitor to listen for function key presses, even though the globe key works completely fine. I believe that this limitation is also reflected in [Karabiner](https://karabiner-elements.pqrs.org).

This might get a little technical, but it may be possible to use a `CGEvent` monitor to listen for the key, but this has broken multi-key trigger keys, so unfortunately this is not currently possible :(

**Comment by T1mVo** [comment]
Alright, thank you for your effort :)
