### ISSUE TITLE
✨ Key bindings export with loop progress

### ISSUE THREAD

**Issue by kawikak** [MrKai77/Loop#464]
### Feature Request Description

I've had to reinstall Loop a few times on the same computer because of bugginess (trying to reproduce to report those separately). Being able to export keybindings has saved me a lot of trouble, but I always lose my loop progress and access to icons. It would be nice if the key bindings export also exported some sort of secret key to re-establish loop progress for access to icons or there was some other way to maintain progress after re-installs.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Actually, I am currently working on iCloud sync :) 

At the moment, you can manually set your times looped with:

defaults write com.MrKai77.Loop timesLooped x

**Comment by kawikak** [comment]
iCloud sync is even better! And thanks for the tip, back where I left off. Loop on!
