### ISSUE TITLE
🐞 Loop Window Preview shows on Screen 1 after moving window to Screen 2

### ISSUE THREAD

**Issue by addvanced** [MrKai77/Loop#475]
### Bug Description

When moving a window between screens, Loop doesn't recognise that the window has moved. If I try to move the window again, the preview to where it should move, is still on the 1st screen. I have to click on the window on the seconds screen, for Loop to "realise" that the window is now on the seconds screen.

### Steps To Reproduce

1. Open window on Screen 1
2. Move window to Screen 2 and let go of the trigger keys
3. Now try and move the window again, by holding down trigger keys and right/left
4. Loop preview shows up on Screen 1, instead of Screen 2 where the window is

### Expected Behavior

I expect that the Loop Preview would show up on the screen where the window actually is, and no where it came from, without having to actively "force" focus on the window again with a mouse click

### Actual Behavior

The Loop window preview shows up on the original screen, if you do not "force a focus with a mouseclick etc." on the window after moving it to another screen

### MacOS Version

Sequoia 15.0 Beta 2

### Loop Version

Version 1.0.0 (1030)

### Additional Context

This could be a macOS Sequoia Beta 2 issue.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Try disabling the "Use screen with cursor" setting in the general tab, I believe that this should resolve your issue.

**Comment by addvanced** [comment]
> Try disabling the "Use screen with cursor" setting in the general tab, I believe that this should resolve your issue.

Thanks. That did the trick.
Maybe I just dont understand that feature. :)

But I guess we can close this bug then.
