### ISSUE TITLE
✨ Ability To Hide Preview

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#481]
### Feature Description:

Allow for the preview to be dismissed and shown<br><br>[https://www.figma.com/design/7JLRVafMYI9kbpnDcwd9Of/Loop?node-id=1203-32294&t=2SWCfkUMKFtcG0hO-11](https://www.figma.com/design/7JLRVafMYI9kbpnDcwd9Of/Loop?node-id=1203-32294&t=2SWCfkUMKFtcG0hO-11)

### Why Do You Want This?:

people (one person), were asking for it.

**Comment by SenpaiHunters** [comment]
Should be done, so I will close this issue. 
![Loop - June 06 2024 - 12 07 PM@2x](https://github.com/MrKai77/Loop/assets/103985728/84d01901-ded3-433d-ae8a-324e68d2497f)
