### ISSUE TITLE
💄 Overhaul readme

### ISSUE THREAD

**Issue by SenpaiHunters** [MrKai77/Loop#487]
### Improvement Description:

The readme is pretty old and outdated, let's change it completely to outline what Loop is and how users can make Loop their own. This will bring a new and fresh vibe to Loop, in the same sense that Luminare had!

### Why tho…?:

Out-of-date or basic READMEs prevent users from having a quick overview of the app. Creating or editing the current README to include even the basics is key. (I understand there is a GIF which gives users an idea that it's WM, but there needs to be more.)

**Comment by uncenter** [comment]
FYI I'm seeing "Unable to render expression" in parts of the comparison table at the bottom of the new README:

![CleanShot 2024-07-22 at 20 01 06@2x](https://github.com/user-attachments/assets/6bbbb7a1-c827-45d4-84da-d169b609c627)

**Comment by SenpaiHunters** [comment]
Yea, it's due to how it's being rendered. Just reload the page and it should fix
