### ISSUE TITLE
🐛 Loop staying permanently on screen

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#50]
### Bug Description

Problem with window overlays

### Steps To Reproduce

1. Quciky press hotkey(option in my case) + shift

### Expected Behavior

To function normally, like a termporary window that disappears as soon as you release the hotkey

### Actual Behavior

Windows staying permanently
https://we.tl/t-I5UqC88LhE

### MacOS Version

Sonoma 14, public beta

### Loop Version

The previous issue's application

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thanks for reporting this bug!
This is also something I've encountered (very rarely though), and it was something I could never figure out how to reproduce. Since you have now provided it, I'll see what I can do about fixing the bug!

**Comment by MrKai77** [comment]
Ok... This should fix it! 
[Loop.zip](https://github.com/MrKai77/Loop/files/12787860/Loop.zip)
