### ISSUE TITLE
✨ Max Height without Modifying Width

### ISSUE THREAD

**Issue by Ender-Wang** [MrKai77/Loop#503]
### Feature Request Description

- Moved from Rectangle to Loop because of the GREAT window animation when resizing them! 
- There's a feature in Rectangle that I use every day that to be able to maximize the window size without modifying the width of it, many times I have Chrome max height but left the width untouched.
- I saw there are options to adjust the `with & height` in the `custom keybinds`, so the easier way to fulfill this feature request would be to give us `the option to un/check width or height`, so when changing width/height, the other property remains untouched.

### Screenshots

![CleanShot_2024-07-10_11-38-09](https://github.com/MrKai77/Loop/assets/33310255/7fd81c0f-473d-4947-9103-6ab14cd61940)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Interesting idea, will definitely look into implementing this :)

**Comment by andrew-tiosa** [comment]
after latest update doesn't work on latest Sonoma.... it ask for permission, granted , unistallled, brew installed, doesnt work.....

**Comment by MrKai77** [comment]
@andrew-tiosa check #418. I can run Loop on Sonoma without any problems. If the problem persists, please open a new issue.

**Comment by andrew-tiosa** [comment]
@MrKai77 fixed with #418 solution. appreciate it!

**Comment by Ender-Wang** [comment]
No offense, but this feature request is not the place to report bug I assume, and now it's marked as closed lmao

**Comment by SenpaiHunters** [comment]
Ah, @Ender-Wang i did not see this, I'll reopen the issue as it's a feature request. I agree, @andrew-tiosa, next time create an issue, and don't use other peoples.
