### ISSUE TITLE
✨ Windows preview in the dock

### ISSUE THREAD

**Issue by Romachamp** [MrKai77/Loop#505]
### Feature Request Description

Please, add a feature, that enables **previewing opened windows of an app when hovering on its icon in the dock**. It would be really helpful, because It would become much easier to see and navigate between windows. 

### Additional Context

Thank you, in advance!

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by SenpaiHunters** [comment]
This won't be a Loop feature, something you'd want would be [DockDoor](https://github.com/ejbills/DockDoor)
