### ISSUE TITLE
Super Ultrawide Support

### ISSUE THREAD

**Issue by nesl247** [MrKai77/Loop#508]
### Feature Request Description

Please add more sizes that are better for super ultrawide monitors. Currently I can only have 2 windows side by side, but on a super ultrawide, it would be nice to have 3.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
You can add custom window actions here!
<img width="302" alt="Screenshot 2024-07-14 at 3 25 06 PM" src="https://github.com/user-attachments/assets/fee7837d-5b70-4cce-95f2-5410574cf8b5">

**Comment by nesl247** [comment]
@MrKai77 but those are keybinds not part of the radial menu right?

**Comment by MrKai77** [comment]
Ah yes, configuring the radial menu is planned at #107. I have just finished implementing the backend for customizing the radial menu, so hopefully it doesn't take too much longer to finish implementing :)

**Comment by MrKai77** [comment]
Closing this as a duplicate :)
