### ISSUE TITLE
✨ Selecting the window to resize on mouse hover

### ISSUE THREAD

**Issue by ABOrange** [MrKai77/Loop#510]
### Feature Request Description

A nice function to add is that make Loop select the window to resize on cursor hover instead of having to click on the window and bring it to the front to be able to resize.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
That is planned in #209.

However, you might already be satisfied with these settings under "Cursor" section in the "General" tab:
<img width="386" alt="Screenshot 2024-07-15 at 8 11 35 PM" src="https://github.com/user-attachments/assets/1b41cd27-5fad-48de-a325-b435873aa3d9">

**Comment by ABOrange** [comment]
Works great! Thank you.
