### ISSUE TITLE
🌐 Arabic localisation

### ISSUE THREAD

**Issue by muhammadbahaa2001** [MrKai77/Loop#517]
### What language do you intend to add or change?

Arabic

### Final Checks

- [X] My localisation request is written in English
- [X] My localisation request title is descriptive
- [X] This is a single localisation request (multiple localisation request should be requested individually)
- [ ] I need a localised file for my language (tick this if needed)

**Comment by SenpaiHunters** [comment]
Awesome! For the localizations you cannot seem to find a direct translation for, such as movie quotes, just leave it blank. I see you've ticked that you do not need the file; however, if this becomes true at a later date, here it is! [ar.xcloc.zip](https://github.com/user-attachments/files/16318535/ar.xcloc.zip). Once localized, please ping me, and I'll add your localizations to Loop and credit you after completion 😄

**Comment by muhammadbahaa2001** [comment]
> Awesome! For the localizations you cannot seem to find a direct translation for, such as movie quotes, just leave it blank. I see you've ticked that you do not need the file; however, if this becomes true at a later date, here it is! [ar.xcloc.zip](https://github.com/user-attachments/files/16318535/ar.xcloc.zip). Once localized, please ping me, and I'll add your localizations to Loop and credit you after completion 😄 

I will try to finish it soon as possible.

**Comment by muhammadbahaa2001** [comment]
@SenpaiHunters Done!
[ar.xcloc - localized.zip](https://github.com/user-attachments/files/16322442/ar.xcloc.-.localized.zip)

**Comment by SenpaiHunters** [comment]
Hey, @muhammadbahaa2001, can you re-export it, seems the build is corrupted as it's failing to import. 

Menu bar → Product → Export Localizations... → Untick all other localisations → Export → Zip the file up and resend it.

**Comment by MrKai77** [comment]
@muhammadbahaa2001 we have successfully imported the file, and have created a draft PR for you! This is excellent :)
But it looks like not all strings have been translated yet, here's a new file if you require it:
[ar.xcloc.zip](https://github.com/user-attachments/files/16323397/ar.xcloc.zip)

**Comment by muhammadbahaa2001** [comment]
> @muhammadbahaa2001 we have successfully imported the file, and have created a draft PR for you! This is excellent :) But it looks like not all strings have been translated yet, here's a new file if you require it: [ar.xcloc.zip](https://github.com/user-attachments/files/16323397/ar.xcloc.zip)

[ar.xcloc - finsihed.zip](https://github.com/user-attachments/files/16336200/ar.xcloc.-.finsihed.zip)
