### ISSUE TITLE
🌐 German localisation

### ISSUE THREAD

**Issue by L1am-cd** [MrKai77/Loop#523]
### What language do you intend to add or change?

Translating Loop into german

### Additional Context

Taking over the German localisation process.

### Final Checks

- [X] My localisation request is written in English
- [X] My localisation request title is descriptive
- [X] This is a single localisation request (multiple localisation request should be requested individually)
- [ ] I need a localised file for my language (tick this if needed)

**Comment by SenpaiHunters** [comment]
Perfect, once you've fully localised the file please give me a ping and I'll do what's needed in my end, if you cannot translate some sayings fully you can leave the section blank.

**Comment by L1am-cd** [comment]
Okay! Is there an updated .xloc or should I use the same one as in the other issue?

**Comment by SenpaiHunters** [comment]
There is an updated one since Kai gave the previous one; yes, let me give it to you now. [de.xcloc.zip](https://github.com/user-attachments/files/16323848/de.xcloc.zip)

**Comment by L1am-cd** [comment]
@SenpaiHunters I have finished the translation now! Sorry this took a little longer, took some breaks.

[de.xcloc.zip](https://github.com/user-attachments/files/16324703/de.xcloc.zip)

**Comment by SenpaiHunters** [comment]
No, this is awesome, and it's fully localized! We've got a Discord server if you'd like to stay aware of updates to localizations. I will add this and your name to the list, then branch and push it when the other user's localization is done! Thank you for this

**Comment by L1am-cd** [comment]
No, I should thank! I have joined the discord server now too. Should the Issue be closed?

**Comment by SenpaiHunters** [comment]
It'll automatically be closed when the branch is merged 😄 So, you don't need to worry about anything else here.
