### ISSUE TITLE
✨ Hackintosh Support

### ISSUE THREAD

**Issue by Birdabo404** [MrKai77/Loop#524]
### Feature Request Description

I recently discovered this lovely app on twitter and I have been wanting to download it but when I did, it didn't work. Tho I was able to download it and tinker with the settings but when I tried the shortcuts provided nothing happens. I'm not sure if its a bug [using the latest release] or maybe just because I am using Hackintosh. 

OS: macOS Ventura 13.6.7

Hoping this req wouldn't get ignored. cheers.

### Screenshots

![Screenshot 2024-07-23 at 4 39 29 AM](https://github.com/user-attachments/assets/5b36c638-8667-4f63-a16a-4d0d27dc5889)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by SenpaiHunters** [comment]
None of the team has any type of Hackintosh, so none of us can actually test this. However, I am not 100% sure why this is happening; I assume some keybinds aren't being respected. I'm also not entirely clear on Hackintoshs and how they function in regard to macOS. I assume it masks itself as any other Mac, but I'm unsure if the `CGEvent` will respect that keyboard. 

For now, I can recommend some basics:
1. Clear Loop of its previous permissions, quit it, and reauthorize.
2. Try another/different/older version, to see if anything before would work (although the newer the better).
3. Create a screen recording to see if it's a basic issue within Loop itself or if it requires logic changes.

At this point, we won't/can't support Hackintoshs, as this is one of the first issues regarding this matter. Additionally, there won't be any major code changes to Loop for now, as our main developer, Kai, is away on a well-deserved holiday.

However, if you've got more information regarding this, or if another window manger works, I can look into this more.

**Comment by MrKai77** [comment]
As @SenpaiHunters said, we have no way of testing this on our side, so I will be closing this.
