### ISSUE TITLE
🐞 Loop codesign issue

### ISSUE THREAD

**Issue by marketjob2022** [MrKai77/Loop#527]
### Bug Description

“Loop” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
![Loop Image](https://github.com/user-attachments/assets/ffb39524-f4eb-4859-8f17-6b84a0d63ba3)

### Steps To Reproduce

“Loop” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
![Loop Image](https://github.com/user-attachments/assets/ffb39524-f4eb-4859-8f17-6b84a0d63ba3)

### Expected Behavior

“Loop” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
![Loop Image](https://github.com/user-attachments/assets/ffb39524-f4eb-4859-8f17-6b84a0d63ba3)

### Actual Behavior

“Loop” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
![Loop Image](https://github.com/user-attachments/assets/ffb39524-f4eb-4859-8f17-6b84a0d63ba3)

### Screenshots

![Loop Image](https://github.com/user-attachments/assets/740ce7b4-91e9-48a5-9779-6bd06fd97aeb)

### macOS Version

Mac Mini 2023 MacOS Sonoma

### Loop Version

Version 14.5

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
What version of Loop are you running? Please fill in the form properly next time you open an issue.

**Comment by SenpaiHunters** [comment]
@marketjob2022, as Kai has said. Fill out the issue form correctly next time, and what version are you trying to download, you should be opening version 1.1.1 from the Release tab on GitHub, or indicate if you're trying to install this from brew.

**Comment by marketjob2022** [comment]
yes i am trying to download it from Github and its release 1.1.1.         please guide me from where should i download the latest version, as i m not able to download it from app store.          please provide the link to download the latest version

**Comment by SenpaiHunters** [comment]
https://github.com/MrKai77/Loop/releases/latest/download/Loop.zip download this and run it. Loop is and never will be on the App store.

**Comment by marketjob2022** [comment]
yes its still the same error coming up 
I am trying to install in Mac Mini M2  
Loop latest release as provided in the link
Still  not able to access it due that error, attached file to get idea.


![LOOP July 26 2024 @9:42AM](https://github.com/user-attachments/assets/9f6d8fd4-88f9-4e90-a004-399dcad62fe5)
![Loop Info](https://github.com/user-attachments/assets/87bf901f-72a3-40f6-9355-43779104dde0)
![system info](https://github.com/user-attachments/assets/e7456277-ebbf-4a67-937e-b2eea6aa3fae)

**Comment by SenpaiHunters** [comment]
I'm not entirely sure why this is happening, however, all I can recommend is

1. With Loop move it to the `~/Applications` folder, then open it
2. If it fails, or logs with the same error as before, try pass this command and open it
```bash
xattr -c "/Applications/Loop.app"
```
3. Try downloading it using another browser

**Comment by GrahamQuan** [comment]
i had this issue too
- macos version 14.2.1 (m1 chip)
- chrome version 127.0.6533.73 (Official Build) (arm64)
- loop Version 1.1.1 (1259)

bug
- download the latest version and unzip the zip file, then open `loop`, app crash
- move `loop` to `application` folder, open it, app still crash

solution
1. move `loop` to `application` folder
2. open `terminal` and run `xattr -c "/Applications/Loop.app"`

**Comment by marketjob2022** [comment]
its works now thanks to all.      

please guide me is there a way i can use multiple windows in a single screen with 8 Rows & 10 Columns, and arrange my way to them

**Comment by SenpaiHunters** [comment]
Use the custom option and configure your sizes etc, have a flick around them! https://github.com/MrKai77/Loop#keyboard-shortcuts-1 - I will now be closing this, as it's done. If anyone has this issue remember.

1. Open the ZIP
2. Move it to the `~/Applications` folder
3. Open Loop

**DO NOT**: Open it whilst it's in the downloads section, if this fails run the command.
```sh
xattr -c "/Applications/Loop.app"
```
