### ISSUE TITLE
🐞 Permission issue

### ISSUE THREAD

**Issue by sagarishere** [MrKai77/Loop#532]
### Bug Description

The loop checks for permission too fast, as soon as it starts. The issue happens as there is no delay between when the computer starts and when the loop asks for permission.

So when I start login to my mac, the loop is asking for permission, even though it already has the permission. This happens as the io for permission is not available immediately. 

If it delayed for 2-5 seconds before looking for permission, this problem would disappear.

### Steps To Reproduce

1. Update loop to latest version
2. Switch off your computer
3. Restart your mac and login again
4. You should see Loop asking for permission again, as it was unable to detect that it already has the permission (due to delay in availability of io for permission).

### Expected Behavior

Once the permission is given, then Loop should know.

### Actual Behavior

Even when permission was given, it asks for permission again

### macOS Version

Sonoma 14.6

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
I cannot repo this, although, I'm also not on 14.6. I don't think a delay will do anything to be frank. Turn off Loops permissions, open the app, click on the two popups, force quit loop, remove the accessibility perm completely, then press + add Loop back to see if'll reset it.

**Comment by sagarishere** [comment]
got it. followed the steps, the issue persists.

It appears that you are right about that delaying first permission check will not happen. I will try some other methods, but could be a local issue limited to my computer rather than software or os issue.

![image](https://uploads.linear.app/80ac51d6-b1c5-48ff-a911-e9b446f51d33/eaf20fd9-ff02-4ca2-8372-66bae7c46654/098199e0-36ad-444a-9fe8-62c0bd08d04e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYWM1MWQ2LWIxYzUtNDhmZi1hOTExLWU5YjQ0NmY1MWQzMy9lYWYyMGZkOS1mZjAyLTRjYTItODM3Mi02NmJhZTdjNDY2NTQvMDk4MTk5ZTAtMzZhZC00NDRhLTlmZTgtNjJjMGJkMDhkMDRlIiwiaWF0IjoxNzIyNzcyNzE4LCJleHAiOjMzMjkzMzMyNzE4fQ.NacrwYTOKq-VIPVNZB5HwhvV4fDFo66XygMJOWY0sqs "=1262x")

**Comment by sagarishere** [comment]
I am closing this issue as this seems to be a system issue rather than an app issue.
