### ISSUE TITLE
🐞 Loop crashes when cycling outside the window

### ISSUE THREAD

**Issue by opakholis** [MrKai77/Loop#533]
### Bug Description

Loop crashes when cycling while no application or window is active.

### Steps To Reproduce

1. With the app not fully maximized on the desktop.
2. Move and click outside the window.
3. Do a cycle.
4. Loop crashes immediately.

### Expected Behavior

App doesn't crash

### Actual Behavior

Loop crashes

### Screenshots

![CleanShot 2024-08-03 at 3 02 11](https://github.com/user-attachments/assets/9277e7d1-27a0-423c-93d1-7a8c069f5193)

### macOS Version

Ventura 13.6.7

### Loop Version

1.1.1 (1259)

### Additional Context

[Here's the crash log](https://pastebin.mozilla.org/AuuopL7D)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Hey, thanks for the crash logs. I went through them and tried reproducing the issue, but I couldn't replicate the crash on either version 1.1x or earlier, nor in a development build. It seems like it might be an issue on the macOS side, possibly related to how concurrency is being handled. Could you please do a screen recording if possible? Also, is Loop set to a language other than English?

**Comment by opakholis** [comment]
Unfortunately, I couldn't reproduce the issue during the screen recording, likely due to the focus window factor.

I recorded the issue with my phone instead:

[https://github.com/user-attachments/assets/f4369ca9-967d-4f02-9e12-8f822d54a1c2](https://github.com/user-attachments/assets/f4369ca9-967d-4f02-9e12-8f822d54a1c2)

Additionally, Loop language is set to English, as shown in the video.

**Comment by MrKai77** [comment]
> likely due to the focus window factor

This seems to be what was causing it, the latest prerelease should fix this! (and the _next_ prerelease will optimize this functionality even more!) :)
