### ISSUE TITLE
🐞 Daily Loop crashes

### ISSUE THREAD

**Issue by harshar-1** [MrKai77/Loop#534]
### Bug Description

Loop program crashes (quietly). I had to relaunch the program everytime I tried a shortcut and it wouldn't work.

I checked and saw crash reports in the console.
crash reports. 
Termination Reason: Namespace SIGNAL, Code 6 Abort trap: 6

OS Version: macOS Sonoma 14.5 (23F79)
Code Type: ARM-64 (Native)
Loop version: 1.0.0 (1030)
macOS Sonoma on M1 MacBook Air

### Steps To Reproduce

1. Start loop
2. Wait.
3. Try shortcuts once in a while.
4. Program crashes (quietly)
5. Try shortcut, and if not working, then check for loop in activity monitor

### Expected Behavior

The program needs to be running in the background until quit.
App should not crash.

### Actual Behavior

Program crashes without any indication.

### macOS Version

macOS Sonoma 14.5 (23F79)

### Loop Version

version 1.0.0 (1030)

### **Crash logs**
**Date/Time: 2024-07-29 18:05:35.8329 +0530**
https://pastebin.mozilla.org/QpLFetiG

**Date/Time: 2024-08-01 19:56:11.7297 +0530**
https://pastebin.mozilla.org/Mzv2acY1

**Date/Time: 2024-08-02 22:40:14.8484 +0530**
https://pastebin.mozilla.org/Xhz4FNt1

**Date/Time: 2024-08-03 18:57:47.5146 +0530**
https://pastebin.mozilla.org/XELXLnJ0

**Date/Time: 2024-08-05 01:51:50.4732 +0530**
https://pastebin.mozilla.org/1zaH8JwW

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
UPDATE LOOP!!!!!!! Then give me a new report

**Comment by harshar-1** [comment]
Have updated to Version 1.1.1 (1259). Will let you know if it happens again.

**Comment by JaceThings** [comment]
Is this still an issue?

**Comment by harshar-1** [comment]
No. I haven't experienced any crashes. 
Sorry for the delay. 

Version 1.1.1 (1259)
2024-08-05 12:00 PM - started program
2024-08-05 1:04 PM - chk ok
2024-08-05 5:23 PM - chk ok
——
2024-08-06 1:25 PM - chk ok - 24h run
2024-08-06 5:26 PM - chk ok
——
2024-08-07 5:55 PM - chk ok
2024-08-07 10:09 PM - chk ok
—
2024-08-08 12:45 PM - chk ok
——
2024-08-09 09:25 AM - chk ok
——
2024-08-11 5:11 PM - chk ok
——
2024-08-13 12:15 PM - chk ok
2024-08-13 12:15 PM - Version 1.1.1 (1259)

**Comment by SenpaiHunters** [comment]
If it's been solid and hasn't crashed yet it looks good, I will be closing this issue. However, if there is more crashes, please make a new issue like before! Cheers
