### ISSUE TITLE
🐞 Show in dock toggle 

### ISSUE THREAD

**Issue by hibluesea** [MrKai77/Loop#536]
### Bug Description

when turn on the button the icon show in docker, but when turn off the button, the icon still show in docker, the switch button 
seems do not work.

### Steps To Reproduce

1 turn the button on , the icon show in docker
2 turn the button off, the icon still show in docker

### Expected Behavior

1 when the button is on , the icon show in docker
1 when the button is off,  the icon hide in docker 

### Actual Behavior

the icon is always show  in docker, this is not expected

### Screenshots

<img width="378" alt="image" src="https://github.com/user-attachments/assets/b096ffd9-b1f7-479f-a9fd-4a95815198ef">

### macOS Version

sonoma 14.6

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Regardless of your state, if Loops settings are open, the icon will remain visible. The state will only take effect once you close the settings. 

1. **Disabled** = No icon  
2. **Enabled** = Icon visible

**Comment by hibluesea** [comment]
thanks you are right, the icon only disappear when the window is closed
