### ISSUE TITLE
🍱 Add [fontisto--zoom-plus]

### ISSUE THREAD

**Issue by 0xwataru** [MrKai77/Loop#537]
### Icons

![fontisto--zoom-plus](https://github.com/user-attachments/assets/b10985a6-7ce1-49ff-9e2e-b20c7bbdf86a)

### Comments

zoom-plus

### Final Checks

- [X] My suggestion is written in English
- [X] I am submitting an icon (this is not for icon requests)

**Comment by JaceThings** [comment]
what

**Comment by SenpaiHunters** [comment]
Ensure that in the final checks, when you press 'I am submitting an icon,' you are submitting an image of your icon, not a blank screen or SVG. Please correct this issue. If it is not corrected within the next week, the issue will be closed.
