### ISSUE TITLE
🐞 Loop application auto quit or not respond

### ISSUE THREAD

**Issue by yclau97** [MrKai77/Loop#540]
### Bug Description

I am not able to trigger the loop radial menu, and I need trigger it by opening the loop application. But after some time, again not able to trigger the loop radial menu and I need to repeat the process of opening the loop application then only able to open the radial menu.

### Steps To Reproduce

Not able to provide the steps as sometime it works sometime is not and I just reopen the loop application in order to use the radial menu.

### Expected Behavior

Once open loop application and as long as I did not quit it, I am able to use the loop radial menu at any time.

### Actual Behavior

Sometimes able to use radial menu sometimes cant and need to open loop application in order to use the radial menu.

### macOS Version

Sonoma 14.5

### Loop Version

Version 1.0.0 (1030)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
UPDATE LOOP!!! Then come back and tell me if you have the same issue.

**Comment by MrKai77** [comment]
Closing as a duplicate of #534.
