### ISSUE TITLE
🐞 Shortcut Key Malfunction Bug

### ISSUE THREAD

**Issue by Chel1zi** [MrKai77/Loop#542]
### Bug Description

I really enjoy using this app. However, I've encountered a strange bug. Ever since a particular update, even though I've granted the app the necessary permissions, I can no longer use the shortcut keys to resize the program's window. I've tried restarting my computer and re-granting the permissions, but it still doesn't work. I even reinstalled the app, but that didn't help either. My macOS version is Sonoma 14.6.1 with an M1 Pro chip, and the app version is 1.0.0.

### Steps To Reproduce

1

### Expected Behavior

1

### Actual Behavior

1

### macOS Version

Sonoma 14.6.1

### Loop Version

1.0.0(1030)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Update loop

**Comment by Chel1zi** [comment]
> Update loop

I have updated to version 1.1, but it still doesn't work.

**Comment by Chel1zi** [comment]
Every time I open the app, it prompts me to grant access to assistive features, but I have already granted the relevant permissions.
<img width="251" alt="截屏2024-08-20 10 31 19" src="https://github.com/user-attachments/assets/a075f706-5078-4e92-a6df-81d8a5502264">
<img width="474" alt="截屏2024-08-20 10 31 30" src="https://github.com/user-attachments/assets/ad8e0830-857a-42a6-b923-a201b154632e">

**Comment by SenpaiHunters** [comment]
Try this:

Quit Loop → System Settings → Accessibility → Loop (click on Loop) → `-` Button. Then use the `+` button to re-add Loop while it's closed. Reopen Loop once done.

Image for ref
![000893-08@2x](https://github.com/user-attachments/assets/c4ce9a61-5051-4169-8116-8ffef0e0a27a)

**Comment by Chel1zi** [comment]
It finally works, ohhhhhhhhhhh, thank you so much for your help.I really, really enjoy using your app.

**Comment by 2e2ee95304418f96** [comment]
> Try this: 试试这个：
> 
> Quit Loop → System Settings → Accessibility → Loop (click on Loop) → `-` Button. Then use the `+` button to re-add Loop while it's closed. Reopen Loop once done.退出 Loop → 系统设置 → 辅助功能 → Loop（点击 Loop）→ `-` 按钮。然后使用 `+` 按钮在 Loop 关闭时重新添加 Loop。完成后重新打开 Loop。
> 
> Image for ref 参考图片 ![000893-08@2x](https://private-user-images.githubusercontent.com/103985728/359317638-c4ce9a61-5051-4169-8116-8ffef0e0a27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDY2MDAsIm5iZiI6MTcyNTcwNjMwMCwicGF0aCI6Ii8xMDM5ODU3MjgvMzU5MzE3NjM4LWM0Y2U5YTYxLTUwNTEtNDE2OS04MTE2LThmZmVmMGUwYTI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxMDUxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjM0MmFjOTEwYjk5ZjNiMzVmOTZhMDNhNzQzZDRjOGQ0NjJjNmUzMmE2Y2U5ODhiZGMwYjdiOGQ0YzkyZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aXkVPMlpoRPJCPmG-wM03pUDPzQ2F9BbqmhF7-Jx-IQ)

Thanks, this resolved my problem. But I  think this is bug.
