### ISSUE TITLE
✨ [Menu bar shortcut operation]

### ISSUE THREAD

**Issue by zhanggang807** [MrKai77/Loop#548]
### Feature Request Description

Like old version , I can change window by shortcut in menu bar.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by SenpaiHunters** [comment]
It's highly unlikely for this to come back, as you should be using keyboard shortcuts, or snap centres if you need your mice.

**Comment by MrKai77** [comment]
Yes, this is not on our roadmap.
