### ISSUE TITLE
🐞 Custom cycle with custom windows closes modal before you're done customizing

### ISSUE THREAD

**Issue by brunomdsilva** [MrKai77/Loop#549]
### Bug Description

If I create a custom cycle and try to add a custom window size, the modal for editing the window size keeps closing before I finish my customization. If I click anywhere or try to tweak anything, the modal closes instantly, making it impossible to make any changes correctly.

### Steps To Reproduce

1 - create a custom cycle keybinding
2 - add a custom keybind (window size)
3 - try to change any values (width, height, check any options...)

### Expected Behavior

It should keep the modal openened until I click "close" and save changes

### Actual Behavior

It closes the modal if I click or change any value

### Screenshots

https://github.com/user-attachments/assets/78f67d30-2dae-4659-81d3-6def053e102c

### macOS Version

macOS Sonoma - 14.6.1

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Switch to the dev release, this should be fixed in pr #547 . Anymore issues let me know
