### ISSUE TITLE
🐞 Keybindings: changing the keybinds triggers "customize keybind’s action" modal

### ISSUE THREAD

**Issue by greg1075** [MrKai77/Loop#553]
### Bug Description

Changing the secondary trigger key sometimes opens the "customize this keybind’s action" menu, and other times it doesn’t. I’m not sure what triggers this and whether or not it is intended or not, but it definitely is unnecessary. It actually forces the user to close the keybind's action menu before moving on. 

### Steps To Reproduce

1. Go to Keybindings>Keybinds menu
2. Change the value for the

### Expected Behavior

No menu should open, unless the parameters for the window (size, coordinates, etc.) have NOT been set yet. 

### Actual Behavior

Changing the secondary trigger key sometimes opens the "customize this keybind’s action" menu, and other times it doesn’t. I’m not sure what triggers this and whether or not it is intended or not, but it definitely is unnecessary. It actually forces the user to close the keybind's action menu before moving on. 

### macOS Version

Sequoia 15.0 Public Beta 8

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
This should fix that bug!
[Loop.zip](https://github.com/user-attachments/files/16981041/Loop.zip)

**Comment by greg1075** [comment]
Can't launch. 
<img width="372" alt="Screenshot 2024-09-12 at 9 46 22 AM" src="https://github.com/user-attachments/assets/523ed2a8-3302-4b80-82bf-99967307bd4e">

**Comment by greg1075** [comment]
Nevermind - I was able to bypass the security message above by authorizing Loop in Privacy & Security. To all users, note that you will need to remove and re-add Loop in the Accessibility menu for it to work correctly.
