### ISSUE TITLE
🐞 Loop is in Chinese when my OS is in French

### ISSUE THREAD

**Issue by lordfpx** [MrKai77/Loop#555]
### Bug Description

Since a certain version (sorry, I don't know wich one), Loop is in Chinese and I can't find a way to set it into English for exemple.

### Steps To Reproduce

1. I installer Loop some times ago, it was in English and it was fine
2. One day, It gets updated and turned into Chinese
3. I can't put it back to English from now
4. I tryed to uninstall Loop and reinstall it, it's still in Chinese

### Expected Behavior

By default it should follow OS language with a fallback to English.

### Actual Behavior

I can't change actual language from Chinese to English

### Screenshots

<img width="764" alt="image" src="https://github.com/user-attachments/assets/e612c7a7-3af4-468c-8dba-4417bd941c08">

### macOS Version

Sonoma 14.6.1

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
That's odd, can you try the latest development version by enabling this toggle:
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/4497c033-72a6-44ba-be1a-05816f08558d">

**Comment by lordfpx** [comment]
@MrKai77 it's now Version 🧪 1.1.0 (1287), but I sill got the same issue :-(

**Comment by SenpaiHunters** [comment]
System Settings → General → Language & Region → Applications → + button → Add Loop and put it in either system default or to follow a specific language → Relaunch loop

**Comment by lordfpx** [comment]
Thanks @SenpaiHunters , that worked!
I might have found the origine of the issue. I've 2 languages configured, the primary one is French, the other one being traditional Chinese. 
When I added Loop into the Applications list, the default selected language was Chinese, maybe because French is not available?
Thanks anyway, that fixed my problem!
