### ISSUE TITLE
🐞 Custom cycle bug on Sequoia

### ISSUE THREAD

**Issue by greg1075** [MrKai77/Loop#557]
### Bug Description

Custom cycle keybind: Set custom windows sizes to cycle though closes window settings window back to cycle settings.

### Steps To Reproduce

1. Add custom keybind
2. Set to "Cycle"
3. Add cycle item
4. Set to "Custom"
5. Click "Size" 
6. Click on Width or Height and type a number, or enable "Use Pixels" 

### Expected Behavior

User should be able to keep editing settings without the menu window closing 

### Actual Behavior

Windoe menu closes

### macOS Version

Sequoia 15.0

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Update to the newest dev branch, should be fixed

**Comment by greg1075** [comment]
Thanks! It looks like the latest main release 1.1.1 also incorporates the fix. Cheers.
