### ISSUE TITLE
🐞 Pressing trigger key after clicking on desktop triggers alert sound

### ISSUE THREAD

**Issue by greg1075** [MrKai77/Loop#561]
### Bug Description

Pressing the trigger set in Loop > Keybindings while the desktop/Finder is the focused application triggers the system alert sound.  

### Steps To Reproduce

1. With Loop open, click on desktop
2. Press Loop trigger key

### Expected Behavior

No sound trigger

### Actual Behavior

Pressing the trigger set in Loop > Keybindings while the desktop/Finder is the focused application triggers the system alert sound.  

### macOS Version

macOS Sequoia 15.0 (24A335)

### Loop Version

Version 1.2.0 (1298)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
If there is no window focused, Loop will play an alert sound indicating that there is no window to be resized. However, are you facing this with finder _windows_ focused as well?

**Comment by greg1075** [comment]
Just when there is no window focused, sorry for the confusion. I don't remember this happening before, so I thought that was introduced in one of the recent updates.

That said, I'd suggest removing the alert altogether. I don't find particularly useful (if no window is focused, nothing happens and that's that). It is also annoying to have the alert triggered every time I use a keyboard shortcut that uses the same trigger key.  Ex: I use the left command key to trigger Loop keybinds, which means that the alert sound is triggered every time I invoke spotlight (command + space) and a few other shortcuts that uses the left command key.

**Comment by MrKai77** [comment]
Actually, that makes a lot of sense. Even a visual indicator on top of the radial menu indicating that there's not a focused window makes more sense than producing sound!

**Comment by greg1075** [comment]
I use Spotlight dozens of times a day, and getting the alert sound every time was getting pretty annoying. For now I've turned its volume all the way down. Looking forward to a fix soon :)
