### ISSUE TITLE
🐞 Loop shortcuts stop working until I open loop again

### ISSUE THREAD

**Issue by kiranjd** [MrKai77/Loop#564]
### Bug Description

I keep having to open loop and then close it(cmd + w) when the shortcut does not work. This happens randomly even when the app is not quit. I have checked that `Launch at login` is checked as well

### Steps To Reproduce

1. Open Loop - shortcuts work fine as expected with radial menu
2. After a while it stops working
3. Reopen Loop and then close the window to have it working again

### Expected Behavior

Should always respond to shortcut keys

### Actual Behavior

Shortcuts do not work

### macOS Version

Sonoma 14.6.1

### Loop Version

1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Update to the newest dev branch and see if this still happens

**Comment by kiranjd** [comment]
As in switch to dev and build binaries there?

**Comment by SenpaiHunters** [comment]
![001389-09@2x](https://github.com/user-attachments/assets/6a6eaa4f-c7c3-4ef5-a1da-d4c765c16f15)

**Comment by mahaonanStart** [comment]
I have updated to the latest version. Why can't these shortcut keys below be used?
<img width="463" alt="image" src="https://github.com/user-attachments/assets/faba3c93-3467-4112-83a8-dd4f28760f38">

**Comment by SenpaiHunters** [comment]
@mahaonanStart make a new issue, do not comment on others. Provide detail when creating your issue.

**Comment by kiranjd** [comment]
Thanks @SenpaiHunters. I have enabled dev mode. Did not face issues after it. I will close the issue after using the app for a day

**Comment by MrKai77** [comment]
@kiranjd any updates on this?

**Comment by kiranjd** [comment]
This is working fine.
