### ISSUE TITLE
🐞 Crash when minimizing or hiding an app with an keybind

### ISSUE THREAD

**Issue by L1am-cd** [MrKai77/Loop#573]
### Bug Description

When having a keybind set to either hide, or minimize an app, Loop crashes instantly.

### Steps To Reproduce

1. Keybind to minimize or hide app
2. Use Keybind on any app

### Expected Behavior

To hide or minimize any app without crashing Loop.

### Actual Behavior

Loop crashed instantly without minimizing or hiding any app.

### Screenshots

https://github.com/user-attachments/assets/fb306147-5083-44d4-8af3-03075125976f

### macOS Version

Sequoia 15.0

### Loop Version

🧪 1.2.0 (1327)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Found a fix! Hopefully will be included in the next prerelease :)
