### ISSUE TITLE
🐞 Percentage position not working as expected

### ISSUE THREAD

**Issue by jrobinson-uk** [MrKai77/Loop#581]
### Bug Description

I've been playing with loop and love it.
I've set up some custom keybindings for my home setup based on position but want to more them the using percentages so that they scale appropriately when I connect to other screens

I've tested this with a single keybind which should occupy the lower right 6th of the screen (33% width, 50% height) but the percentage postioning isn't working as expected

### Steps To Reproduce

Create custom keybind with 50% height and 33% width, positioned at 67%, 50%
![Screenshot 2024-10-01 at 08 56 44](https://github.com/user-attachments/assets/22f5b793-5009-4b61-ac9f-fc3db1a154a6)
![Screenshot 2024-10-01 at 08 57 32](https://github.com/user-attachments/assets/057429a5-8907-471a-9e2e-ed941c592f4d)

### Expected Behavior

To create the expected behaviour I have to set the position height to 31% rather than 50%
![Screenshot 2024-10-01 at 08 57 54](https://github.com/user-attachments/assets/56c930a8-2ffb-478b-a340-717748f5de47)

### Actual Behavior

Keybind is positioned off the screen
![Screenshot 2024-10-01 at 08 56 44](https://github.com/user-attachments/assets/3b3912c9-8305-445e-950b-8a48921610a7)

### macOS Version

Sonama 14.7

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by ShawnZhong** [comment]
I am seeing the same issue with the Y coordinate.
