### ISSUE TITLE
🐞 Background noise when moving mouse 

### ISSUE THREAD

**Issue by EranNL** [MrKai77/Loop#582]
### Bug Description

After updating to version 1.2.0 (I am including development versions) I noticed some strange noice when hovering over the window. I have no idea whether it was there before the update and the app is of course still usable, but I still wanted to let it know. 

### Steps To Reproduce

1. Update the app probably
2. Move your mouse around

### Expected Behavior

I expected no noise in the background

### Actual Behavior

There is noise in the background when moving the mouse. It is more noticeable when the window is opened over a bright background

### Screenshots

https://github.com/user-attachments/assets/0dc6bc06-ac24-4485-8e24-4ede183b9b68

### macOS Version

MacOS Sequoia Beta 15.1

### Loop Version

1.2.0 (1333)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Thanks for the bug report! Unfortunately, this is an issue with macOS, so it seems to be impossible to fix from my side :(
I will be closing this issue for that reason. However, correct me if I was wrong!
