### ISSUE TITLE
Add more components on the header section

### ISSUE THREAD

**Issue by ishapandey007** [MrKai77/Loop#589]
### Feature Request Description

We can provide home, contact and other additional components on the header. And there is only release notes as a header component and when we click on it we remain in the same page with same details which makes no sense. Instead we first make home page and then other pages. And provide all these components on the header section so that it can be more attractive and responsive.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [X] I can help with the improvement or development of this feature (tick if you can help)

**Comment by SenpaiHunters** [comment]
I'm a bit confused. Could you clarify what you mean by "header section"? Are you referring to the README? Please rephrase your request for clarity.

**Comment by ishapandey007** [comment]
![Screenshot 2024-10-07 195623](https://github.com/user-attachments/assets/200d6c3b-d3c8-409f-b005-bb106ab194da)
The top most portion. It is looking empty. We can add more components such as Home, Contact and others.

**Comment by ishapandey007** [comment]
And when we click on "Release Notes" we remain in the same page with same details which makes no sense.
