### ISSUE TITLE
🐞 Square box around setting tabs after upgrading to 1.2.0 (1356)

### ISSUE THREAD

**Issue by ShawnZhong** [MrKai77/Loop#590]
### Bug Description

See the screenshot above. There is a square box around the setting tab "Icon", and it does not disappear after opening other tabs. 

### Steps To Reproduce

Open the settings. 

### Expected Behavior

Only see the rounded corner for setting tab text. 

### Actual Behavior

Square box displayed

### Screenshots

<img width="673" alt="image" src="https://github.com/user-attachments/assets/c8092c90-8295-43bb-8d17-9786b42da7a7">

### macOS Version

15.1 Beta

### Loop Version

1.2.0 (1356)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by ShawnZhong** [comment]
One can press TAB to move the focus box around, but it's not going away. 

<img width="663" alt="image" src="https://github.com/user-attachments/assets/9f125220-e7ee-4dc0-9b1a-24b4da7366f7">

Might be related to https://github.com/MrKai77/Loop/commit/5e57d6a1dc5c0b8ad8ad67e6b5f559cc91985a8a

**Comment by MrKai77** [comment]
Actually, I've had other people report this bug before as well, but have never found a way to reproduce it. I have a feeling that his may be caused by the system. Are you aware of any settings that might cause this bug?

**Comment by MrKai77** [comment]
Ah, actually, I found the cause, and it was much more obvious than I previously thought 😅
<img width="482" alt="image" src="https://github.com/user-attachments/assets/05cfb6bb-e500-4017-8458-29d4aa230b88">
I will try modifying the code to make Loop work better with keyboard navigation :)

**Comment by ShawnZhong** [comment]
I can confirm that the highlighted box disappears after disabling the "Keyboard navigation" option in the system settings and restarting the application. It's unclear to me whether this option is enabled by default, and I don't recall changing it either.

**Comment by MrKai77** [comment]
Should be fixed in the latest development build. Can you confirm this?

**Comment by ShawnZhong** [comment]
I don't see a new dev build coming out. The latest one is still 1.2.0 (1356).

**Comment by MrKai77** [comment]
I have just triggered a new dev build, should be out soon!

**Comment by MrKai77** [comment]
Update: Apple's notarizations servers are currently down, will try and publish it tomorrow 😓

**Comment by ShawnZhong** [comment]
I switched to the dev branch and manually updated the Luminare dependency. It works as expected right now. Thanks for fixing!
