### ISSUE TITLE
✨ Integration with native snapping in Sequoia

### ISSUE THREAD

**Issue by shirok1** [MrKai77/Loop#593]
### Feature Request Description

I like the UX of Loop, which is much better that dragging windows to edges.

But native snapped windows have a little bar in the middle that can be dragged to resize both windows at the same time. I want windows snapped by Loop be able to adjust using that UX from system, by providing system essential infos.

Since Loop (at least can be configured to) be state-less, I think it can live happily with native snapping?

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
Yes, with the 1.2.0 developer build, there is an option in the advanced tab to use the system window manager when available! This will allow you to use the system window dragging bar as well :)

**Comment by shirok1** [comment]
Cool! Should I leave this request open til 1.2.0 be shipped?
