### ISSUE TITLE
✨ Allow the window position commands to move to next screen

### ISSUE THREAD

**Issue by raphaelluethy** [MrKai77/Loop#594]
### Feature Request Description

In magnet, there is the QOL function that the positional functions like left half, right half, upper right quarter, etc are able to go to the next window.
I could not find a way to replicate this behavior, except having a keybind for left-half and a separate one for switching windows (with keybinds only).

If I did not find this function somehow, I am sorry for the skill issue...

Thanks!

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
If I'm understanding correctly, your title is asking for an action to change a window's screen from Loop? Those options exist:
<img width="379" alt="image" src="https://github.com/user-attachments/assets/4f77cb46-44fa-4ffa-9ee0-34bca3ba50f1">

As for your description:
>In magnet, there is the QOL function that the positional functions like left half, right half, upper right quarter, etc are able to go to the next window. I could not find a way to replicate this behavior, except having a keybind for left-half and a separate one for switching windows (with keybinds only).

I'm not sure I fully understand, would you be able to elaborate?

**Comment by raphaelluethy** [comment]
Hi there, thanks for asking.
I think I should have added some images, so here they are:

Consider there are 2 screens (screen 1 and 2 in black) and my app window, set on the left half of screen 2:
![CleanShot 2024-10-14 at 22 05 06@2x](https://github.com/user-attachments/assets/709d2ff3-35bc-466c-ba95-db4bf74508e2)
If I now invoke the `left half of the screen` action again, it would lead to the following state:
![CleanShot 2024-10-14 at 22 06 42@2x](https://github.com/user-attachments/assets/eefe9ac6-a5bf-4beb-a10f-50b6f7df0524)
And another invocation would then lead to the final (desired) state:
![CleanShot 2024-10-14 at 22 10 57@2x](https://github.com/user-attachments/assets/1b6f3128-9f1c-4134-b67c-c5a300be1e2f)


If something like that would ne possible, that would be really neat!

**Comment by MrKai77** [comment]
Alright, so as I was preparing a demo, I found a bug that was preventing this, so I went ahead and fixed it in this build: 
[Loop.zip](https://github.com/user-attachments/files/17369265/Loop.zip)

After installing build, make a cycle keybind with this configuration:
<img width="511" alt="image" src="https://github.com/user-attachments/assets/b166e262-acd8-47ed-85b8-976b716eba34">
And it should work!

**Comment by raphaelluethy** [comment]
perfect, it works now. Thanks a lot :)
