### ISSUE TITLE
🐞 Icon for Cycles

### ISSUE THREAD

**Issue by ShawnZhong** [MrKai77/Loop#597]
### Bug Description

I am not sure what the expected icon for cycles is. It seems to be pretty random right now. 

### Steps To Reproduce

1. Add a new cycle: the initial icon is an empty box
2. Click "Add"
3. Select an action, say "Fullscreen": the icon is still empty
4. Click "Add" again: the icon shows fullscreen
5. Select another action, say "Center": the icon now becomes empty again
6. Remove the "Center" action: the icon now shows "Center", which does not exist at this point

### Expected Behavior

I am not sure. 

### Actual Behavior

See below

### Screenshots

![Untitled](https://github.com/user-attachments/assets/34911d31-9510-4945-a4f1-b4422ead1531)

<img width="448" alt="image" src="https://github.com/user-attachments/assets/cd41d366-4d3b-469a-b5c1-8eedef47a41b">

### macOS Version

15.1 Beta

### Loop Version

1.2.0 (1356)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Interesting, the intended behavior for the cycle icon is to reflect the first action inside the cycle, but I can see that is not happening in your ticket 🤔
I'm guessing that this is a bug caused by a missing change observer for the keybind value, which causes the icon to not be updated in real time.
