### ISSUE TITLE
🐞 Loop crashes when trying to use Loop to move the Loop window with focus on another screen

### ISSUE THREAD

**Issue by Tgist1024** [MrKai77/Loop#599]
### Bug Description

When attempting to use Loop to move its window while the focus is on a window on a different screen, Loop crashes.

### Steps To Reproduce

1. open Loop
2. open Loop window
3. open Loop option "Resize window under cursor"
4. open any else window like "Chrome" on another screen
5. click the "Chrome" window to focus on it
6. move the cursor on the Loop window
7. use Loop on it(with "Resize window under cursor")

### Expected Behavior

it should work fine as expect.

### Actual Behavior

Loop just crash.

### Screenshots

![QQ_1729066548221](https://github.com/user-attachments/assets/b6ecda9b-071a-4f76-97b4-76488394f6d1)

https://github.com/user-attachments/assets/0c76ad14-a048-4e33-aa64-fd5841dad7c0

### macOS Version

Sequoia 15.0.1

### Loop Version

Version 1.1.1

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
That's very odd! Can you check if this can be reproduced this in the latest development build?

**Comment by Tgist1024** [comment]
Tested it, and the issue isn’t present in the development version 1.2.0. Should I close the issue?

**Comment by MrKai77** [comment]
Yep!
