### ISSUE TITLE
🐞 Custom Keybindings - Window closes unexpected

### ISSUE THREAD

**Issue by gnewmann** [MrKai77/Loop#600]
### Bug Description

When I add a "Custom Keybind" to my Cycle the window for the Custom Keybind closes, after typing one letter or changing one of the attributes. I need to open the custom windows 3 times, to type in a width "100".

### Steps To Reproduce

1. Open Keybindings
2. Open the Right Cycle Keybind
3. Add a custom Keybind 
4. Try to modify the Custom Keybind

### Expected Behavior

The window should not close and stay open.

### Actual Behavior

The window closes as soon as I type in something or change an attribute

### macOS Version

Sequoia 15.0.1 (24A348)

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Can you see if you can reproduce this in the latest development build?

**Comment by gnewmann** [comment]
Thank you! It is fixed in the development build!
