### ISSUE TITLE
🍱 Add Daylight

### ISSUE THREAD

**Issue by 0w0x** [MrKai77/Loop#603]
### Icons

![daylight_1024](https://github.com/user-attachments/assets/94b14c40-c140-4626-b52d-73aa4791e21e)

### Comments

Loop ring over clouds

### Final Checks

- [X] My suggestion is written in English
- [X] I am submitting an icon (this is not for icon requests)

**Comment by MrKai77** [comment]
Hey @0w0x, thanks for your submission, looks great!! Just one request though, would you be able to add some more depth to the icon, to look a bit more like system macOS icons? Currently, it has more of a flat design, which looks more like an icon for iOS. This can be done by adding drop shadows, or even adding a shining ring around the radial menu as done in the "Classic" Loop icon.

**Comment by 0w0x** [comment]
Thanks for the feedback @MrKai77. I made a few quick changes but I still don't think there's enough depth to ring itself. Is this moving in the right direction?

![daylight2_1024](https://github.com/user-attachments/assets/541c917e-f720-4150-9b47-76565d531069)

**Comment by MrKai77** [comment]
Definitely looks better than the first iteration! Maybe you can take some inspiration from our [Figma](https://www.figma.com/design/vQbpZkyY7SG9q6V72fOn2R/Loop-Icons?node-id=0-1&t=HJ30AVWYqHi1aW2b-1), such as the glowing radial menu selection, or the radial menu feather before the border. But otherwise, this is looking great!

**Comment by 0w0x** [comment]
Thanks for your support! I'm new to icon design so this is a great help. Using some of the Figma designs as a base for the menu shadow and glow I've got three icons that might work. Let me know which one I should continue iterating on.

![image](https://github.com/user-attachments/assets/64a3e2ab-e14d-42bb-9913-5d902e437ca1)

**Comment by MrKai77** [comment]
I like both the top ones! Maybe continue iterating on the top right icon as the drop shadow is less intense, which interferes less with the background?

**Comment by 0w0x** [comment]
Thoughts on these? The one on the right doesn't interfere with the background as much but still has a subtle drop shadow.

![image](https://github.com/user-attachments/assets/8f84d579-a2dc-4c2d-9997-cee85382a2ca)

**Comment by MrKai77** [comment]
I like the one on the right! Is there anything else you wanted to add? Maybe birds could make a good easter egg if you can fit them in small enough (although don't do that if it makes the icon worse)?

**Comment by 0w0x** [comment]
Thanks for the feedback. Here's the final PNG. 
I tried adding in birds but there's no space to put them without it looking weird when viewed at a smaller size.
![daylight3_1024](https://github.com/user-attachments/assets/5e77407b-5354-45c5-9ae0-75d5686ecf9c)

**Comment by MrKai77** [comment]
Sweet, thank you so much! I will add it in soon!

**Comment by MrKai77** [comment]
Also, did you design this icon in Figma? If yes, I would appreciate it if you could share the link with me, as I can add it into the official Loop Icons Figma (the one I shared earlier) as well! If not, I can just add a png of the icon above too.
