### ISSUE TITLE
🐞 Adding Custom Keybind in Cycle Doesn't Work

### ISSUE THREAD

**Issue by um-jglad** [MrKai77/Loop#608]
### Bug Description

When attempting to add a custom keybind/layout to a cycle, the UI for the custom keybind closes the first time you click a UI element.

### Steps To Reproduce

1. Create or modify a cycle keybind
2. Add a **custom** keybind to the cycle
3. Attempt to setup the custom keybind by setting coordinates/size

### Expected Behavior

UI for custom keybind should remain open to allow setting of location and size.

### Actual Behavior

Custom Keybind UI closes and returns to cycle setup UI, effectively only allowing you to set one aspect of the custom keybind.

### Screenshots

![loop_custom_cycle_bug](https://github.com/user-attachments/assets/ac609976-effe-4402-b07e-ac52eaaca48c)

### macOS Version

Sequoia 15.1 (24B83)

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
The latest developer version will fix this! You should be able to update from Loop's about section.
