### ISSUE TITLE
✨ Next screen support move whole Application with additional modify key

### ISSUE THREAD

**Issue by yinheli** [MrKai77/Loop#617]
### Feature Request Description

Currently, "Next screen" only supports moving the current window to the next monitor. If a modifier key could be added, when it is pressed, all windows of the entire app will be concentrated on "Next screen".

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
I believe that this is a duplicate of #324.
