### ISSUE TITLE
🐞 Keybinds not working any more?

### ISSUE THREAD

**Issue by domiheyLA** [MrKai77/Loop#620]
### Bug Description

I've been using Loop for months without issues. I had it working with trigger keys "left option" + "left cmd" and keybinds using arrow keys. However, since a few days / weeks its not working any more. I seem to be unable to change the keybinds any more in the settings. The only thing that still works is trigger key + mouse.

Is this just me or was something changed?

### Steps To Reproduce

keybind not working any more, only mouse

### Expected Behavior

arrow keys can be used as keybinds

### Actual Behavior

i just hear the mac OS sound if something is clicked without action

### macOS Version

Sonomo 14.6.1

### Loop Version

1.1.1

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
That is very odd, nothing should have been changed. My first recommendation would be to remove Loop from the accessibility settings in System Settings, relaunching Loop, then re-grant accessibility access when prompted. If that doesn't fix it, try updating to the latest developer version and see if the issue persists there.

**Comment by domiheyLA** [comment]
Unfortunately, it did not work. I guess i have to settle with only the mouse working for now (which is also ok). It is probably something on my side, but I can't figure it out. Thanks for you help anyway.

**Comment by domiheyLA** [comment]
@MrKai77 It randomly worked again :) So happy.
