### ISSUE TITLE
✨ Next release version

### ISSUE THREAD

**Issue by debuxxed** [MrKai77/Loop#624]
### Feature Request Description

Sorry for a somewhat offtopic question, but would we get new compiled release version or do we compile ourselves from sources?

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [X] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
No problem, I've been quite busy lately, but am planning to release 1.2.0 soon! In the meantime, you can turn on development updates and you will be able to update to the latest signed update :)

**Comment by debuxxed** [comment]
> No problem, I've been quite busy lately, but am planning to release 1.2.0 soon! In the meantime, you can turn on development updates and you will be able to update to the latest signed update :)

sorry, how do i turn dev updates on. I use homebrew, couldn't find any info of it

**Comment by SenpaiHunters** [comment]
@offeex inside loops settings

![003269-12@2x](https://github.com/user-attachments/assets/6f101619-0a21-490d-960c-efc8b5a2c61d)
