### ISSUE TITLE
🐞 [Title here]

### ISSUE THREAD

**Issue by QJHWC** [MrKai77/Loop#625]
### Bug Description

录屏后找不到文件在哪个位置

### Steps To Reproduce

录屏之后找不到文件

### Expected Behavior

在文件里可以直接打开保存位置

### Actual Behavior

我真的找不到

### macOS Version

15.1.1

### Loop Version

1.2.0

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Please re-submit your issue in English.

**Comment by QJHWC** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/deleting-an-issue
Can you delete the issue by following this tutorial? Thank you. Now the loop project has been in my project repository. I hope you can help delete the issue.
