### ISSUE TITLE
🐞 Screen switching not working when macOS window manager enabled

### ISSUE THREAD

**Issue by misaka** [MrKai77/Loop#632]
### Bug Description

The "Next screen" and "Previous screen" commands do not move the currently focused window, despite the preview showing correctly.

### Steps To Reproduce

Requires a multiple-screen setup.

1. Bind a key to "Next screen" or "Previous screen"
2. Press the appropriate key(s); note that the preview window appears on the other screen. Release.
3. 💥 Currently focused window moves to the center of the current screen.

### Expected Behavior

The currently focused window moves to the new screen.

### Actual Behavior

The currently focused window stays on the screen it was on, but moves and resizes to the position and size it would have taken on the other screen.

### Screenshots

Not sure how to screen-record multiple screens, if anyone can provide instruction I can give it a go.

### macOS Version

Sequoia 15.1.1

### Loop Version

🧪 1.2.0 (1381)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [X] I can help with fixing or developing this issue (tick if you can help).

**Comment by misaka** [comment]
Oh! Sorry, on a whim I disabled the option "Use macOS window manager when available" and this now works! Should this still work when that option is enabled? I'm not even clear on what it does.

**Comment by MrKai77** [comment]
Hey sorry for the late response! Just fixed this, and will be released in the next development version :)
