### ISSUE TITLE
✨ Needs more options for ultrawide monitors

### ISSUE THREAD

**Issue by mortenscheel** [MrKai77/Loop#635]
### Feature Request Description

On ultrawide monitors, it would be nice if we could get more options than halves, thirds and quarters.
The layout I currently prefer looks like this:
```
+------------+------------------------+------------+
|            |                        |            |
|            |                        |            |
|            |                        |------------|
|            |                        |            |
|            |                        |            |
+------------+------------------------+------------+
```
- Left quarter width, full height
- Center, half width, full height
- Top right quarter width, half height (top right eight)
- Bottom left quarter width, half height (bottom right eight)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by transportrefer** [comment]
Have you even looked at the settings? You can customize the window size and position as you wish.

**Comment by ageorgios** [comment]
@transportrefer where is that exactly ?

**Comment by plyght** [comment]
> @transportrefer where is that exactly ?
>
@ageorgios see the video below:

https://github.com/user-attachments/assets/ab35d173-89ff-4067-8818-a13b2565fd71

**Comment by ageorgios** [comment]
awesome thank you very much!

**Comment by plyght** [comment]
@MrKai77 @mortenscheel this issue can be closed, as it has been resolved.
