### ISSUE TITLE
🐞 Can't update to development version

### ISSUE THREAD

**Issue by transportrefer** [MrKai77/Loop#637]
### Bug Description

Nothing happens when I click "restart to complete". The program doesn't update to the development version.

![image](https://github.com/user-attachments/assets/11d01ea7-91cf-4a60-a02e-b214d9108408)
![image](https://github.com/user-attachments/assets/30e968f1-dfbe-4d1c-af5e-84029c85128c)

### Steps To Reproduce

1. Check "Include development versions"
2. "Check for updates"
3. "Install"
4. "Restart to complete"

### Expected Behavior

Expecting update to development version.

### Actual Behavior

Nothing

### macOS Version

Sequoia 15.3 Public Beta 

### Loop Version

1.1.1.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Alright, this may have been a bug in 1.1.1. Can you manually update to the development version of 1.2.0 and report back if it happens again?

**Comment by transportrefer** [comment]
Constantly asks me to update to 1.3 and when I click to update, it restarts but nothing updates.
