### ISSUE TITLE
🐞 Resetting keybinds only updates the UI after restarting

### ISSUE THREAD

**Issue by injust** [MrKai77/Loop#639]
### Bug Description

Loop needs to be restarted after resetting keybinds for the new keybinds to reflect in the UI, even though they already work.

### Steps To Reproduce

1. Configure some keybinds
2. Go to the Advanced section and reset your keybinds
3. Go back to the Keybindings section -- nothing has changed, but your custom keybinds don't work and the default ones work again

### Expected Behavior

The UI should update with the new reset keybinds.

### Actual Behavior

The UI still shows the old keybinds.

### macOS Version

Sequoia 15.2

### Loop Version

Version 1.1.1 (1259)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Hey @injust, thanks for all your bug reports/feature requests!!
As for this issue, I believe that the latest development version should fix this, would you be able to update and try again?

**Comment by injust** [comment]
Sorry I wasn't able to test sooner! I just updated to 1.2.0 (1383) and this is the behaviour I observed:

- If I start Loop and go directly to Advanced to reset the keybinds, it reflects immediately
- If I opened the Keybinds section before resetting them, it only reflects after a restart

Hopefully that aligns with your fix.

**Comment by MrKai77** [comment]
Ah yes so here's an update:
While writing the PR I just merged above, I *did* notice that the reset button doesn't tell the keybinds tab to refresh. So I fixed that :)
There should be a new development build released reflecting these changes in a few minutes!
