### ISSUE TITLE
✨ "Remind me later" text should change after update is installed

### ISSUE THREAD

**Issue by injust** [MrKai77/Loop#649]
### Feature Request Description

After installing an update, you are prompted to restart Loop. However, the "Remind me later" button is still there.

As the latest version has already been installed, I'm assuming that it will never actually remind you. (I couldn't verify this, but that's how it works for most macOS app updaters, and pressing "Check for updates..." shows no available updates.)

Maybe the button text should change to "Restart later" or "I'll restart later", as that seems more accurate.

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
Good point!
Actually, a better option may be to simply disable the option (and grey it out) or remove the button once the update has been installed

EDIT: actually I like your idea more, will test it :)
