### ISSUE TITLE
🐞 Keybinding import/export bug.  1.2.0 (1401)

### ISSUE THREAD

**Issue by Fred-IV** [MrKai77/Loop#652]
### Bug Description

2 dev builds have come out today, and as I was about to report the issue on the first one, another update came along, so I tried it too, and same problem.
I export my keybindings on one Mac, and try to import on the 2nd Mac, and they are all wrong.
It changed the 3 key combo (ctrl, cmd, alt) to fn.
I don't have a Mac fn key on my keybopards.
So, I am using the 3 modifier keys and the keypad.
To move the windows top, bottom, left, right, corners, and center.
When I import the file on the 2nd Mac, they are all wrong.

Source Mac is on Sonoma 14.7.1
Destination Mac is on Sequoia 15.2
Both are on Loop  1.2.0 (1401)

### Steps To Reproduce

1. Export keybinds on one Mac
2. Import keybindings on 2nd Mac.
3. See failure.
4

### Expected Behavior

For the keybindings to be correct.

### Actual Behavior

Changes the 3 modifier keys to a non-existent mac-fn key.

### Screenshots

[Loop Keybinds.json.zip](https://github.com/user-attachments/files/18268762/Loop.Keybinds.json.zip)
![image](https://github.com/user-attachments/assets/19ed3e2e-4466-4512-9683-b5e31db4f09e)
![image](https://github.com/user-attachments/assets/bdce4208-a662-4096-b78a-1016b288a764)

### macOS Version

15.2 (24C101)

### Loop Version

 1.2.0 (1401)

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by Fred-IV** [comment]
It looks like the problem is that is is NOT saving and loading the correct trigger key.

**Comment by MrKai77** [comment]
The trigger key currently doesn't save in the exported keybinds file. But that would make sense, will try and implement this tomorrow!

**Comment by Fred-IV** [comment]
I got the update, and tried it, but now it crashes after the import.
I tried 3 times, all 3 crashed, but it looks like it did take the trigger change, so I think it crashes after the import works.
I submitted all crashes and clicked reopen. When I reopened, and checked, the trigger key was changed.

**Comment by MrKai77** [comment]
Would you be able to send your keybinds file here? I will try importing it on my end. (from the latest version, unlike the one in your original report?)

Edit: or is this happening when importing the original file?

**Comment by Fred-IV** [comment]
I just verified, and it's the same as the first zip I sent. No changes.

**Comment by MrKai77** [comment]
Try the latest development build, should be fixed now!

**Comment by Fred-IV** [comment]
so far, so good...

thanks, I'll report anything new if it comes up.
