### ISSUE TITLE
✨ Double tapping left/right to split into thirds

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#66]
### Feature Request Description

I think it would be nice to allow a toggle to double tap left/right to act as super+L/J respectively. This way users can split into horizontal thirds without moving their fingers from the arrows/WASD.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup! This has already been implemented in #54, but it hasn't made its way into a release yet! I'm hoping to release beta 11 within the next few days, so stay tuned!
