### ISSUE TITLE
🐛 Trigger Key and conflicts

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#74]
### Bug Description

Loop gets triggered whenever the trigger key is pressed alone or in combination with other keys; this frequently conflicts with other keybindings, making them unusable.

### Steps To Reproduce

1. Set Trigger Key to left <kbd>Command</kbd>
2. Open Safari
3. Try to open a new tab with left <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>

### Expected Behavior

Loop should let me open a new Safari tab

### Actual Behavior

Loop intercepts the key and makes <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> impossible, since pressing <kbd>Command</kbd> alone triggers the app

### MacOS Version

Sonoma 14.0 (23A344)

### Loop Version

1.0.0-beta.11 (465)

### Additional Context

I'm using <kbd>Caps Lock</kbd> as <kbd>Hyper Key</kbd> (<kbd>⌃</kbd><kbd>⌥</kbd><kbd>⌘</kbd><kbd>⇧</kbd>), and every time I press it, Loop gets triggered and I can't call my custom key bind (if Loop is set to any keys in the left side of the keyboard).

It would be nice to make Loop recognize when its key is being used alone or when a combination of keys is pressed so it won't get triggered, paired with the option to remove the trigger key altogether or set it to multiple trigger keys instead of just one.

I know there's the option to make the trigger key only work when it's double pressed – and this partially solves the issue – but I'd love to use <kbd>Hyper Key</kbd> for Loop. However, I don't know if that would be feasible since it invokes Loop and takes control of that key combination. I'm not informed enough to understand what is happening under the hood, but apps like Moom or Rectangle do not conflict with other apps in which I'm using the <kbd>Hyper Key</kbd> such as Raycast or macOS System Settings.

Perhaps if it's just the Radial Menu, add an option to disable it or activate it only when the Keybinds are pressed? So you'll be able to see the preview anyway but it won't affect other key combinations.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
> Perhaps if it's just the Radial Menu, add an option to disable it or activate it only when the second key is pressed? So you'll be able to see the preview anyway but it won't affect other key combinations.

Interesting approach! I'll look into this! This should indeed allow the user to use other keybinds in other apps!
As for the <kbd>Hyper Key</kbd>, I'll have to intestigate that too! Making sure that it's pressed alone should work!

EDIT: I'll be working on this once I get #75 done!

**Comment by Zabriskije** [comment]
Edit: I had read the description of my issue again and found that instead of "second key" I meant "Keybinds" (last sentence), so I fixed it.

**Comment by MrKai77** [comment]
Thanks! 
Just letting you know that this issue is my priority for Loop right now. 
Unfortunately, I've been quite busy lately, but I assure you that I am committed to implementing this as soon as my schedule allows for it :)

**Comment by Zabriskije** [comment]
No pressure. It's already great to see so much passion and dedication :)
Stars keep coming, so it's a matter of time until someone lends an extra hand.

**Comment by MrKai77** [comment]
Alright, here's a build that should work! You can find the setting under the "Radial Menu" tab of the settings window.
[Loop.zip](https://github.com/MrKai77/Loop/files/13721471/Loop.zip)

**Comment by Zabriskije** [comment]
Conflicts with other keys are gone, but now `Middle-click to trigger Loop` doesn't work/show up anymore until you press a direction key. When `Hide until direction is chosen` is disabled, the radial menu shows up but still doesn't work with the mouse until you press a direction key.

![Middle-click bug](https://github.com/MrKai77/Loop/assets/101254295/dff60b4e-e7a8-4a79-8a8d-536dc30adc10)

**Comment by MrKai77** [comment]
I can't believe that the fix was a in a single line of code 😂
But now it works! Here's the latest build: 
[Loop.zip](https://github.com/MrKai77/Loop/files/13746781/Loop.zip)

**Comment by Zabriskije** [comment]
`Middle-click to trigger Loop` seems to work fine now, but when `Hide until direction is chosen` is enabled, `Window
Snapping` keeps showing the preview until another middle-click action is made.

![Window Snapping bug](https://github.com/MrKai77/Loop/assets/101254295/b76e8d5f-ce07-42d4-a646-09c95ebaedea)

**Comment by MrKai77** [comment]
Fixed!
[Loop.zip](https://github.com/MrKai77/Loop/files/13753599/Loop.zip)

**Comment by Zabriskije** [comment]
Everything seems to work properly 🥳 good job!
