### ISSUE TITLE
✨ Option to hide Loop icon in menu bar

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#78]
### Feature Request Description

For a tidy and clean menu bar :)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Makes sense! However, once menubar icon is gone, what would be the most optimal way for the user to open Loop's settings? Or would it make sense to just show the settings window on app launch (as long as it didn't launch at login)?

**Comment by Zabriskije** [comment]
Yup, opening the app again to change settings it's the common way.

**Comment by JaceThings** [comment]
Think this can be closed now

**Comment by MrKai77** [comment]
> Think this can be closed now

Mind if I ask why? (Also I'll do this once I finish the custom keybinds PR)

**Comment by JaceThings** [comment]
> Mind if I ask why?

Oh, sorry. I noticed that the related ticket was closed, and it seems like both of them are asking the same thing. My mistake if they aren't. 😅

**Comment by MrKai77** [comment]
Got it :)
I usually close duplicate issues and only keep the original (non-duplicate) one open.

**Comment by MrKai77** [comment]
Done!
[Loop.zip](https://github.com/MrKai77/Loop/files/13796336/Loop.zip)
