### ISSUE TITLE
✨ App icons shadow

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#79]
### Feature Request Description

I've found that all the app icons have a narrower shadow than the ones normally found in macOS icons.

### Screenshots

![Icon differences](https://github.com/MrKai77/Loop/assets/101254295/0918e9bc-eed7-42f6-9914-5dc5f14c1c9d)

### Additional Context

If you want I can help with that by redoing the icons, or suggest using the [Production Templates](https://developer.apple.com/design/resources/#macos-apps) by Apple's HIG (the same one that I'm using but in Pixelmator).

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Alright, just did it! Just as a final check, does this look correct?
![Classic-1024](https://github.com/MrKai77/Loop/assets/68963405/a219768c-769e-4287-bb88-2cfb964b7a8f)

**Comment by Zabriskije** [comment]
This still looks a bit off:

![Differences](https://github.com/MrKai77/Loop/assets/101254295/b99d5a90-c146-4c31-a561-37d852080149)

[Here's a ZIP](https://github.com/MrKai77/Loop/files/13197710/Shadow.zip) with the correct shadow in PNG and SVG formats. I've made both in 1024x1024px, but if they're not automatically centered, they both should be placed 10px vertically below the perfect center (Y axis).

**Comment by MrKai77** [comment]
Got it! 
I guess there might have been an issue when importing Apple's template (a Sketch file) into Figma!
Anyways, here it is now! Does it look correct this time?
![Classic-1024](https://github.com/MrKai77/Loop/assets/68963405/56d1b855-808c-4583-849a-a6bb852588e8)

**Comment by Zabriskije** [comment]
Perfect 👌

You did a great job with the icons. Nice touch to use them as a reward when using Loop :)
I love the Rosé Pine and the Holo one – and also the pattern (the one used in the readme header).
