### ISSUE TITLE
🐛 Enabling "Middle Button Trigger Loop" will affect the drag operation of the left mouse button.

### ISSUE THREAD

**Issue by caocanx** [MrKai77/Loop#83]
### Bug Description

This bug will not disappear unless the computer is restarted.

### Steps To Reproduce

1. Enable "Middle Button Trigger Loop"
2. Use mouse middle button trigger Loop. For example, move a window to right.
3. Open chrome and select full url in the address bar, and press mouse left button to drag the selected url to bookmark bar, release the button. It will failed to drop it.

### Expected Behavior

Normally, use left mouse button drag the selected url to the bookmark bar will add it.

### Actual Behavior

It will failed to drop it.

### MacOS Version

Sonoma 14.2

### Loop Version

Version 1.0.0-beta.11 (465)

### Additional Context

https://github.com/MrKai77/Loop/assets/15025287/0919dbe2-549b-4ce3-af83-913e9bf716ff

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Thanks for reporting this issue! 
Unfortunately, I am unable to reproduce this. Does this only happen when dragging chrome tabs into the bookmarks bar? Or does it also interfere with dragging windows around or dragging files in Finder etc. as well?

**Comment by caocanx** [comment]
It will affect many operations related to dragging with the left mouse button, such as dragging files from the desktop to Finder, changing colors in Figma's color picker.

https://github.com/MrKai77/Loop/assets/15025287/1fb49f85-3d86-41ca-85ba-8aa7d36e664c

**Comment by caocanx** [comment]
Found a temporary solution, which is to click the mouse wheel in the blank area. Everything will return to normal until the middle mouse button is used again to trigger Loop.

**Comment by MrKai77** [comment]
Interesting... I was able to reproduce this bug just now! I'll look into fixing it!

**Comment by MrKai77** [comment]
I think I was able to fix it! Would you be able to verify that it doesn't happen anymore?
[Loop.zip](https://github.com/MrKai77/Loop/files/13323350/Loop.zip)

**Comment by caocanx** [comment]
> I think I was able to fix it! Would you be able to verify that it doesn't happen anymore? [Loop.zip](https://github.com/MrKai77/Loop/files/13323350/Loop.zip)

I tested it, and now it works very well. Thank you.
