### ISSUE TITLE
✨ Ability to restore initial frame when window is dragged

### ISSUE THREAD

**Issue by baschte** [MrKai77/Loop#87]
### Feature Request Description

Hey @MrKai77,
i would love if you could add an option that the pinned window gets its initial size automatically if the window is dragged away from its pinned position after some threshold.

**Example:**
You drag an Finder window to the top to get it fullscreen. If you drag it a little bit away from the top bar it will get its initial frame size automatically instead of pressing hotkey + Z. Hope you get an idea what i mean. 

thank you and best regards!

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Great idea! I recall this being in Rectangle too!
I'll definitely look into this :)

**Comment by baschte** [comment]
thank you! Would love to see this feature in Loop :-)

**Comment by MrKai77** [comment]
Alright, let me know how this is (the setting is enabled by default)!
[Loop.zip](https://github.com/MrKai77/Loop/files/13757791/Loop.zip)

**Comment by baschte** [comment]
Hey @MrKai77 thats exactly what i missed and love! Thank you for your implementation! 

I get a Problem on Multi Screens where the Full screen position isnt recognized correct. But i guess its no new Problem right?

Big thx for your App! Would love to donate something!

**Comment by MrKai77** [comment]
Awesome! Will merge!

> I get a Problem on Multi Screens where the Full screen position isnt recognized correct. But i guess it's no new Problem right?
 
This seems like a bug that's unrelated to this one, so I'd recommend opening a new issue! Also, I can't seem to reproduce it on my side :(

> Big thx for your App! Would love to donate something!

Thank you so much! I'm planning to open a GitHub Sponsors page soon :)

**Comment by baschte** [comment]
hey @MrKai77,
i got a problem with your compiled version here in the issue. When i hard close the apple messages app and opened it the drag an snap functionallity doesnt work anymore until i restart the loop app. On the actual released beta is everything fine so it could be an issue with the feature you implemented here.

Best regards and happy xmas btw.

**Comment by baschte** [comment]
ok so i compiled the actual master and there no issues. Seems to be a only a problem with the version you posted here :-) Hope you have nice holidays! 

Best regards

**Comment by MrKai77** [comment]
Awesome!

> I'm planning to open a GitHub Sponsors page soon :)

Just finished!
Merry xmas to you too!

**Comment by baschte** [comment]
Great! Thx for your app and time you share to develop this. 😁
