### ISSUE TITLE
✨ Allow Trigger Key to be Hyperkey

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#89]
### Feature Request Description

I currently use Rectangle Pro for my window management, and it allows me to set multiple keys for the trigger key. Personally, I have mapped Right ⌘ to ⌘⌥⌃⇧ and use Right ⌘ + [character] to move my windows.

I have used Loop for 1 minute, and I already want to switch to Loop from Rectangle. However, this single feature is stopping me (and custom keybinds, but I saw a ticket for that already) from replacing rectangle. Hope this feature gets implemented asap. Loop has **insane** potential, and the animations are **_incredible_**, following the project as its developed!

### Screenshots

![000505@2x](https://github.com/MrKai77/Loop/assets/60551230/14eb652a-995b-4b5a-8ce2-b166a381de0e)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thank you so much!
Actually, the hyperkey functionality has already been implemented in #75! Feel free to try the test builds posted there :) (although they are still a little buggy)
