### ISSUE TITLE
✨ Option to "Almost Maximize" a window

### ISSUE THREAD

**Issue by rohithvenkatesh** [MrKai77/Loop#93]
### Feature Request Description

Hi!

I'd love an option to set a percent (or even a fixed percent) to _almost maximize_ the window. 

I find that I like having certain windows at a "reasonable size", like around 60-70% of the maximize size. This is useful for apps like calendars or todo apps that don't need to take up the entire screen. 

Thank you so much for this awesome window manager!

### Additional Context

Rectangle also has this feature if you'd like to see it in action (but I like Loop a lot better :))

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thank you so much!
I'll definitely add this!

**Comment by UsamaKarim** [comment]
Almost Maximize is also required when you are using stage manager. It maximizes the window and leaves the space for stage manager.

**Comment by MrKai77** [comment]
Here it is!

[Loop.zip](https://github.com/MrKai77/Loop/files/13758035/Loop.zip)

ALSO: this includes breaking changes to the keybind system so all your custom keybinds will be gone when using this version.

EDIT: the commit above meant "Maximize", not "Resize" 😋
