### ISSUE TITLE
✨ Import/Export Settings

### ISSUE THREAD

**Issue by SenpaiHunters** [MrKai77/Loop#96]
### Feature Request Description

While Loop is nice, being able to import and export your settings is a much-needed update. It eliminates the need to set up the app each time and allows you to have fallbacks.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Good point! I'll see what I can do!
