### ISSUE TITLE
✨ Custom Size (in px & %) & Position

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#98]
### Feature Request Description

Rectangle Pro enables you to define custom sizes and positions for windows and associate those presets with custom shortcuts. This effectively addresses any user's request for specific window sizes. My favorite option is also the ability to cycle through a list of sizes using the same keybind, which Loop already does for some existing directions like left, right, up, and down.

Rectangle only allows you to set sizes in pixels, but I think it would be great to add the option of using percentages. Sometimes, you may want a window to take up 33% of the screen and then resize another window to take up 66%, giving you a 1/3 - 2/3 split.

Another cool option, which seems like a quality-of-life feature, is the ability to preview the footprint of the custom preset you've just created.

### Screenshots

![000703](https://github.com/MrKai77/Loop/assets/60551230/43c1336c-e89e-4137-86f4-5852f63644b6)
![000704](https://github.com/MrKai77/Loop/assets/60551230/f19f6ea3-1618-4dd0-96d5-12118cc51166)
![000705](https://github.com/MrKai77/Loop/assets/60551230/6501254f-f90b-4518-853f-d64112eb05d9)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
ohhh I really like this idea, especially the percentage part!
I've been wanting to put this feature in Loop for a while as well too, so stay tuned!

**Comment by MrKai77** [comment]
Alright, got the basic functionality working! I'm pretty excited about how this is turning out!

<img width="562" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/c336ba1f-d4cb-4bf3-8ef5-1ab64a0b7607">

**Comment by MrKai77** [comment]
Latest version:

<img alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/06837482-1deb-4058-889b-c876af95bfbf">


Todo:
- Make preview window show custom window sizes
- Add footprint window (aka temporarily enable preview window)

**Comment by MrKai77** [comment]
Alright, custom keybinds now work!
[Loop.zip](https://github.com/MrKai77/Loop/files/13781434/Loop.zip)

**Comment by JaceThings** [comment]
Oop... menu to small 😅
![002166@2x](https://github.com/MrKai77/Loop/assets/60551230/07893aed-33b5-4810-924b-b984facfbfa0)

**Comment by JaceThings** [comment]
Would there be any chance to add cycles to custom sizes too... ?
![002167@2x](https://github.com/MrKai77/Loop/assets/60551230/f510cd30-9143-4f20-a3ef-33d00ae28509)
![002168@2x](https://github.com/MrKai77/Loop/assets/60551230/5d7734a8-1a1d-477e-82ce-f0e163d5628c)

**Comment by MrKai77** [comment]
Custom cycle keybinds now work!
~[Loop.zip](https://github.com/MrKai77/Loop/files/13790208/Loop.zip)~

EDIT:
Here's a newer build that removes the jittering of the preview window:
[Loop.zip](https://github.com/MrKai77/Loop/files/13790258/Loop.zip)

<img width="700" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/9c53c468-8e6c-4dc8-89c9-68be9e2d2fbc">

**Comment by JaceThings** [comment]
That's it! 👏👏👏 Absolutely perfect, and even better than Rectangle Pro. All that's left is multi-monitor support, and Loop will pretty much be the most feature-packed non-tilable window manager ever made for Mac.
