### ISSUE TITLE
✨ Window padding only enabled on external monitors

### ISSUE THREAD

**Issue by noahkiss** [MrKai77/Loop#99]
### Feature Request Description

I personally love window padding, but only when my windows are on an external monitor. When I'm just using my laptop screen, it feels too crowded if padding is used - pixels are at more of a premium on a 14" screen than a 40", ya know?

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Will be on the latest prerelease :)

Check here for instructions: #502
